### ISSUE TITLE
Make Gag time sand pouch have no EMC so you dont accidently nuke it in transumation tablet.

### ISSUE THREAD

**Issue by thezeesystem** [ChosenArchitect/Project-Architect-2#1]
**Is your feature request related to a problem? Please describe.**
->gag:time_sand_pouch has EMC Value  Shouldn't have any (time in bag gets nuked when put into transmutation tablet)

**Describe the solution you'd like**
-> EMC value shouldn't be on it.

**Additional context**
->time in bag gets nuked when put into transmutation tablet

**Comment by ChosenArchitect** [comment]
Fixed in 2.2

**Comment by ChosenArchitect** [comment]
Fixed in next update!
