### ISSUE TITLE
No EMC values assigned for: Asurine, Crimsite, Ochrum, Veridium

### ISSUE THREAD

**Issue by James103** [ChosenArchitect/Project-Architect-2#10]
**Describe the bug**
There are no EMC values assigned for Asurine, Crimsite, Ochrum, or Veridium. This makes these blocks relatively scarce, hindering people who like to build with blocks from the Create mod, including these four.

**To Reproduce**
Check in JEI (search `@create` and scroll down) and notice no EMC values are assigned for Asurine, Crimsite, Ochrum, or Veridium.

**Expected behavior**
There should be EMC values assigned for Asurine, Crimsite, Ochrum, and Veridium, based on the yield and EMC value of the corresponding minerals (as these blocks can be processed like ores to get minerals and aren't just for decoration).

Out of these four blocks, my rough calculations indicate Ochrum should have the highest EMC value, followed by Crimsite and Veridium, then Asurine.

**Screenshots**
N/A (yet)

**Modpack version**
Base: 2.2
Added: Xaero's World Map, Xaero's Minimap
Removed: Daily Dad, Ambient Environment, Nyf's Spiders
**Java Version**
17.0.3, using 64 (amd64) architecture, from Eclipse Adoptium.
**Modpack Launcher Used**
Prism Launcher
**Ram Allocated**
6144 MB

**Comment by ChosenArchitect** [comment]
They will eventually have EMC values but I think first I will need to remove the functionality from create processing in order to implement them correctly. Definitely working on it but we'll take a bit of time :D

**Comment by ChosenArchitect** [comment]
fixed in next update!
