### ISSUE TITLE
JEI Villager UI Bug

### ISSUE THREAD

**Issue by OnscreenNova** [ChosenArchitect/Project-Architect-2#100]
**Describe the bug**
-> Items within the villager trades tab in JEI do not show up, however they are still there.

**To Reproduce**
1. Open JEI
2. Open the Villager Trades tab via any recipe

**Expected behavior**
-> "Empty" slots should show the item that is clearly meant to be there.

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)
![2024-08-07_08 48 13](https://github.com/user-attachments/assets/066f3958-da06-4c97-bd61-2e4e8af7d490)
![2024-08-07_08 51 30](https://github.com/user-attachments/assets/5ab1df3f-627a-4b62-826d-1a73f2762b18)

**Modpack version**
-> 3.0
**Java Version**
-> 1.20.1
**Modpack Launcher Used**
-> Curse Forge
**Ram Allocated**
-> 10gb

**Additional context**
->

**Comment by monkeybug34** [comment]
similar to this, JEI doesn't show all professions correctly when looking up villager POIs

**Comment by IRicTheCoder** [comment]
Unfortunately, this is mod related, it is an issue with the Just Enough Resources (think that is the one that adds it) addon for JEI and might not be something we can easily fix, if we can even fix it at all.

**Comment by IRicTheCoder** [comment]
> similar to this, JEI doesn't show all professions correctly when looking up villager POIs

As for this, it seems to be an issue with More Villagers that does not implement the POIs and other things as it should, resulting in them not being listed.

Edit: Talked to the JEP's Developer, might be a way for us to make a temporary fix on this, however, this is an issue with MoreVillagers not registering things the convencional way.

**Comment by IRicTheCoder** [comment]
The two issues discussed here has been fixed in version 4.0, the trades not present from More Villagers have been added as information to the quest book. And the items should now appear due to the new JEI update. Closing as solved, reopen if the issue persists.
