### ISSUE TITLE
Sophisticated Backpacks EMC Right Clicking Issue

### ISSUE THREAD

**Issue by MooMcMooman** [ChosenArchitect/Project-Architect-2#101]
**Describe the bug**
-> A dupe involving EMC-able items and Sophisticated Backpacks

**To Reproduce**
1.  Craft Backpack of any tier
2.  In Trans table, pick up backpack
3.  Right click over any item
4. Item is stored in backpack without any emc taken out

https://github.com/user-attachments/assets/096ffbc6-f8e3-49a4-9dfd-7453c6e33290

**Expected behavior**
-> EMC taken out or item not stored

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)
https://github.com/user-attachments/assets/096ffbc6-f8e3-49a4-9dfd-7453c6e33290
**Modpack version**
-> 3.1
**Java Version**
-> 8 Build 361
**Modpack Launcher Used**
-> Curseforge
**Ram Allocated**
->11040 / 29k

**Additional context**
->

**Comment by shiftthedev** [comment]
that's really insane. thanks for reporting.

**Comment by ChosenArchitect** [comment]
Shift made this mod that fixes this issue
https://www.curseforge.com/minecraft/mc-mods/sophisticated-backpacks-container-blacklist
