### ISSUE TITLE
Alchemical Collection enchant breaks learning objects (with workaround)

### ISSUE THREAD

**Issue by Xetaxheb** [ChosenArchitect/Project-Architect-2#103]
As here: https://github.com/DonovanDMC/ProjectExpansion/issues/139

TL;DR If you alchemical collection (convert mined drops to emc if they have it) a block that isn't learned yet, whatever it is will be unlearnable and unsearchable until you un-learn it manually first.

**Comment by IRicTheCoder** [comment]
This should be fixed (till the mod fixes it directly) in version 3.4+, closing it as solved. If you still find this behavior please reopen the issue, thanks!
