### ISSUE TITLE
CTD When crafting using crafting module in Sophisticated Storage

### ISSUE THREAD

**Issue by cherubael1010** [ChosenArchitect/Project-Architect-2#105]
**Describe the bug**
-> CTD when pulling items out of the crafting grid using the crafting table built into the Sophisticated Storage chest module. It is a intermittent issue, happening no matter if crafting in bulk or single items

**To Reproduce**
1.  Craft items
2. 
3. 
4. 

**Expected behavior**
->Use table as normal and not have a CTD

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)

**Modpack version**
->3.1
**Java Version**
->TBH idk, I'm pretty sure I'm up to date
**Modpack Launcher Used**
-> CurseForge
**Ram Allocated**
->12k MB

**Additional context**
->Crash report makes a mention about slot 9 having issues.
I appologise about not having a screenshot of the crash report, ill update it if I get it again

**Comment by cherubael1010** [comment]
https://mclo.gs/gGLbP9j

**Comment by shiftthedev** [comment]
duplicated #20
