### ISSUE TITLE
RFtools Dimension crashing 

### ISSUE THREAD

**Issue by Athalin86** [ChosenArchitect/Project-Architect-2#106]
**Describe the bug**
-> I created 2 random dimensions with rftools. The first would crash a few seconds after loading. the second dimension i tried doesn't crash immediately, but bounces between below 10 fps to 60+ and crashes eventually. 

**To Reproduce**
1. enter an RFtools dimensions 
2. 
3. 
4. 

**Expected behavior**
-> explore the dimension at the framerates and stability i experience in the rest of the game.

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)

**Modpack version**
-> 3.1
**Java Version**
-> version 8 update 421
**Modpack Launcher Used**
-> curseforge 
**Ram Allocated**
->16288m
[crash report.docx](https://github.com/user-attachments/files/16534601/crash.report.docx)

**Additional context**
->

**Comment by RxDoc** [comment]
I have a crash report for the same issue if this helps
[crash-2024-08-10_09.04.28-server.txt](https://github.com/user-attachments/files/16570116/crash-2024-08-10_09.04.28-server.txt)

**Comment by ChosenArchitect** [comment]
I hope this is fixed in the next updat! I removed Formations
