### ISSUE TITLE
Suggestion, add project red mods

### ISSUE THREAD

**Issue by pantherpusher** [ChosenArchitect/Project-Architect-2#107]
**Is your feature request related to a problem? Please describe.**
->N/A

**Describe the solution you'd like**
->N/A

**Describe alternatives you've considered**
->N/A

**Mod Sugestions**
->The project red series

**Additional context**
->
Equivalent Exchange feels weird without having Red Power alongside it, maybe I'm just old but I think it'd sure be neat to have the successors to the red power mod included.

**Comment by ChosenArchitect** [comment]
We tested Project Red and it had texture issues that were kinda all over the place. I decided to pull that mod

**Comment by pantherpusher** [comment]
> We tested Project Red and it had texture issues that were kinda all over the place. I decided to pull that mod

Aw, well that sucks. Oh well. Can't fault you if you tried.
