### ISSUE TITLE
Experience Quadrupling

### ISSUE THREAD

**Issue by TheViperman** [ChosenArchitect/Project-Architect-2#108]
**Describe the bug**
Hero's Medallion quadruples exp after right-clicking an Experience Crystal.

**To Reproduce**
1. Get a Hero's Medallion
2. Right-click with the Medallion on Experience Crystal containing some levels.
3. Check the Medallion's tooltip, it now contains over 4x more levels.
4. (Optional) Put the Medallion on a pedestal and pump the experience back into Experience Crystal using any fluid pipe. The Crystal should now also show the quadrupled levels.

**Expected behavior**
Hero's Medallion should not quadruple experience when absorbing Essence from the Crystal.

**Screenshots**
![1](https://github.com/user-attachments/assets/3a87766c-aefe-442d-b616-d2d0a491eb74)
![2](https://github.com/user-attachments/assets/7c53f4d4-bdcc-4ef6-b453-09cc72f8ac61)

**Modpack version**
3.1
**Java Version**
17.0.8 64bit
**Modpack Launcher Used**
Curseforge
**Ram Allocated**
16GB

**Additional context**
n/a

**Comment by ChosenArchitect** [comment]
Is fixed in next update!
