### ISSUE TITLE
Mod/texturepack sugestion

### ISSUE THREAD

**Issue by MatteoPL** [ChosenArchitect/Project-Architect-2#110]
**Mod Sugestions**
-> ae2 texture backport https://modrinth.com/resourcepack/ae2-texture-backport 
It's a backport to 1.20.1 of new ae2 textures which are a lot better.

**Comment by shiftthedev** [comment]
if its not on curseforge, it can't be added.

**Comment by MatteoPL** [comment]
> if its not on curseforge, it can't be added.

Oh my bad. I thought that you can add mods using modpack files.
