### ISSUE TITLE
The "More Villagers" mod is a bit much

### ISSUE THREAD

**Issue by pantherpusher** [ChosenArchitect/Project-Architect-2#111]
**Describe the bug**
-> I am pretty sure that the "More Villagers" mod is out competing the vanilla villager house types, there are a ton of them to the point it feels like the only villagers that exist are the oceanographers, the foresters, the hunters, and the flower guys.

**To Reproduce**
1. Find a village
2. Home invade
3. Notice the lack of diversity

**Expected behavior**
-> A more diverse variety of villager professions and homes.

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)

**Modpack version**
->3.1
**Java Version**
->17.0.8
**Modpack Launcher Used**
->Curseforge
**Ram Allocated**
->8000mb

**Additional context**
->

**Comment by OnscreenNova** [comment]
I cant say the same, of the 4 villages ive stumbled across, all of them have a wide variety of vanilla professions.

**Comment by pantherpusher** [comment]
maybe I was just getting unlucky
