### ISSUE TITLE
RFTools dimensions still accessible and safe when unpowered

### ISSUE THREAD

**Issue by M4trixm4n** [ChosenArchitect/Project-Architect-2#112]
I'm not sure if it's intended, or if it's the case in the base mod, and not only the modpack. When trying to access a random old dimension that wasn't powered (dimension tab was empty of power), well I just could. No problem at all, when it's supposed to be the main concern about RFTools' dimensions. I expected to die or have very heavy bad effects.

1. Create a dimension
2. Build and power it with the dimension builder
3. Enter the dimension then leave it
4. Remove the dimension tab from the dimension builder and let the power drain away
5. Enter the dimension when the dimension tab is empty

**Modpack version**
->3.1
**Java Version**
->It's on a server (which isn't the cause I'm quite certain) so I would assume latest
**Modpack Launcher Used**
->/
**Ram Allocated**
->/

**Comment by Waikiki-Tim** [comment]
I have noticed this issue too in Modpack version 3.2. I placed Waystones in all the worlds I created and I'm still able to access all of them even though I've reused my dimension tab for each one. I guess it gives me time to build a better power infrastructure. ;-)

**Comment by IRicTheCoder** [comment]
Unfortunately, this is an issue with RFToolsDimensions itself, we can try tweaking some configs but "unused"/unpowered dimensions seem to be problematic in general.

**Comment by IRicTheCoder** [comment]
After looking through RFToolsDimensions config and testing a lot of things, this seems a consequence of some design decisions on the mod side. Nothing we can do about it, besides tweaking the config which should now make you get debuffs when accessing those dimensions.

As of 4.0, this should work better and as the mod originally intended. We might add some more tweaks in the future if possible, but for now that is not the case. Will close this as solved, reopen if the issue ends up happening again.

NOTE: Old dimensions might still have this issue, but new ones should not.
