### ISSUE TITLE
Old Miners Bundle OffHand Bug

### ISSUE THREAD

**Issue by Gallucky** [ChosenArchitect/Project-Architect-2#113]
**Describe the bug**
-> When using the item `Old Miners Bundle` in the offhand the item is not getting consumed but rather the item in the main hand.

**To Reproduce**
1. Take one instance of the `Old Miners Bundle` item and put it in the offhand
2. when the **main hand is empty** the item is **not** consumed and the rewards are still generated.
3. when the **main hand has an item** in it like a good enchanted pickaxe the `Old Miners Bundle` item **does not get consumed but rather the pickaxe**.
4. If in the main hand there is stackable item then only **one** is removed for example 7 gold ingots will become 6 gold ingots **[if the rewards from the `Old Miners Bundle` did not contain gold ingot(s)]**

**Expected behavior**
-> The `Old Miners Bundle` will be consumed the rewards will appear in the inventory [if there are any remainders and the inventory is full they will be **dropped into the ground**] and most importantly **the main hand item will not be consumed** like the Good Enchanted Pickaxe.

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)

**Modpack version**
-> `3.1 (Release)`
**Java Version**
-> `Minecraft: 1.20.1`
**Modpack Launcher Used**
->`CurseForge`
**Ram Allocated**
->`12064 MB`

**Additional context**
->

**Comment by shiftthedev** [comment]
[known issue](https://legacy.curseforge.com/minecraft/mc-mods/spelunkers-charm-ii/issues/4)

**Comment by ChosenArchitect** [comment]
Should have a sorta workaround for this next update thanks to Shift!
