### ISSUE TITLE
Range Addon EMC Values

### ISSUE THREAD

**Issue by YamenTheMan** [ChosenArchitect/Project-Architect-2#114]
**Describe the bug**
-> Some range addons from Industrial Foregoing have EMC values, which I assume is an oversight. The only ones affected are those with EMC having items in the recipe

**To Reproduce**
1. No real steps, just look at the Addon Range : 1,2,3,9,10,11

**Expected behavior**
-> Didnt expect the range addons to have EMC for some and not others

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)
![image](https://github.com/user-attachments/assets/b6fb3f7f-91c8-49ce-b856-3bf08b608844)
![image](https://github.com/user-attachments/assets/7fdd62dd-9db8-4d37-9d15-ca1563980418)
![image](https://github.com/user-attachments/assets/d1a2e792-9ead-4701-a151-d20f9dedf945)
![image](https://github.com/user-attachments/assets/af11c81e-5a5d-4dea-8564-5141fb6e600b)
![image](https://github.com/user-attachments/assets/a47e3489-f710-4893-ba84-565e48cc0c07)
![image](https://github.com/user-attachments/assets/4cf6ff3a-ac9f-4d01-a31a-7547c456abd2)
![image](https://github.com/user-attachments/assets/bca4d147-25bf-421b-be9c-5da84d7d717c)

**Modpack version**
->3.1
**Java Version**
-> If its the game, 1.20.1
**Modpack Launcher Used**
->Curseforge
**Ram Allocated**
->10096 MB

**Additional context**
->

**Comment by ChosenArchitect** [comment]
Thanks for pointing that out! It should be fixed in next update!
