### ISSUE TITLE
Sugar canes don't grow more than vanilla even if in the Apotheosis config it's set to be at 255 max

### ISSUE THREAD

**Issue by Porkemon211** [ChosenArchitect/Project-Architect-2#115]
**Describe the bug**
-> Sugar canes don't grow more than vanilla even if in the Apotheosis config it's set to be at 255 max

**To Reproduce**
1. Plant sugar cane in sand, dirt, snad
2. Wait
3. Sugar canes don't grow more than 3 blocks tall
4.

**Expected behavior**
-> Sugar canes should grow to a max of 255 and instead don't grow more then 3 blocks

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)

**Modpack version**
-> 3.1
**Java Version**
-> Java 17.0.8
**Modpack Launcher Used**
-> Curseforge
**Ram Allocated**
-> 8GB

**Additional context**
->

**Comment by ChosenArchitect** [comment]
That feature if disabled
