### ISSUE TITLE
"Pig" Quest in Adventure Bound not completable

### ISSUE THREAD

**Issue by exastencil** [ChosenArchitect/Project-Architect-2#116]
**Describe the bug**
->  In the quest "Pig" in the "Adventure Bound" section, there is a task for cooked whole crab which is no longer in the pack. The recipe for the pig plushie no longer requires it, but the quest no longer completes and since it is a prerequisite for the "Amalgamation" quest the remainder of the questline cannot be completed. I had started this world on an earlier version and upgraded so I'm not sure if this is an edge case that happens with older worlds.

**To Reproduce**
1. Unlock the "Pig" quest.
2. Obtain all the food items required.

**Expected behavior**
-> The quest should complete.

**Screenshots**
![Screenshot 2024-08-09 at 22 42 53](https://github.com/user-attachments/assets/32d10807-2663-42bf-bbe3-649881cb9734)

**Modpack version**
->  3.1
**Java Version**
->  Eclipse Adoptium 17.0.2 (aarch64)
**Modpack Launcher Used**
-> Prism Launcher 8.4
**Ram Allocated**
-> 8GB

**Additional context**

-> If anyone else is having this problem a manual way to get around this is the use the command `/ftbquests editing_mode` (this doesn't require cheats to be enabled), opening the quest "Pig" and right-clicking the question mark and selecting "Delete". Then exit the questing interface and retype the command `/ftbquests editing_mode` to turn edit mode off. Then exit and save your world and load it back up. Your quest should register as completed and you can carry on.

**Comment by shiftthedev** [comment]
the cooked whole crab wasn't removed.
you maybe need to reinstall the pack.

**Comment by ChosenArchitect** [comment]
in my indev pack its working so something didn't download on your end seems you are missing the Quark Delight mod for some reason.
![image](https://github.com/user-attachments/assets/4a3cae96-7ba6-45ff-b9e5-ec9640af10a8)
