### ISSUE TITLE
Chunk Loading

### ISSUE THREAD

**Issue by PokeNitro** [ChosenArchitect/Project-Architect-2#117]
**Describe the bug**
->a couple of my friends and I have noticed an inability to load chunks. the chunks load so slow that even with sprinting you can run into a dead chunk. we know it's not an issue of our computers, as our gpu, cpu, and any other relevant resource is not being fully utilized, and not having any issues running the game.

The chunks don't load on our server, or on any of our clients. (tested on 3 clients) We can't figure out the issue, so we come to you with this report.

**To Reproduce**
1. open world
2. move in one direction
3. chunks don't load

**Expected behavior**
->The expectation is for chunks to load at a normal speed

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)
![2024-08-09_21 29 58](https://github.com/user-attachments/assets/396d6d4d-1a67-47aa-be4b-3336d6e66105)

**Modpack version**
->2.3.1
**Java Version**
->Latest
**Modpack Launcher Used**
->CurseForge
**Ram Allocated**
->tried everything from 2800-12000

**Additional context**
-> The server has had no problems running modpacks of this size in the past before.

**Comment by ChosenArchitect** [comment]
Please update the modpack. The latest version if 3.1
