### ISSUE TITLE
Plushies missing EMC values

### ISSUE THREAD

**Issue by VendoAU** [ChosenArchitect/Project-Architect-2#118]
Since most plushies have EMC values I think it would make sense for all of them to have EMC
These ones are missing:
- Allay
- Sniffer
- Killer Bunny
- Iron Golem
- Wandering Trader
- Villager
- Pillager
- Vindicator
- Ravager
- Vex
- Wither Skeleton
- Piglin Brute
- Ghast

**Comment by ChosenArchitect** [comment]
Fixed next update!
