### ISSUE TITLE
maybe a You issue maybe not Lantern Emc?

### ISSUE THREAD

**Issue by DiggityMan420** [ChosenArchitect/Project-Architect-2#12]
**Describe the bug**
-> looking at a lantern in world has emc but when in inventory has none see images

**To Reproduce**
1. place lantern
2. look at lantern see emc in jade
3. place lantern in table no emc attached 

**Expected behavior**
-> emc attached to or removed from

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)

**Modpack version**
->2.3

**Java Version**
->17.0.8 64bit

**Modpack Launcher Used**
->Curseforge

**Ram Allocated**
->8gb

**Additional context**
-> see images

![Screenshot_34](https://github.com/user-attachments/assets/b1ed27ca-c464-4eb6-a8d2-e93549a639a8)
![Screenshot_33](https://github.com/user-attachments/assets/c884333a-3859-4657-91ee-c27b81a75cc5)
![Screenshot_32](https://github.com/user-attachments/assets/0763e3c6-d4f7-4a20-b3cb-07d9b0bbca7a)

**Comment by shiftthedev** [comment]
Jade issue with ProjectE
