### ISSUE TITLE
Wither Builder Not Working In Claimed Chunks

### ISSUE THREAD

**Issue by realSimon157** [ChosenArchitect/Project-Architect-2#120]
**Describe the bug**
->The Wither Builder is only working outside the claimed chunks

**To Reproduce**
1. Claim a chunk
2. Place a wither builder in the claimed chunk
3. (Try to spawn the Wither using the Wither Builder)

**Expected behavior**
->I expected the Wither to spawn

**Modpack version**
->3.1
**Java Version**
->17.0.8 (64-bit)
**Modpack Launcher Used**
->Curseforge
**Ram Allocated**
->10GB

**Comment by ChosenArchitect** [comment]
You need to enable Fake Players in your Team settings for your claims!
![image](https://github.com/user-attachments/assets/f54f8498-4b54-49fa-913b-f84496995d56)
