### ISSUE TITLE
Red heart canisters are not craftable

### ISSUE THREAD

**Issue by VendoAU** [ChosenArchitect/Project-Architect-2#121]
**Describe the bug**
-> Red heart canisters can't be crafted because baubley heart canister's wither bones are unobtainable and they have a different tag

**To Reproduce**
1. Check the recipe in JEI

**Expected behavior**
->`architects_pallete:witherered_bone` should allowed in the recipe

**Modpack version**
-> 3.1
**Java Version**
-> 17.0.7
**Modpack Launcher Used**
-> Prism
**Ram Allocated**
-> 6G

**Additional context**
->Need to either change the recipe or add the `#forge/wither_bones` tag

**Comment by shiftthedev** [comment]
i can confirm that Wither Bones from the BHC mod drop from Wither Skeletons with a chance of 15% per kill.

**Comment by VendoAU** [comment]
> i can confirm that Wither Bones from the BHC mod drop from Wither Skeletons with a chance of 15% per kill.

I got really unlucky and didn't get any, but after I saw your message I got one first try lol.

The loot table and recipes should probably be updated to only have one type of withered bone still.
