### ISSUE TITLE
Breaking a modular router with a Draconic Evolution weapon in the buffer deletes the weapon's modules

### ISSUE THREAD

**Issue by M4trixm4n** [ChosenArchitect/Project-Architect-2#123]
You can use modular routers as mob grinders with the activator module, and you can put weapons in their buffer slot, which they will use to kill enemies. I placed my Wyvern Sword as a test, and when I was done i broke the modular router. Every module and upgrade stays inside the router, but the item in the buffer slots is dropped. When my sword was dropped, every module inside it disappeared. It's the same every time, with any module (didn't test everything), they just disappear. The Router's modules and upgrades do not matter, the result is the same each time.

1. Place a modular router
2. Put a Wyvern Sword with some modules in the router's buffer slot
3. Break the router
4. Check the dropped sword

**Modpack version**
-> 3.1

**Additional context**
->It's all on a server so Java version or RAM shouldn't matter.

**Comment by ChosenArchitect** [comment]
Ouch... um, I don't know if I could fix this one... I do know that Draconics has its own Mob Crusher that uses swords. I might be able to blacklist the use of Draconic tolls from modular routers however to prevent this. (still don't know if that's a good idea however)

**Comment by M4trixm4n** [comment]
If it's not fixable then I would prefer for it to stay like that, because there aren't a lot of alternative good swords/weapons that accept enchantments (the red matter sword and katar do not), and I use it mainly to get draconic souls and reliquary drops.

**Comment by IRicTheCoder** [comment]
We have deployed a fix for this, that fix should now allow you to get the right item back. It is slightly bugged in 3.4/3.5 but it will be fully fixed in 3.6. Closing this as the issue with the item drops has been essentially fixed.
