### ISSUE TITLE
Infinite EMC

### ISSUE THREAD

**Issue by Betahero** [ChosenArchitect/Project-Architect-2#124]
**Describe the bug**
-> The magma cream Bee queen trade is broken considering she will constantly trade with you.
The trade is constant profit of EMC give her magma cream and she spits out either a ghast tear(4,096)or glowstone dust(384).

**To Reproduce**
1.  Find bee queen in bumblezone
2. Trade magma cream
3.  Transmute glowstone and ghast tears
4. Repeat

**Expected behavior**
-> Maybe limit the trades or make the trade less favorable.

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)

**Modpack version**
->3.2
**Java Version**
->1.20.1
**Modpack Launcher Used**
->CurseForge
**Ram Allocated**
->8192 mb

**Additional context**
->

**Comment by pHAT-pHUC** [comment]
Did it, it does check out lol Free EMC. My house is now built out of red matter blocks.

**Comment by MooMcMooman** [comment]
Is the trade unlimited, unlike villagers?

**Comment by pHAT-pHUC** [comment]
yeah infinite

**Comment by aphroidite** [comment]
Wouldn't that be too slow to actually be considered "infinite"? I'm playing on a server with some friends and a couple of them already generate over 10 billion per second...

**Comment by Betahero** [comment]
> Wouldn't that be too slow to actually be considered "infinite"? I'm playing on a server with some friends and a couple of them already generate over 10 billion per second...

The point of me calling it Infinite wasn't about speed it was you can mine one log emc it into magma cream, trade, and have 10-100 magma cream. It's not intended and wasn't fun to find at the start of a mod-pack not even 8 hours in.
