### ISSUE TITLE
Quests

### ISSUE THREAD

**Issue by XenonsTech** [ChosenArchitect/Project-Architect-2#126]
**Is your feature request related to a problem? Please describe.**
-> when someone makes a crafts an item for a quest and they forget to hold the item for the previous crafts and I have to remake that item because I used it in a craft

**Describe the solution you'd like**
-> to add a feature

**Describe alternatives you've considered**
->  having the plushy *not limited to* give you the advancements from the items in the craft

**Mod Sugestions**
-> Idk

**Additional context**
-> I was making the wither and had forgot to hold the wither builder and had to remake it all over again by hand to get the quest

**Comment by ChosenArchitect** [comment]
The quest mode is set to flexible so it should work that way however if you forget to hold something when you craft it then you are not following the quests. I have no other way to show people whats needed without having items thats needed.
