### ISSUE TITLE
Mycelial Reactor doesn't seem to work

### ISSUE THREAD

**Issue by ZeusesNeckMeat** [ChosenArchitect/Project-Architect-2#127]
**Describe the bug**
-> The Mycelial Reactor is not generating any power. We have all other 16 Mycelial generators running and active, and the Reactor is not doing anything. 

**To Reproduce**
1.  Set up all Mycelial Generators and have them all producing power at once

**Expected behavior**
-> Would expect the Reactor to produce 25 Million FE/t

**Screenshots**
![2024-08-11_01 20 41](https://github.com/user-attachments/assets/05cb1ab0-2719-42f9-ae8f-d3f91b0668f4)

Energy Cell all generators and reactor are putting power into:
![2024-08-11_01 23 49](https://github.com/user-attachments/assets/49c9d6cb-fd77-47e0-9c35-b03136477339)

**Modpack version**
-> 3.1
**Java Version**
-> Unsure what version is used on the VPS I'm using to host the server
**Modpack Launcher Used**
-> Curse Forge
**Ram Allocated**
-> 10gb

**Comment by ChosenArchitect** [comment]
I dont think those mek pipes can keep up with the power gains from the 25mill and that would fill the pipe buffer shutting off the other generators when they get full. Try flux networks to handle the RF

**Comment by ZeusesNeckMeat** [comment]
I did originally have Flux Plugs on all of them, however the Mycelial Reactor isn't outputting any power at all. The internal progress never actually moves. I've seen people in discord talking about actually using them so they must be working, I just don't understand what I'm missing. All the other Mycelial Generators are running

**Comment by ZeusesNeckMeat** [comment]
I did originally have Flux Plugs on all of them, however the Mycelial Reactor isn't outputting any power at all. The internal progress never actually moves. I've seen people in discord talking about actually using them so they must be working, I just don't understand what I'm missing. All the other Mycelial Generators are running

**Comment by ZeusesNeckMeat** [comment]
Alright so I've learned that Shift and Right Clicking the reactor with an empty hand shows you what's wrong. Apparently there were several generators the reactor didn't register as actually running, even though they were. I'm not entire sure why, but breaking and re-placing those generators fixed the issue, and the Mycelial Reactor is actually working as expected now. Sorry about that.
