### ISSUE TITLE
White wool from blocks when right-clicking with the Red Katar

### ISSUE THREAD

**Issue by Waikiki-Tim** [ChosenArchitect/Project-Architect-2#128]
**Describe the bug**
->When I right-click with the Red Katar, I get wool. My Red Katar is fully "charged". I haven't tried it without it being charged.

**To Reproduce**
1. Walk up to a block like stone, andesite or chiseled brick. (These are the only ones I've tried so far.
2. Right click with Red Katar.
3. Check inventory for white wool that wasn't there before.
4. 
5. 

**Expected behavior**
->I expect to NOT receive while wool from anything other than a white sheep.

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)

**Modpack version**
->3.1
**Java Version**
->1.20
**Modpack Launcher Used**
->curseforge
**Ram Allocated**
->System settings, which I think is 6GB.

**Additional context**
->

**Comment by Waikiki-Tim** [comment]
![Snag_2719c826](https://github.com/user-attachments/assets/c6d86f75-99a7-4858-9f47-235de8da7824)

I got all this wool by right-clicking my Red Katar on the Illuminant Blcok(Inverted) above me. I have a 64x64 ceiling made of those blocks and I was in one of the corners of the room.

**Comment by shiftthedev** [comment]
have you added / removed / changed anything in the modpack?
I've tried multiple times and couldn't replicate this behaviour.

**Comment by Waikiki-Tim** [comment]
I responded via email to your (shiftthedev) post, but it didn't show up here.

I didn't add or remove anything. The only thing I changed that might be remotely related is that I changed my right-click setting to be the F key instead of the right mouse button. I don't how that could be relevant, but who knows.

I've upgraded to the latest version (currently 3.2) and I still can "shear" things other than sheep to get wool.

**Comment by Waikiki-Tim** [comment]
I don't know if this helps, but here is a screenshot from NBTExplorer that shows my katar.

![image](https://github.com/user-attachments/assets/4a6b20f2-f283-4450-befd-e19642e47c66)

**Comment by Waikiki-Tim** [comment]
I accidentally found out that it's not clicking a block that yields wool. It's just right clicking the Red Katar period. I get the same results when clicking in the air. It seems the longer I wait, the more I get, up to a point.

I don't find this annoying, just weird. And, it's not like it's a big cheat since, at this point, the amount of EMC I get is minuscule.

**Comment by Waikiki-Tim** [comment]
Please disregard. My base, the location where this phenomena occurs, is located near a city with a couple of sheep farms. My Red Katar is just AOE shearing them.

![image](https://github.com/user-attachments/assets/8358d1b9-8d1d-4e55-8c29-8af315c30495)

**Comment by Waikiki-Tim** [comment]
Closing this issue.
