### ISSUE TITLE
Mod Suggestion. 

### ISSUE THREAD

**Issue by delta2k** [ChosenArchitect/Project-Architect-2#13]
**Is your feature request related to a problem? Please describe.**
-> n/a

**Describe the solution you'd like**
-> would like to see this mod added. It allows you to connect pips/cables at long distances from point A to B.  it supports many mods.
it's a pretty cool mod for this modpack

**Describe alternatives you've considered**
-> a/n

**Mod Sugestions**
-> https://www.curseforge.com/minecraft/mc-mods/pipe-connector

**Additional context**
-> n/a

**Comment by IRicTheCoder** [comment]
As of now, this mod won't be added, the pack is mainly finished and we saw no need to add this mod. Thanks for the suggestion, closing this as not planned
