### ISSUE TITLE
RfTools dimensions still crashing

### ISSUE THREAD

**Issue by RxDoc** [ChosenArchitect/Project-Architect-2#130]
[crash-2024-08-11_12.07.33-server.txt](https://github.com/user-attachments/files/16574334/crash-2024-08-11_12.07.33-server.txt)
**Describe the bug**
->  Dimension crashed about 5 seconds after entering.  This is not a new dimension since the update.
    java.lang.IllegalStateException: Tried to biome check an unregistered feature, or a feature that should not restrict the biome

**To Reproduce**
1.  Enter my RfTools DImension
2.  Game crashes
3. 
4. 

**Expected behavior**
-> Entering dimension should not crash game.

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)

**Modpack version**
-> 3.2
**Java Version**
-> 19.0.1
**Modpack Launcher Used**
-> Curse Forge
**Ram Allocated**
-> 12GB

**Additional context**
-> Since the resolution of the previous bug states the problem was related to dimension creation, do we need to recreate old dimensions?

**Comment by ChosenArchitect** [comment]
I hope that I fixed this as I did some testing and should have fixed the Dirt tags from generating
