### ISSUE TITLE
Bugged Blitz Texture

### ISSUE THREAD

**Issue by Goosepignose** [ChosenArchitect/Project-Architect-2#131]
**Describe the bug**
->Agro Blitz texture from thermal series mod is sometimes black and blue checkered and bugged.

**To Reproduce**
1. Find Blitz
2. Go into survival
3. When it goes agro it sometimes has bugged texture.
4. N/A

**Expected behavior**
->It should look like agro texture that somtimes spawns

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)
![image_2024-08-11_151357168](https://github.com/user-attachments/assets/5a0642a0-295d-49f1-8c8d-56c9c394e131)

**Modpack version**
->3.2
**Java Version**
->17
**Modpack Launcher Used**
->Prism
**Ram Allocated**
->10 GB

**Additional context**
->N/A

**Comment by IRicTheCoder** [comment]
This has been reported before, it is an issue with ETF and Thermal Mobs, it is not necessarily something we can fix unfortunately.

**Comment by IRicTheCoder** [comment]
With some more recent updates, as of version 4.0 this should at least be a lot less frequent if not completely fixed. Closing this as solved for now, since we can't really do much to fix this. Reopen the issue if it still continues to happen. Thank you!
