### ISSUE TITLE
Draconic Armor and tools texture

### ISSUE THREAD

**Issue by nahiwouldloose** [ChosenArchitect/Project-Architect-2#132]
**Describe the bug**
-> Draconic armor and tools just wont show up neither in hand nor in any type of slots

**To Reproduce**
1. get draconic gear
2. put in hand or in slot
3. press f5
4. nothing there

**Expected behavior**
->should be visible

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)
![2024-08-12_18 13 01](https://github.com/user-attachments/assets/e25839bc-0b11-44e9-b515-60af24c3c7e0)
![2024-08-12_18 13 04](https://github.com/user-attachments/assets/92cdcddf-bb66-4ed8-8be2-a5e470ba69b0)

**Modpack version**
->3.2
**Java Version**
->newest
**Modpack Launcher Used**
->Curseforge
**Ram Allocated**
->10gb

**Additional context**
->is on server from gportal but it does not change in singleplayer

**Comment by ChosenArchitect** [comment]
I know this is an issue with the mod in this version... It also didn't render for me in ATM9TTS

**Comment by nahiwouldloose** [comment]
ah dang well then there is nothing to do about it till draconic updates i guess thank you anyway. 
by the way me and my friend are really enjoying the pack and your videos are great so thank you very much!
should i close this issue or leave it open if someone else wonders why it does not show?

**Comment by nahiwouldloose** [comment]
so basically i asked i some of the draconic evo guys it seems to be an incompatibility issue with oculus / immediatly fast mods with DE dont know if you can do anything about this but i guess its nice to know
