### ISSUE TITLE
Game freezing frequently during usual play

### ISSUE THREAD

**Issue by newborntigr** [ChosenArchitect/Project-Architect-2#133]
**Describe the bug**
-> As I am playing, I am getting frequent freezes. the game would be running fine, but then it would freeze for a second or 2. i dont know if its the game, or if its just an incompatibility with the shaders i am using (complimentary shaders)

**To Reproduce**
1.  Equip Complimentary shaders
2.  play for a while

**Expected behavior**
-> game runs smooth without any hiccups

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)

**Modpack version**
-> 3.2
**Java Version**
-> version 8 update 421
**Modpack Launcher Used**
-> FTB Launcher
**Ram Allocated**
-> 6132 mb

**Additional context**
-> it might just be my shaders, i dont know though. it only sstarted after i turned on the shaders

**Comment by ChosenArchitect** [comment]
I will say with shaders and only giving the modpack 6 gigs of ram you will run into this issue

**Comment by IRicTheCoder** [comment]
Since this did not get any more feedback after 3 weeks, will assume it has been resolved and close it. If the issue continues, feel free to re-open the issue.
