### ISSUE TITLE
I don't think I've ever played a pack that didn't show percentages of getting a product.

### ISSUE THREAD

**Issue by FishOutOfH20** [ChosenArchitect/Project-Architect-2#134]
**Is your feature request related to a problem? Please describe.**
Percentages for products and byproducts from both Create and Thermal are not displayed.  This is rather frustrating when deciding the best method of processing.  It makes it appear that it's set at 100%, which is not the case.

**Describe the solution you'd like**
I'd like to see what is typically shown in every pack.  Display the chance of getting such products.

![washing](https://github.com/user-attachments/assets/1f0f7409-3a4c-40d4-97b1-6a27ff260469)
![pulverizer](https://github.com/user-attachments/assets/0b852983-5610-403c-8ac4-59b9da44ef37)

**Comment by ChosenArchitect** [comment]
I might revert to a older JEI as the last few updates have broken this. Mezz is working on updating JEI

**Comment by ChosenArchitect** [comment]
Fixed next update 3.3
