### ISSUE TITLE
Remapping the JEI pevious recipe key is making this pack unplayable for me.

### ISSUE THREAD

**Issue by FishOutOfH20** [ChosenArchitect/Project-Architect-2#135]
**Describe the bug**
In every pack I play, I remap the previous recipe key from "backspace" to "mouse button 4", which is my thumb button.  It's also the default "back" key everywhere else on the web.  In this pack though, it skips right to the beginning, going back 3 or 4 recipes.  It is impossible to simply go back one recipe.

There's something wrong with the config somewhere.  I thought it might be a problem with my mouse suddenly, but after loading 3 other modpacks and finding normal behaviour, it appears it's only this pack that causes it.

**Expected behavior**
I would expect JEI to go back a single recipe with a single click of the button.  Instead, it skips all the way back to the beginning.  Never seen something like this before.

**Modpack version**
->2.3.2
**Java Version**17
->
**Modpack Launcher Used**
->Prism
**Ram Allocated**8Gb
->

**Additional context**
->

**Comment by ChosenArchitect** [comment]
I am doing nothing that would change this... I will say maybe mezz changed something in the latest updates. Also UPDATE THE MODPACK as that might help you get the bug fixes...
