### ISSUE TITLE
RF Tools Dimensions Block Absorber is bugged

### ISSUE THREAD

**Issue by Muisturo** [ChosenArchitect/Project-Architect-2#138]
**Describe the bug**
->Block Absorber should absorb Raw Uranium blocks (Mekanism)
so that you can make a dimlet out of it, but it simply just doesn't work, works fine with other blocks.

**To Reproduce**
1. Craft Block Absorber
2. Place it on top of Raw Uranium Block (Mekanism)
3. Watch it do nothing in frustration.

**Expected behavior**
->Should begin absorbing any raw uranium blocks placed underneath itself and start charging towards 100%.

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)
![2024-08-13_19 14 29](https://github.com/user-attachments/assets/6b1d92d8-3e37-441f-aa7d-51f827f47345)
![2024-08-13_19 13 37](https://github.com/user-attachments/assets/dc0838bc-e627-416d-ab73-ae7811c63993)
![2024-08-13_19 13 56](https://github.com/user-attachments/assets/c5192b5b-1987-4554-8f5c-b86668587d40)
![2024-08-13_19 14 16](https://github.com/user-attachments/assets/43f49af7-e807-407e-b2ea-714c0301e409)
Added an example to show it worked with Raw Gold but not with Raw Uranium as it should.
**Modpack version**
->3.2
**Java Version**
->Java 8 update 411 (build 1.8.0_411-b09)
**Modpack Launcher Used**
->Curseforge
**Ram Allocated**
->8192

**Additional context**
->

**Comment by ChosenArchitect** [comment]
Yep some mods are completely disabled this one included from things that can be replicated. If the absorber doesn't collect it it cannot be used

**Comment by Muisturo** [comment]
sooo, some mods dont work even if there is a dimlet for the material in the workbench?
![2024-08-13_20 11 00](https://github.com/user-attachments/assets/631a831c-188e-400f-ad14-09d7e20d4448)

**Comment by Muisturo** [comment]
just trying to understand what works and what doesn't. Thank you for the replies Chosen!

**Comment by shiftthedev** [comment]
this is an issue with RF Dims, where it displays disabled dimlets in workbench, like mekanism stuff.

**Comment by Muisturo** [comment]
i see ty for the help
