### ISSUE TITLE
Quark's slabs to log recipe is back

### ISSUE THREAD

**Issue by CrazyMusicBoy44** [ChosenArchitect/Project-Architect-2#139]
**Describe the bug**
->Quark's slabs to log bug is back

**To Reproduce**
1. put two oak, spruce, jungle, or cherry slabs in a crafting table
2. it outputs logs 

**Expected behavior**
->would expect it to craft planks

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)
![image](https://github.com/user-attachments/assets/c891e87f-756c-447f-9ff2-0d90261ce5eb)
**Modpack version**
->3.0
**Java Version**
->17
**Modpack Launcher Used**
->Curseforge
**Ram Allocated**
->whatever curseforge decided

**Additional context**
->

**Comment by shiftthedev** [comment]
update modpack to latest version

**Comment by CrazyMusicBoy44** [comment]
oh wait im stupid
