### ISSUE TITLE
[Bug? Feature?] Mob feature takes control from the player.

### ISSUE THREAD

**Issue by NaliAroni** [ChosenArchitect/Project-Architect-2#14]
**Is your feature request related to a problem? Please describe.**
-> An unknown mod adds effects to mobs (in my case Pillagers with Crossbows) that takes control away from the player, disabling their keyboard and inputting random commands like movement, open and close inventory, pause and un-pause game. During this de-buff the keyboard is unresponsive for in game actions. I confirmed it was Minecraft by Alt+tab 'ing to another window during the effect. This was an extremely scary situation that made it seem like I was under the attack of a hack / virus.

**Describe the solution you'd like**
->I would like to identify the mod that causes this and ask for an option to disable this effect. (I tried to identify the effect but I couldn't control my inventory) 

**Additional context**
->Encountered in Pillager outpost, probably attached to an arrow effect. Most likely applied by crossbow pillager. Debuff lasted 2-4 seconds after taking damage from the mob. Mouse control still worked, and I survived by killing the mob in question while unable to control my movement.

**Comment by shiftthedev** [comment]
Have you added any mods?
Did any effect icon displayed?
What launcher you're using?

**Comment by James103** [comment]
I am trying to narrow down any possible effects, to determine the responsible effect. Can you please try to paste in and run the following command next time you lose control over your player character?
```
data get entity @s ActiveEffects
```
EDIT: `enlightened_end:dazed` does not appear to cause the effect you're describing, according to [MEED](https://modrinth.com/mod/moderately-enough-effect-descriptions-(meed)-jeed-addon)'s descriptions.

**Comment by NaliAroni** [comment]
I have not added any mods. I'm using ATLauncher. 
If I encounter this again then I will try that command.

**Comment by NaliAroni** [comment]
dazed turns my screen sky blue for the duration. this also happens when using glider + Slime sling out of 1 deep water. No shaders enabled.
