### ISSUE TITLE
Please add Eccentric Tome mod

### ISSUE THREAD

**Issue by DFran49** [ChosenArchitect/Project-Architect-2#140]
**Is your feature request related to a problem? Please describe.**
-> I'm always frustrated when I have lots of mod books and I can't have them centralized.

**Describe the solution you'd like**
-> I think the solution is to add the "Eccentric Tome" mod, since it only adds the eccentric tome that can holds any mod guide book.

**Describe alternatives you've considered**
-> 

**Mod Sugestions**
-> Eccentric Tome ( https://www.curseforge.com/minecraft/mc-mods/eccentric-tome )

**Additional context**
->

**Comment by IRicTheCoder** [comment]
This was considered but it can cause issues of losing the books and such as mentioned on the mod's description, there is also a lot of options to store those books, so there doesn't seem to be that much need for this, for now it won't be added.

As of 4.0 you can use your AE2 or RS system, QIO, backpacks and even your ender cake inventory to store these books, making it easier for them to be stored in a single place of easy access.

Closing this as not planned, as we currently have no plans to add more mods to the pack.
