### ISSUE TITLE
pipez mod does not chunkload

### ISSUE THREAD

**Issue by DevilsGoonie** [ChosenArchitect/Project-Architect-2#144]
**Describe the bug**
-> pipez is my assumption as the problem (since the barrels continue to fill while offline). But when offline (no players on my server) the sophisticated storage will completely fill itself from my mob farm using mob grinding utils. I have three barrels from sophisticated storage, one to route out all the dims and non-EMC items to my refined storage, one to auto turn into EMC through an EMC link, and one as a buffer from the absorption hopper. After being offline for multiple hours i will come back to thousands of items on the ground and the server being overloaded by over 20kms and all barrels being completely full to the brim. Items are routed using the pipez mod with the netherite "ultimate" upgrade for speed. If i am online everything runs just fine. I am able to remove items from the barrels faster than they can receive. My area is chunkloaded using the map (not sure what mod that is). I also have an advanced item collector from item collectors as the absorption hopper is way too slow to keep up with a 5x5 of dreadful dirt being overclocked with redstone. The setup works perfectly as long as someone is logged in! Even if nowhere near the base for hours. Only if the server is empty does this issue persist.

**To Reproduce**
1. mob masher to absorption hopper
2. absorption hopper to barrel
3. barrel going two directions. One to another barrel as buffer and then to an EMC link. One going to an Import for refined storage
4. 

**Expected behavior**
-> I expected the items to not overfill while offline

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)
![2024-08-13_15 33 00](https://github.com/user-attachments/assets/5c272a8c-8510-445f-b0f9-16b89769cd41)
![2024-08-13_15 37 04](https://github.com/user-attachments/assets/54bcf0b5-d23e-4d19-8099-982ab835e745)
![2024-08-15_16 11 00](https://github.com/user-attachments/assets/12313c5a-e1dc-47e2-ae28-26359eac1da1)
![2024-08-15_16 11 08](https://github.com/user-attachments/assets/72a909c5-f440-4b24-8cb2-30b854a96428)
![2024-08-15_16 11 26](https://github.com/user-attachments/assets/7eb7dbfb-c9fd-4713-ad6e-db87225befbe)

**Modpack version**
->3.2
**Java Version**
-> Not sure which one it uses but Java 8 - 401 and the JDK 17.0.12
**Modpack Launcher Used**
->Curseforge
**Ram Allocated**
->10 gigs to the client. 10Gigs to the server

**Additional context**
-> If this setup is poorly designed and there is a workaround using a different setup i'm more than welcome to a solution

**Comment by shiftthedev** [comment]
try using other pipes, like the mekanism pipes.

**Comment by DevilsGoonie** [comment]
Haven't tested chunk loading but can confirm the Logistical Sorters from Mekanism are way too slow to keep up

**Comment by IRicTheCoder** [comment]
This does not seem to be related to `pipez` per say as I have used it and it respects loading from FTB Chunks, however, if you are on a server, and no one is online the chunk unloads unless you modify FTB Chunks config. Shouldn't be an issue in Single Player.

Some blocks still work even with the chunks unloaded due to predicative behavior, so when they load they execute their function X amount of time based on how long it was unloaded. Which is the case of the Item Collector you are using if I am not mistaken.

**Comment by danebra** [comment]
Go to saves\World\serverconfig and edit the `ftbchunks-world.snbt` file. Change `force_load_mode: "default"` to `"always"`

**Comment by IRicTheCoder** [comment]
No more feedback has been given on this, and a potential solution was provided. Will assume this has been resolved and closing it as such. If not feel free to reopen the issue.
