### ISSUE TITLE
Infinte emc issue

### ISSUE THREAD

**Issue by ThyRiverEXE** [ChosenArchitect/Project-Architect-2#145]
**Describe the bug**
->An infinite emc loop can be easily made soul sand (emc:49) and soul soil (emc:1)

**To Reproduce**
1. pull stack of soul soil from table, cost 64 emc 
2. put soul soil in mekanism crusher
3. get stack of sould sand, worth 3,136 emc
4. profit

**Expected behavior**
-> not to have an infinite loop

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)

**Modpack version**
->
**Java Version**
->
**Modpack Launcher Used**
->
**Ram Allocated**
->

**Additional context**
->

**Comment by Github-User4769** [comment]
That's just projecte for you.
Redwood saplings can be placed in a 3x3 formation (288 emc), bone mealed for (9 x n) (n = how many times you have to bone meal) to produce 468 logs that has an emc of 32 each.

**Comment by IRicTheCoder** [comment]
The pack does have a lot of situations where you can dupe EMC, part of its main progression are blocks designed mainly for that, so I would say that this is not a major issue, if it is an issue at all.

**Comment by ChimeraGaming** [comment]
A Better one is 
1. Igneous Extruder to basalt
2. Basalt to combiner

1. EMC link extracting debris to Crusher
2. Dirty N. Scrap to Enrichment Chamber 
3. N. Scrap to Metallurgic Infuser with Gold being fed with EMC link
4. Dust to Combiner
5. You wind up with a surplus of 15k EMC every few ticks :)

**Comment by se7enek** [comment]
> 7\. You wind up with a surplus of 15k EMC every few ticks :)

This is totally reverse if im aware.

requires 1 debris
1 debris yields 3 n.scrap
u need 4 n.scrap for 1 n.dust (so ure missing 1 n.scrap)
u need 2 n.dust to combine back into 1 debris

which basically means ure **losing** like 7k emc every few ticks.

**Comment by mikekaylor98** [comment]
Found a similar, less crazy one. 

1. Get compressed cobble
2. macerator/crusher to compressed gravel
3. uncraft compressed gravel to normal gravel, instant 4x EMC

Basically, compressed gravel is 1/4th of the EMC value that is should be. Gravel costs 4 EMC, compressed gravel x1 costs 1 EMC

**Comment by IRicTheCoder** [comment]
Some of those values are either auto mapped, or ended up just being left as they are for people to have early game solutions for EMC farming. As such, most of these will not me modified and it will remain as is.

Closing this as sorted, as some of these were deemed ok enough and left as intentional.
