### ISSUE TITLE
Chisel chipped integration blocks have no recipe 

### ISSUE THREAD

**Issue by JeanVictorL** [ChosenArchitect/Project-Architect-2#147]
**Describe the bug**
->factory block variations cannot be crafter since they don't have a recipe anymore.

**Expected behavior**
->for factory blocks like the rusty plate or slightly rusty plate to be craftable using the tinkering table

**Modpack version**
->3.3
**Java Version**
->irrelevant
**Modpack Launcher Used**
->curseforge
**Ram Allocated**
->irrelevant

**Additional context**
->I crafted this blocks before, my base has plenty of them, the recipe was removed in a later update.

**Comment by shiftthedev** [comment]
![javaw_fwbNsqkhoa](https://github.com/user-attachments/assets/dbd53282-892a-48a1-a8e4-16f97be71e94)
for me they show. i'm on version 3.3

**Comment by JeanVictorL** [comment]
somehow, restarting the game worked --'
