### ISSUE TITLE
sophisticated backpacks reset

### ISSUE THREAD

**Issue by T-Fold** [ChosenArchitect/Project-Architect-2#148]
**Describe the bug**
->Inventory/upgrades of sophisticated backpack "reset" to the state it was in ~30min ago.

**To Reproduce**
I'm unsure, I just found out you could put multiple Stack Upgrades into the backpack then went mining in a dimlet dimension after returning and depositing the loot I went to the End were a bit later my inventory filled up with stuff that should have gone to the backpack when I opened my backpack it was back to how it was before I went mining both Inventory and upgrades.

**Expected behavior**
->For the backpack and its contents to stay the way its configured

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)
unfortunately I didn't take a before and after

**Modpack version**
-> 3.1
**Java Version**
->V8 U421
**Modpack Launcher Used**
->CurseForge
**Ram Allocated**
->8.5

**Additional context**
->it wasn't too much but at the time it had at least 1M items ~15B EMC inside

**Comment by IRicTheCoder** [comment]
This can most likely be an issue with duplicated bags or similar where they share the same internal ID (or UUID). If it happens again, please comment back on this post. As it is, it is a bug from the backpack mod itself, and we can't do anything about it.

**Comment by IRicTheCoder** [comment]
There was no more feedback on this for 2 weeks so I will assume the issue is resolved. If it happens again feel free to reopen the issue, thank you!
