### ISSUE TITLE
teleport in the end bug

### ISSUE THREAD

**Issue by Dabduck** [ChosenArchitect/Project-Architect-2#15]
**Describe the bug**
->From the outer islands i went into an end gateway portal and it spawned me in the main island as it should but it spawned me in the air and i fell into the void and died

**To Reproduce**
1. be in the outer islands
2. find end gateway
3. go in it

**Expected behavior**
->i expected it to spawn me on the platform

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)

![image_2024-07-27_133510224](https://github.com/user-attachments/assets/d39fe6c6-9df7-4581-b601-3e977a12b1ff)

**Modpack version**
->2.1 (release)
**Java Version**
->1.20.1
**Modpack Launcher Used**
->CurseForge
**Ram Allocated**
->10048

**Additional context**
->

**Comment by ChosenArchitect** [comment]
hum... that is a issue
Im not sure a good way to fix that or disable the gateways
ill look deeper into that

**Comment by shiftthedev** [comment]
how did you enter the gateway?
Is there a gateway where you died?

**Comment by Dabduck** [comment]
> how did you enter the gateway? Is there a gateway where you died?

i entered a gateway from the outer islands

**Comment by shiftthedev** [comment]
sorry what I meant was, 
did you use a pearl, fly in with an elytra, shrink yourself?

Also, have the dragon been killed or was this your first time in the end?

**Comment by Dabduck** [comment]
> sorry what I meant was, did you use a pearl, fly in with an elytra, shrink yourself?
> 
> Also, have the dragon been killed or was this your first time in the end?

i think i used a pearl and the dragon had no been killed, it was my first time in the end

**Comment by shiftthedev** [comment]
i've tested this multiple times and, unfortunately, i've been unable to replicate it.
Either you had a lag spike, or minecraft placed you on a non-solid block and you fell through it.

**Comment by Dabduck** [comment]
> i've tested this multiple times and, unfortunately, i've been unable to replicate it. Either you had a lag spike, or minecraft placed you on a non-solid block and you fell through it.

its fine, ill try to replicate it as well but if I cant succeed that it was probably a lag spike or something like that

**Comment by Itzbionicz** [comment]
I was originally thinking it happened because of you not killing the dragon yet which means there was no gateway spawned on the main island but don't you spawn on the obsidian platform? But now that I think about it, that could be the reason because when I made a void trader, it spawned me next to the gateway, so it could have been because you didn't kill the dragon yet.

**Comment by shiftthedev** [comment]
because of End's Phantasm when you go to the end you are placed in the other islands. finding a gateway to go back to center is viable and in my testing using the gateway always spanwed me in the edge of the main island in a end stone block.

**Comment by ChosenArchitect** [comment]
This is a feature and will be closing the ticket :D
