### ISSUE TITLE
Deepslate Draconium ore 

### ISSUE THREAD

**Issue by Pyroshere** [ChosenArchitect/Project-Architect-2#151]
**Describe the bug**
->The deepslate version of the Draconium ore is not included in any of the Draconium ore recipe. It can only be breaken by a pickaxe to get Draconium dust. It can't even be smelted.

**To Reproduce**
1. get a deepslate Draconium ore 
2. use it with a furnace or a IntegratedDynamics Squeezer (two thing that the three other type of Draconium ore can be use with)
3. you can also observe JEI recipe to see that the deepslate Draconium ore is not part of the Draconium ore tag when observing the other version recipe. 

**Expected behavior**
-> deepslate Draconium ore should be usable in the same recipe as the normal, nether and end version. 

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)
![2024-08-18_22 16 31](https://github.com/user-attachments/assets/0264c4f7-f24a-44c3-98a6-854a9d6c854a)
![2024-08-18_22 16 50](https://github.com/user-attachments/assets/4e8f615a-6bb1-48c4-a20d-b03c9d7b0844)
![2024-08-18_22 16 57](https://github.com/user-attachments/assets/0e921a47-f0b6-4fc3-9d6b-2386d4ee211a)
![2024-08-18_22 21 38](https://github.com/user-attachments/assets/55ef8ba8-3159-4d13-884b-c72e7e27bbfd)

**Modpack version**
->3.3
**Java Version**
->
**Modpack Launcher Used**
->CurseForge
**Ram Allocated**
->9024mb

**Additional context**
->I find out that the deepslate Draconium ore is part of the Draconic Evolution tag but not the forge:ores/draconium tag. that might be the problem.

**Comment by IRicTheCoder** [comment]
This has been fixed in update 3.4+ it should now work like the other variants.
