### ISSUE TITLE
2 crashes while game is running fine, seems to be while looking at recipes

### ISSUE THREAD

**Issue by Captainmoriarty** [ChosenArchitect/Project-Architect-2#153]
**Describe the bug**
->I think both times i was in a crafting table looking at jei

**To Reproduce**
1. 
2. 
3. 
4. 

**Expected behavior**
->

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)

**Modpack version**
->3.3
**Java Version**
->unsure/current available
**Modpack Launcher Used**
->Forge 47.3
**Ram Allocated**
->9-10gb

**Additional context**
->
Seems to be a garbage collection thing maybe or some other thing thats just using up memory, also have edge open and it crashes with minecraft.
Crash Report

[hs_err_pid15208.log](https://github.com/user-attachments/files/16664615/hs_err_pid15208.log)

**Comment by Captainmoriarty** [comment]
Seems fine now, not sure why. Haven't changed anything

**Comment by IRicTheCoder** [comment]
This might be related to the issues with some Create Recipes, this was fixed in 3.4. Will close the issue as no more information was provided and it does seem related. If the problem still remains feel free to reopen this issue.
