### ISSUE TITLE
Bunch of Fixes + Extras

### ISSUE THREAD

**Issue by IRicTheCoder** [ChosenArchitect/Project-Architect-2#154]
**Is your feature request related to a problem? Please describe.**
-> This is not a request per say nor a bug report, I have been fixing some of the bugs I come across and also fixed some of the issues here on the tracker. Also made a few additions/changes and I would like to share them.

**Describe the solution you'd like**
-> It would be cool for at least the bug fixes to be introduced, the additional things would also be cool but not required as I made them mainly for myself.

**Describe alternatives you've considered**
-> Besides waiting for mods to update and potentially fixing their bugs, this is the best alternative to it for now I think.

**Mod Suggestions**
-> In order to help out with fixes I would suggest two mods [AttributeFix](https://www.curseforge.com/minecraft/mc-mods/attributefix) which should fix some issues with monster health, mainly the RFToolsDim Blobs which should have way more health based on the configs.

And [ToolStats](https://www.curseforge.com/minecraft/mc-mods/tool-stats) which will help identify more stats on tools including harvest level for when some blocks have bugged drops, as it might be related. It is also a nice addition for some people.

**Additional context**
-> I will break down what my fixes + additions are and what they do/fix

**[Fixes for Known Issues]**
- ~~#125~~ - This is actually a problem that can also occur with datapacks in vanilla, when dropping heads that only require a skull owner it tends to sometimes modify the `SkullOwner` property and add weird `Signature` field values, which aren't needed. **HOWEVER** scratch that fix as not all drops from head are actually in the drop list, so there is no good way to fix this without either a mod, or the mod itself fixing it.
- #129 - Not only bosses are made invincible, this is sometimes related to regen and sometimes to immunity. My fix, or attempt at it, checks if the mob will be killed with the amount of damage, or if the health is already 0 or less, if it is, sets it to 1 and runs the kill function with the given damage source (works as it normally would and should at least prevent the issue, but needs more testing).
- #80 - This is a Create issue and has been fixed but a version hasn't been released with it, as far as I am aware, so I made a fix for it, it simply remaps the ID of some recipes to append "_manual_only" which prevents Create to add them to the 'Automated Shaped Crafting'.
- #103 - This happened to me a lot of times it was annoying, so I made a sort of fix that so far has been working. If the item has the AC enchantment and is active, when it breaks a block, the block is force learned by running the ProjectE command. It has worked on all my testings.
- #104 - This isn't directly a fix, but at some level of automation this can become laggy, so instead of EMC values I added alternative recipes for Redstone Crystal and Sky Steel Ingots (the ones most likely to become laggy) to the Dissulotion Chamber of IF, it is the block that better replicates In-World Transformation, however, for balancing, the recipes are slightly more expensive and use the fluid up.
- #123 - The Mekanism tools sometimes also break their modules, and so do any items with complex NBTs, my fix delays the Modular Router breaking by one tick and drops the buffered item manually, then removes it from the MR's inventory and breaks the MR. So far it seems to work for all items.
- #151 - This is a missing tag, which I also fixed, however I never found deepslate draconium ore in the overworld ^^'
- #137 - There is a mention on the issue about the biggest problem being with unbreakable trials content, I made the trials content breakable, and made it droppable if silk touch is used (can be disabled easily), but only if the Vault or Spawner already ran their course anything before that will cancel breaking.

**[Other Fixes]**
- Fixed a bunch of missing language things, using KubeJS lang event.
- Added some EMC value to some Region Unexplored blocks that seemed to have it missing, they do not influence anything and are mainly variation of others that have it. Added this using a mapper script I built so it doesn't override any configurations and instead adds them at Server load, then the new config file can be used. This uses the ProjectE command so after populating the config the script can be removed (server_scripts\pa2_extras\added_emc.js)
- Added all the inventories I could find to Inventory Tweaks, fixed positioning for some of them, and removed them from either screens that made no sense, or ones that the sorting bugs them. (Didn't go through Create Blocks yet)
- Found out that RFTools had config missing, on the serverconfig side to load all extra configs from the `config\rftoolsdim` folder so I added them making the files valid and most likely preventing the unwanted blocks from spawning. **Check the configs in the `config\rftoolsdim` to see if they are fine**, and fiels can be added/removeds from on `defaultconfigs\rftoolsdim-server.toml`
- Fixed drops for some items that should drop such as `Redstone Beacon` and some crystal lamps, etc.
- Removed unneeded/broken recipes such as Compact Sun (has no use without the ProjectExpansion Collectors), and Chicken Spawn Egg from Reliquary that is added when mobs don't have spawn eggs.
- Adjusted the Emotes button from Quark so it doesnt stay on top of the NoChatReports buttons, and disabled the view that shows the total stacks in the inventory, as inventory tweaks already does this, so no point in having two, also inventory tweaks one is always present and doesn't "flash" everything a block is placed.
- Some blocks such as Dark Pedestal become unbreakable with tools not made of Dark/Red Matter, it is an issue with ProjectE, and some other mods that hardcode this requirement. As such made a script that lets you break those blocks by Sneaking and hitting them. (It is configurable and more blocks can be added)

**[Additions]**
- Added recipes for `Reinforced Deepslate` and `Infinity Upgrade` from Pipez, for the deepslate I used bones from Deeper and Darker giving more uses to the dimension. For the Infinity Upgrade it made sense for me to be present the recipe is actually pretty hard too, so it should be balanced.
- Also added a recipe for `Max Storage Upgrade` which is the same as the Infinity one but uses a Netherite Upgrade instead.
- Added drops to trials blocks like mentioned above, they can be broken eitherway but they do drop if silk touch is used and this can be disabled, as they do look nice as decorative blocks. Trial blocks can be made to drop/break even when active.
- As Reinforced Deepslate has a recipe also made it mineable and droppable with silk touch.
- Added Dyeable Fire because it is a cosmetic thing that is almost always overlooked in mods. It does not burn on touch, does not make sound or particles, it is purely cosmetic and infinite. Can be made by using a dye on fire or soul fire, does not drop the dye back so the dye is "burned by the fire", they can be recolored by just reapplying another dye. All dye colors are supported. White, gray and black are slightly different than the rest due to highlights and recolors. (to remove delete the `server_scripts\dyeable_fire` folder and the `startup_scripts\pa2_extras` folder).
- Adjusted the spawning of Sinker from Outer End because in some scenarios so many spawn that you get surrounded and it makes it impossible to fly and/or see good enough to kill them. To balance this I made a script that reduces their spawn rate, other mobs can be added to.
- Added tooltips to some items such as Dimensional Tabs from RFToolsDim to make people aware of how to delete dimensions, or retrieve ones they forgot to delete, and added some informative tooltips for items that seem to have potential bugs.

**[Changes]**
- Altered the Bundle Curios Slot icon to a bundle like one, it gets a bit annoying that it feels that we have a general curio one free when we don't.
- Altered the Inventory Sort icon to something that aligns better with the GUI. It is still visible in dark mode, and it doesn't look weird in light mode.

**[Conclusion]**
All my files have comments and explanations, everything should be possible to turn off, or slightly configure. All are made in independent files, so it doesn't change any of the original files, making it mainly drag and drop to install.

My files also allow for more things to be added, such as more '_manual_only' recipes, spawn rate reductions, etc.

I have been researching KubeJS and other things as I built some tools for Minecraft, and some of this came from that, everything or nothing can be added but I wanted to share it so if any is interesting then just go ahead and add it.

I will also keep testing things to find how to fix some other issues as the ChunkLoading bugs with some mods/blocks which is weird.

**DOWNLOAD:** [PA2 - Fixes & Extras.zip](https://github.com/user-attachments/files/16670385/PA2.-.Fixes.Extras.zip)

**Comment by IRicTheCoder** [comment]
Made a small change, as I forgot to add something to the list of Additions and had the wrong script in the zip, fixed now.

**Comment by IRicTheCoder** [comment]
Made a few more updates, and removed the Head fix as it only worked a few times when the heads actually appear on the drop list, most don't unfortunately.

**Comment by mcdodge34** [comment]
Wow, thanks for your hard work, always appreciate someone giving some free time to solve issues with a modpack, is there any ways to send you a little gift like kofi link or something like that

**Comment by IRicTheCoder** [comment]
> Wow, thanks for your hard work, always appreciate someone giving some free time to solve issues with a modpack, is there any ways to send you a little gift like kofi link or something like that

I appreciate the comment, right now I don't think I have anything like that setup, but I do appreciate the intention.

**Comment by Zahaaan** [comment]
bug: rftools block absorber won't absorb matter blocks

**Comment by IRicTheCoder** [comment]
> bug: rftools block absorber won't absorb matter blocks

This has been explained [here](https://github.com/ChosenArchitect/Project-Architect-2/issues/160#issuecomment-2301141521) please look for the current open issues before posting one, also post the issue as a new issue and not a comment, otherwise makes it hard to keep track off. Thank you!

**Comment by IRicTheCoder** [comment]
Been added into the updates, so no longer required to be open, will close to clean the issue list a bit.
