### ISSUE TITLE
Enlightend ores do not drop when mined by tools which work like pickaxes but aren't strictly pickaxes.

### ISSUE THREAD

**Issue by James103** [ChosenArchitect/Project-Architect-2#157]
**Describe the bug**
When a block from the Enlightend mod is broken using a tool which acts like a pickaxe but does not have the word "Pickaxe" in its name or item ID, the block does not drop.
This may be caused by the mod using a different method which allows pickaxe items but rejects all other tool items, instead of checking if the item can mine blocks like a pickaxe the same way vanilla and several other mods do it.

Furthermore, although Malachite appears to require a wooden pickaxe, it still does not drop anything unless mined with a higher tier pickaxe such as a diamond or netherite pickaxe.

**To Reproduce**
Get any item which acts like a pickaxe but does not have the word "Pickaxe" in its default name or item ID, then try to mine any item from the Enlightend mod such as Palerock or Malachite Ore. The block will mine just as fast, but will not drop. Examples include but are not limited to:
* Red Morningstar from ProjectE
* Fluxbore from Thermal Innovation
* Paxel from Mekanism: Tools
* Any shovel reforged through Apotheosis to have "This tool has netherite effectiveness against all blocks" as one of its affixes

**Expected behavior**
Blocks from the Enlightend mod should drop if mined using items which act like pickaxes but don't have the word "Pickaxe" in its name or item ID.

**Modpack version**
3.3
**Java Version**
17.0.3, using 64 (amd64) architecture, from Eclipse Adoptium.
**Modpack Launcher Used**
Prism Launcher
**Ram Allocated**
6144 MB

**Comment by IRicTheCoder** [comment]
The tools that can mine a block are based on block tags, not checks in code. So most likely these blocks are missing tags. As for the Apotheosis affixes that could be another issue. The icon on top that shows the type of tool is always a wooden item, doesn't matter the tier required to mine.

All blocks are doing this? Or just specific ones?

**Comment by IRicTheCoder** [comment]
Made a few tests on the 3 ores, Staff of Power seems to work, paxels don't which is weird, nor Morningstar, unless silk touched which seem to work. Didn't test with the rest

Also check if you don't have Alchemical Collection in your items, if you do check if it is disabled.

Notice that the Staff of Power puts the items straight in your inventory if you are close enough, so you might have missed it.

Also Irradium always works with all for some reason

**Comment by James103** [comment]
None of my tools have the Alchemical Collection enchantment, and I just tested again mining Palerock with my magnets sending block drops to the inventory but not to my ME system.
* Any Mekanism Paxel (tested: Diamond) - voided block drops
* Thermal Innovation's Fluxbore - voided block drops
* ProjectE's Red Matter Pickaxe - block dropped itself
* Draconic Evolution's Chaotic Pickaxe - block dropped itself
* Draconic Evolution's Staff of Power - block dropped itself, possibly because the item passes Enlightend's strict pickaxe check
* Draconic Evolution's Chaotic Shovel - reforged to have "This tool has netherite effectiveness against all blocks" as an affix meaning should also mine like a pickaxe - voided block drops
* Unenchanted Wooden Pickaxe (mining Palerock) - block dropped itself
* Unenchanted Wooden Pickaxe (mining Malachite Ore) - voided block drops despite Jade saying the tool was correct

`/kubejs hand` output for Enlightend's Palerock:
```
Item in hand:
- '61x enlightened_end:palerock'
- '#minecraft:stone_crafting_materials'
- '#minecraft:stone_tool_materials'
- '#emc:remove'
- '#forge:dragon_immune'
- '@enlightened_end'
Held block:
- enlightened_end:palerock
- '#projecte:mineable/hammer'
- '#enlightened_end:end_biome_replace_valid'
- '#projecte:mineable/morning_star'
- '#minecraft:mineable/pickaxe'
- '#minecraft:mineable/mattock'
- '#forge:end_ore_replaceables'
- '#forge:mineable/paxel'
```

**Comment by shiftthedev** [comment]
this is an issue on how that mod checks for the correct tool

**Comment by IRicTheCoder** [comment]
A fix for this was added in Version 4.0, from the tests it seems to work, however, more tests might be required. Closing this as solved for now, reopen if the issue continues, thanks!

**Comment by aaKugelblitz** [comment]
im running enlightend 5.0.4, and the tinkers construct pickaxes with and without their fortune/silk touch modifiers do not drop anything from the enlightend blocks, ores or otherwise.

**Comment by IRicTheCoder** [comment]
The pack does not have tinkers construct in it, so I believe you added it, unfortunately our fix applies to items in the pack, or items that work as normal tools, which the TC ones do not, as such this problem remains, nothing we can do about it.

**Comment by aaKugelblitz** [comment]
apologies! i thought i landed on the enlightend mod github in my haste. feel free to clear up these comments, sorry!
