### ISSUE TITLE
Temporal Pouch accelerates unwanted blocks (Silt Grass Block in my case)

### ISSUE THREAD

**Issue by camm344** [ChosenArchitect/Project-Architect-2#159]
**Describe the bug**
-> When right clicking 

**To Reproduce**
1. Right click the block with Temporal Pouch

**Expected behavior**
-> I expected the Temporal Pouch **not** to accelerate the Silt Grass Block.

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)
![Screenshot 2024-08-20 154421](https://github.com/user-attachments/assets/160d29bc-4b35-42ee-af1d-a5bd3d95a77c)
**Modpack version**
->2.8 (supporter server)
**Java Version**
->17.0.10
**Modpack Launcher Used**
->Prism
**Ram Allocated**
->12gb

**Additional context**
Not sure of any other blocks that are affected by this issue

**Comment by IRicTheCoder** [comment]
Can you elaborate a bit more? As in what blocks should be valid and what shouldn't? I haven't used the pouch yet so I need some idea. But for the looks of it a quick fix should be possible

**Comment by IRicTheCoder** [comment]
So this seems to be working as intended according to the normal functionality of the mod/item, it seems the mod itself does not check for right/wrong block, so I am assuming it is intended.

**Comment by camm344** [comment]
> So this seems to be working as intended according to the normal functionality of the mod/item, it seems the mod itself does not check for right/wrong block, so I am assuming it is intended.


On second thought, I'm sure it is intended as Grass Blocks could grow something. My issue with that though is I could misclick a block, as that kinda bothers me. Thanks.
