### ISSUE TITLE
Crushed Raw Osmium has EMC

### ISSUE THREAD

**Issue by futureflash01** [ChosenArchitect/Project-Architect-2#16]
**Describe the bug**
->None of the crushed raw ores in the 'Create' mod have an EMC value, except for **crushed raw osmium**. It has an EMC value of 1024. Not sure if this was intentional, but it's odd seeing it as the only ore that's transmutable.

**To Reproduce**
1. Open JEI
2. Search "crushed"
3. All the crushed raw ores from the "Create" mod will appear
4. Crushed raw osmium is the only ore with an EMC value, as all other ores require manual processing

**Expected behavior**
->When hovering over the crushed raw osmium in JEI or any inventory GUI, it should just show a description of the ore and which mod it came from, but it should not show an EMC value

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)
![image](https://github.com/user-attachments/assets/02d2b6e8-6c0b-4e68-87cf-c811b82210bd)

**Modpack version**
->Latest (2.4)
**Java Version**
->1.17 JDK
**Modpack Launcher Used**
->CurseForge
**Ram Allocated**
->8192MB (8GB)

**Additional context**
->N/A

**Comment by MalaChaiLatte** [comment]
'create:crushed_raw_osmium',
appears to be missing from Project Architect 2-2.4/overrides/kubejs/server_scripts/emcremove.js , where the other crushed ores are located
adding it to 'emc:create' resolves this, unless this was intentional @ChosenArchitect 
:)

**Comment by shiftthedev** [comment]
just an oversight. will be fixed.
