### ISSUE TITLE
Chests from Sophisticated Storage get stuck in AE2 system

### ISSUE THREAD

**Issue by Rukka2** [ChosenArchitect/Project-Architect-2#161]
**Describe the bug**
->Chests from AE2 can enter the AE2 system via crafting terminal/normal input methods, but can not be retrieved manually and must be piped out/taken out of the crafting window.

**To Reproduce**
1. place any (I have only tried oak chests thus far) chest tier from Sophisticated Storage mod into AE2 System
2. Left Click any tiered oak chest from Sophisticated Storage mod within AE2 system

**Expected behavior**
->When you left-click the item from the terminal, I expect to be able to move the item to my own inventory manually

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)
![2024-08-21_08 19 01](https://github.com/user-attachments/assets/956c8077-0c11-4fcc-86b1-2a6a78119fad)
![2024-08-21_08 19 01_2](https://github.com/user-attachments/assets/a428ef13-8c2e-4414-b75d-5b524e0ea560)

**Modpack version**
->3.5 - (Release)
**Java Version**
->Java 22 - Latest version
**Modpack Launcher Used**
->CurseForge
**Ram Allocated**
->10gb

**Additional context**
->This only started happening recently, but the item has begun flickering within the crafting terminal once I left-click. Previously, it just did nothing.

**Comment by Rukka2** [comment]
It was kind of difficult to show what is going on, but you can see the chest isn't there in the top screenshot and flickers in the lower screenshot. It happens fairly quickly, but I just managed to catch it.

Notice the chest is still not being moved when I left-click.

**Comment by IRicTheCoder** [comment]
Does something appear on the log, like an error or something of sorts? This is a weird problem, and not sure if it is something we can fix, might be an issue with one of the mods themselves.

**Comment by Rukka2** [comment]
I'm not really sure how to tell if something appears on the log, but I'll post one in a moment. Just opening up the client now to generate a new log.

**Comment by Rukka2** [comment]
![2024-08-23_07 22 45](https://github.com/user-attachments/assets/8108a4ce-abe6-4162-97e2-23d83e596cf7)
To show that shift-left clicking also has a strange effect
Though when I was left-clicking without shift, it wasn't flickering anymore... strange indeed.

Latest Log here:
[latest.log](https://github.com/user-attachments/files/16730048/latest.log)

**Comment by IRicTheCoder** [comment]
This is indeed intriguing, as there is a ETF error appearing on the log. Do me this favor, disable the mods ETF and EMF (add .disabled to the mod file or disable in CurseForge) and test doing the same thing again.

**Comment by Rukka2** [comment]
Disabled ETF, EMF was already disabled.
Same thing happens
[latest.log](https://github.com/user-attachments/files/16736798/latest.log)
![2024-08-24_06 28 41](https://github.com/user-attachments/assets/ff6b55c1-9021-4433-9b3c-a2b4bc46c6f0)
![2024-08-24_06 28 46](https://github.com/user-attachments/assets/c58c5cb1-4128-4ce3-9e23-e85f72870050)

**Comment by IRicTheCoder** [comment]
This seems to now be solved in 3.6, suggest updating the pack and see if the issue still remains.

**Comment by IRicTheCoder** [comment]
Wasn't able to replicate this in version 4.0 (or 3.6 before it), the issue might have been solved with some of the updates of the mods involved. Closing as solved, if the issue reappears feel free to reopen this issue.
