### ISSUE TITLE
No Soliciting sign-llamas

### ISSUE THREAD

**Issue by DropTheBudSir** [ChosenArchitect/Project-Architect-2#163]
**Describe the bug**
->I have a no soliciting sign placed and it prevents the wandering trader from spawning but his llamas still spawn

**To Reproduce**
1. Place down a no soliciting sign
2. Wait for spawn

**Expected behavior**
->llama's still spawn but the wandering trader doesn't

**Modpack version**
->Observed in 3.4 and 3.5
**Java Version**
->8.411
**Modpack Launcher Used**
->Curse Forge
**Ram Allocated**
->20GB

**Comment by IRicTheCoder** [comment]
The sign is a bit messy and it does that, you can use the Non Soliciting Banner from Utilitarian and it should work for the llamas too.

**Comment by IRicTheCoder** [comment]
Didn't get feedback on this, but the solution has been provided, closing the issue as resolved.

**Comment by DropTheBudSir** [comment]
Sorry I didn't see this. I'm just glad there's something to get rid of them
because they spawn really frequently for some reason.

Thanks,

Sam
