### ISSUE TITLE
the Watch of Flowing Time

### ISSUE THREAD

**Issue by Demidjack13** [ChosenArchitect/Project-Architect-2#166]
**Describe the bug**
-> watch of flowing time was removed and its so usefull for EMC and generally alot of things. why was it removed?

**To Reproduce**
1. 
2. 
3. 
4. 

**Expected behavior**
-> watch of flowing time exists

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)

**Modpack version**
->3.5
**Java Version**
->17
**Modpack Launcher Used**
->Prism
**Ram Allocated**
->6 gb

**Additional context**
->

**Comment by IRicTheCoder** [comment]
This was most likely because it broke some of the progression and intention of the modpack. In any case you have the temporal pouch as a potential alternative, and the blocks from Industrial Foregoing: Souls.

**Comment by IRicTheCoder** [comment]
This has been addressed multiple times by now, the Watch of Flowing Time was removed due to multiple things getting broken with the pack. Other means are available to achieve similar results as referenced below, closing this as won't fix/not planned.
