### ISSUE TITLE
Saving World Bug

### ISSUE THREAD

**Issue by hellokingpro109** [ChosenArchitect/Project-Architect-2#167]
**Describe the bug**
-> whenever I log in to the game and to my solo world it works completely fine but the moment I exit the game  everything goes well except that my game get stuck in the "saving the world" screen forever. This started to happen when i changed the game version to 3.4 and 3.5. The only way to for me to even exit the game is to kill the instance will I don't think will keep my progress after the auto save had happened.

**To Reproduce**
1. go to curse forge and start the modpack.
2. wait until the game has finished loading and go to a survival solo world.
3.  then wait or play for while and exit the game with "esc". Then the game will  be stuck to the "saving the world" screen.
4. the only to exit is to kill the instance from curseforge or tab manager and the task.

**Expected behavior**
-> The game and everything will load but the moment you exit the screen will be stuck to the " saving world".

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)
![Screenshot (3)](https://github.com/user-attachments/assets/2471ce72-6540-4535-95e8-37a30178e990)

**Modpack version**
->3.5

**Java Version**
->Whatever the modpack uses.

**Modpack Launcher Used**
-> Cursedforge

**Ram Allocated**
->8gb also tried with allocating 9gb.

**Additional context**
->Only started to happen when I changed the modpack version

**Comment by IRicTheCoder** [comment]
Can you provide your `lastest.log` from the log folder? It is most likely an error that should be appearing there, so if you could provide the log we can see if it is possible to figure out the issue.

**Comment by pennycan** [comment]
Checking my latest.log says it's a problem with a powah cable for me.

**Comment by hellokingpro109** [comment]
very sorry that I couldn't respond, I was supposed to send it the when you asked but I was busy all week, I could do it now

**Comment by hellokingpro109** [comment]
I got a few logs but the most recent would be this 
[2024-08-22-3.log.gz](https://github.com/user-attachments/files/16809060/2024-08-22-3.log.gz)

**Comment by hellokingpro109** [comment]
[latest.log](https://github.com/user-attachments/files/16809185/latest.log)
This is the newest one I just loaded the world and exit, still stuck in saving the world

**Comment by hellokingpro109** [comment]
I also to let you know i waited for long while in the screen but it still bugged so killed the instance

**Comment by hellokingpro109** [comment]
just create another world
