### ISSUE TITLE
Block Absorber won't take compressed and matter blocks 

### ISSUE THREAD

**Issue by aws1122339** [ChosenArchitect/Project-Architect-2#168]
**Describe the bug**
->The block absorber is 100% complete but not set and doesn't consume the blocks. Tried both diamond x2-x4, cobblestone x4 and, red matter blocks

**To Reproduce**
1. place 256 blocks of compressed diamond
2. place block absorber on top
3. doesn't consume blocks like it should
4. mine absorber not set 100%
5. Can't be used to craft dimlet

**Expected behavior**
->Should consume 256 of the block so it can be used to make dimlet 

![2024-08-23_03 10 15](https://github.com/user-attachments/assets/7964b9fb-525d-43fc-8bae-ef1edc511d3d)
![2024-08-23_03 10 05](https://github.com/user-attachments/assets/6a8a410d-7467-4805-96b0-eb89d4c285f8)

**Modpack version**
->3.5
**Java Version**
-1.20.1
**Modpack Launcher Used**
->curseforge
**Ram Allocated**
->server 16gb client 64gb+

**Comment by shiftthedev** [comment]
If the Block Absorber don't consume a block, most likely it's because that dimension type is disabled in the configs.
Diamond is one of the disabled dimlets.

And yes, it will still show in the workbench do to a bug with RFTools Dimensions.

**Comment by aws1122339** [comment]
Thanks i didn't know it would show even if disabled.

**Comment by ChosenArchitect** [comment]
I wish it didn't... Couldn't find any way to disable it from showing up in the dimlet maker
