### ISSUE TITLE
crab for the pig plushie

### ISSUE THREAD

**Issue by GuiguiSlide** [ChosenArchitect/Project-Architect-2#169]
**Describe the bug**
->crabs from quark dont spawn but we need them for the quest for the pig

**To Reproduce**
1. 
2. 
3. 
4. 
![2024-08-23_13 26 51](https://github.com/user-attachments/assets/7deb253e-a8c7-494f-9148-c8f9586aad66)
![2024-08-23_13 26 45](https://github.com/user-attachments/assets/189588f9-0632-4256-b734-98c1d2848b73)

**Expected behavior**
->i espected them to spawn in the ocean or the beach

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)

**Modpack version**
->2-3.5
**Java Version**
->forge-47.3.0
**Modpack Launcher Used**
->curseforge
**Ram Allocated**
->8000

**Additional context**
->

**Comment by ChosenArchitect** [comment]
They 100% spawn. If you want to speed up the spawn make a golden eggs and place it on some dirt on a beach biome

**Comment by ryennce** [comment]
You are probably playing on a server with reduced mob spawn. Place some delightful dirt on the beach biome, they should spawn.

**Comment by GuiguiSlide** [comment]
thanks for the tip but i am on no server

**Comment by GuiguiSlide** [comment]
it worked thanks

Le ven. 23 août 2024 à 20:10, guigui_slide ***@***.***> a
écrit :

> thanks for the tip but i am on no server
>

**Comment by IRicTheCoder** [comment]
Just for context, some quark mobs have trouble spawning, for different reasons, but also because of the different biomes available. Mob caps also play a role. Regardless, you still have the ability to make them spawn faster with the delightful dirt. Will close this issue as solved.
