### ISSUE TITLE
Create Utilities has failed to load properly

### ISSUE THREAD

**Issue by mporter012** [ChosenArchitect/Project-Architect-2#17]
I just downloaded the latest version just now and this is the error that popped up on start. I can't play it without removing the mod
![image](https://github.com/user-attachments/assets/1742ded5-0ccc-4e37-8d6a-bff96d130aee)

**Comment by mporter012** [comment]
the version of the modpack is v.2.4

**Comment by ChosenArchitect** [comment]
this I feel is a launcher issue. Did you use curseforge?

**Comment by mporter012** [comment]
Yes, I tried playing it on curseforge. It works fine though if I run the
previous version

**Comment by MalaChaiLatte** [comment]
Could I get some information about your system/hardware?, are you running windows with an x86 chip? @Squidkiller01

**Comment by shiftthedev** [comment]
this happen to other people and usually just re-launching the pack solved it.
also a crash-report could help pinpoint the issue.
if you want to share it please use https://mclo.gs
