### ISSUE TITLE
Add a way for automation for ChiselChippedIntegratin Blocks

### ISSUE THREAD

**Issue by Erwin2Punkt0** [ChosenArchitect/Project-Architect-2#171]
The Base Blocks have EMC, but all variants need to be crafted by hand, since you may need a lot of those, it is really annoing to craft them by hand
Add a Stonecutter recipe just like for stuff like ironbars, so that it can at least be automated with create saws
Or, I dont know how hard that would be, add a block, similar to the powered framing saw from FarmedBlocks

**Comment by IRicTheCoder** [comment]
Most Chisel and Chipped variants should already be available in the Stonecutter, so most blocks should already work that way, what blocks are you specifically talking about?

**Comment by Erwin2Punkt0** [comment]
At least for me (yes I am on the newest version of the modpack) not a single block from "Chisel Chipped Integration" has a stonecutter recipe, just the chipped recipes and crafting recipes for the base blocks

**Comment by IRicTheCoder** [comment]
As of 4.0, the stonecutter recipes have been added for all the Chisel Chipped Integration blocks, and some blocks that were incorrectly hidden have been added back to JEI. Closing as added.
