### ISSUE TITLE
Do NOT Camouflage Your Modular Router With AE2 Cable Anchor

### ISSUE THREAD

**Issue by Rukka2** [ChosenArchitect/Project-Architect-2#172]
**Describe the bug**
->After adding an AE2 cable anchor camouflage mod to the modular router, the modular router becomes invisible and also becomes immovable block.

**To Reproduce**
1. Shift-Right click AE2 Cable Anchor while holding a Modular Routers Camouflage Upgrade
2. Open Modular Router UI and place Camouflage Upgrade in the upgrade slot
3. 
4. 

**Expected behavior**
-> The modular router camouflages itself as an AE2 cable anchor (But I kind of figured this break something, so...)

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)
Me holding a builder's wand trying to show the invisible block that should be a modular router. I can't interact with it or remove it via block breaking from various mods. As you can see, the builder's wand sees the cobblestone behind where the modular router is, but can't build into that space because the invisible modular router is there.
![2024-08-24_06 39 31](https://github.com/user-attachments/assets/5df91d7d-9d2d-4995-9571-3bce8d56b8d3)

**Modpack version**
->3.5
**Java Version**
->22 (latest version)
**Modpack Launcher Used**
->CurseForge
**Ram Allocated**
->10gb

**Additional context**
->I've tried to break the block with block breakers from Industrial foregoing and RFTools (builder with quarry card), but they act as though the block isn't there.

**Comment by James103** [comment]
What do you get in the logs when you try running `/data get block` with the coordinates of the invisible/intangible Modular Router?

**Comment by IRicTheCoder** [comment]
James provided a good question, also does the `latest.log` show anything when you are near the block or try interacting with it?

**Comment by Rukka2** [comment]
![2024-08-24_22 58 58](https://github.com/user-attachments/assets/406080d5-0e7a-42f9-9776-3fe6304b2d3c)

My latest.log is taken after trying to interact with the block shown in the screenshot below with the same builder's wand.
![2024-08-24_23 01 02](https://github.com/user-attachments/assets/26b0db09-efbd-4879-bf33-17a82575bd8b)

latest.log here: [latest.log](https://github.com/user-attachments/files/16739161/latest.log)

Side note: Pay no attention to the line reading, "The target block is not a block entity." I used the wrong coordinates the first time I ran the /data get block command. Also, Sorry it takes so long for me to respond. Life has been very busy lately.

**Comment by IRicTheCoder** [comment]
Well this is weird, but maybe there is a way to blacklist the cable anchor or any of the similar blocks from being allowed as camouflage.

**Comment by IRicTheCoder** [comment]
We couldn't find a solution for this, so a tooltip was added to the camouflage upgrade to say not to use anything related to cables from AE2. Closing this issue as "solved".

**Comment by yanyingfro** [comment]
I found a minor solution, albite niche. The cut & paste tool from Building Gadgets 2 allows you to specifically select the invisible block, hold 'g' (by mod default), and press the "cut" button top left of the GUI. This should remove the block.

**Comment by IRicTheCoder** [comment]
That gives me an idea on a potential fix, will look into it, thanks!

**Comment by IRicTheCoder** [comment]
Made a blacklist and you can no longer use this, should be impossible to set the camouflage to the anchor or any cable from AE2 after next update
