### ISSUE TITLE
Material generator switched ticks and RF/tick.

### ISSUE THREAD

**Issue by Havard-SL** [ChosenArchitect/Project-Architect-2#176]
**Describe the bug**
-> The Cyclic Material Generator doesn't generate power in accordance with the recipe list. I.e: Dragons breath should give 100ticks of 6400RF/tick but instead gives 100 RF/tick for 6400 ticks (5 min 20 sec).

**To Reproduce**
1.  Place Material Generator.
2.  Place any item into generator.
3. Watch the buffer go up with the wrong amount.
4. OPTIONAL: Hook it up to the Energy Meter block and get the exact numbers.

**Expected behavior**
-> Dragons breath and the other items should give the given RF/tick in the given ticks.

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)
N/A

**Modpack version**
-> 3.5
**Java Version**
-> 17 (Client)
**Modpack Launcher Used**
-> Prism Launcher
**Ram Allocated**
-> 8 GB

**Additional context**
-> I tried finding the JSON datapack mentioned in the JEI information pane of the Material Generator, but couldn't find it.

**Comment by IRicTheCoder** [comment]
The recipe list you refer to is from JEI correct, can you check other entries, it might be that the developer of the mod just made a mistake and put the values wrong on the display, as in switched them, since that is what it appears to be to me.

In any case fixing the display should be possible.

**Comment by Havard-SL** [comment]
@IRicTheCoder I've checked multiple entries and they are all switched. I've tested eye of ender, ender pearl, shulker shell, tnt, ghast tear and dragons breath.

**Comment by IRicTheCoder** [comment]
So it seems to be an issue with the mod displaying things switched, might be a way to fix the information to be shown right.

**Comment by IRicTheCoder** [comment]
In version 3.6 cyclic got updated and it seems to have fixed this issue, closing this as solved.
