### ISSUE TITLE
What's causing crazy server RAM usage in Project Architect 2

### ISSUE THREAD

**Issue by KhromeTheUnit** [ChosenArchitect/Project-Architect-2#177]
**Describe the bug**
-> server ram usage goes up to 13gb of ram in 10 min after launching server, even tho i'm by myself on the server, i was using 6gb of ram for a week and it was fine. Crazy RAM usage causes the server to close itself after 10min  

**Expected behavior**
-> that the ram usage stays "normal"

**Modpack version**
->3.3
**Java Version**
->17
**Modpack Launcher Used**
->ATLauncher

**Ram Allocated**
->12 on server, 9 client

Latest log :

[latest.log](https://github.com/user-attachments/files/16741349/latest.log)

**Comment by DiggityMan420** [comment]
version 3.5
![Screenshot_58](https://github.com/user-attachments/assets/7c49807e-9b7d-4194-b02e-0022bc956383)
ya i noticed this awhile back i run 10gb avg and its just me sometimes my son and me but rarely he like vanilla

**Comment by jerry1333** [comment]
Around 10GB for me too (version 3.5)
![obraz](https://github.com/user-attachments/assets/633be2d8-dc3d-4290-bea2-e2165edbca3d)

**Comment by IRicTheCoder** [comment]
This might not be normal, but Java can do this, pull all allocatable memory up to the given limit to have it already ready to be used. Not common, but happens. Other than that I don't see what could be the issue.

Dd you add new mods into the pack? Have you tried newer versions?

**Comment by KhromeTheUnit** [comment]
Hi, no i didn't add any mods, going on version 3.5 instead of 3.3 didn't solve it either. i managed to finish the modpack but with this issue... 
Also, i noticed that when i was in the End or in the Nether the server RAM usage looked normal... (even tho i chunk loaded my base, and my big main base was in the overworld, so something must've been loading weirdly when near it i guess..

**Comment by F1r3w477** [comment]
I've had this same issue, I enabled Aikars flags and it manages to keep the usage down enough for my daily server restart to fix the issue, however, if I start exploring a whole bunch, or go to a few dimensions, it climbs quickly. I allocate 8GB for the server.

**Comment by IRicTheCoder** [comment]
A lot of fixes and improvements came out all the way to 4.3 the latest version, this should not be happening with a fresh install of a 4.3 server.

If there is anymore issues please reopen this issue, I will be closing it has it doesn't seem to be happening anymore, as servers have reported to be more stable now.
