### ISSUE TITLE
not a bug report or suggestion.  More info about update (specifically removal of emc items)

### ISSUE THREAD

**Issue by DoomSquirter** [ChosenArchitect/Project-Architect-2#178]
**Is your feature request related to a problem? Please describe.**
again, not a bug report or suggestion but those are my only 2 options
Want to update but I'm curious what the impact will be on the one item:
"Removed a lot of Overlooked EMCable items (the ones that should - have had emc in the first place)"
->

**Describe the solution you'd like**
You don't have the kubejs or any files from the pack and the changes made in github so I can't look up this info myself
it would be nice to see a full list tho
->

**Describe alternatives you've considered**
I assume you don't manage the files in github for a reason?  that would be one alternative
->

**Mod Sugestions**
->

**Additional context**
Thanks for your time
->

**Comment by IRicTheCoder** [comment]
Its hard to keep track of this, you can always do "#EMC" on JEI to see what has EMC. Sorry for missing this, too many issue and things something there are a few things that get overlooked.

Searching that should help you figure what has EMC and what doesn't. Closing this as solved.
