### ISSUE TITLE
intergrated Dynamics fluid export

### ISSUE THREAD

**Issue by OgPaine** [ChosenArchitect/Project-Architect-2#18]
**Describe the bug**
Exporting fluids with intergrated Dynamics when setting the interger to anything  other then 0 it does not export fluids. But if the inteager is 0 it exports the fluids. I have the same issue on diffrent versions of the modpack back and lunchers
->

**To Reproduce**
1.  set interger to any number on the fluid exporter 

**Expected behavior**
to export fluids with the interger set to 999999999
->

**Screenshots**
![2024-07-27_12 36 11](https://github.com/user-attachments/assets/f6b30494-e2ff-428f-befe-d8afc7bcb60a)
![2024-07-27_12 36 17](https://github.com/user-attachments/assets/b06f9d06-a2ef-4d9b-924f-3334724938be)

**Modpack version**
-> 1.20-1.24
**Java Version**
->jdk-17
**Modpack Launcher Used**
-> prism Atluncher and curseforge 
**Ram Allocated**
->8224MB

**Additional context**
->

**Comment by MalaChaiLatte** [comment]
Gday, I may be misunderstanding, but it seems like your changing the "Channel" value in Integrated and not the transfer rate based on your screenshot.

**Comment by shiftthedev** [comment]
By changing the integer value for the "Channel" tab, you're telling the system that you only want to export fluids that are on that channel, meaning the you'd need to have either an importer or an interface on the same channel.
If you want to change the speed the fluids are exported, you need to change the integer value in the "Fluid Transfer Rate".
