### ISSUE TITLE
Draconic Evo. Items have no model

### ISSUE THREAD

**Issue by NoodlesWithRice** [ChosenArchitect/Project-Architect-2#180]
**Describe the bug**
-> On a multiplayer server (singleplayer not tested) Draconic Evolution armor and tools do NOT show in 3rd person and or to other people. The items are just invisible. 

**To Reproduce**
1.  Equip DE tools like the chestplate or the chaos sword on a server

**Expected behavior**
->The items will  not show up as a model on the player

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)
![2024-08-26_14 39 07](https://github.com/user-attachments/assets/2843f511-c2c4-4425-bcef-c9ae48b7eeeb)

**Modpack version**
->3.3
**Java Version**
->Honestly dont know, it chooses the right one automatically and I have way too many installed
**Modpack Launcher Used**
->
**Ram Allocated**
->10GB client 16 server

**Additional context**
->None

**Comment by IRicTheCoder** [comment]
Thanks for your report, unfortunately this seems to be an issue with Draconic Evolution itself, I am unsure it can be solved in the pack specifically. Does it render when in first person? And on the player's model in the inventory?

**Comment by NoodlesWithRice** [comment]
Hey,
Yes it does render in First Person, and so does it on the inventory model of the player. As far as my "reasearch" ;) went, it's a rendering conflict with another mod thats supposedly in the modpack.
Apperantly it should render in a only-DE-modpack.

**Comment by IRicTheCoder** [comment]
On your research did you get any idea what could be causing the render issue, or not so much? It seems to be the only mod with issues when it comes to that, finding the actual culprit will be complicated.

**Comment by NoodlesWithRice** [comment]
Okay, sooo...
My buddy says his mekanism items sometimes do the same. After trying to dis- and enable various graphic mods the dork seems to be oculus (?). After that I would have guessed it's the cosmetic armor mod.
Still, my best guess would definetly be Oculus. Some dude on GitHub also found a similar issue and said that i's the fault of Oculus not supporting specific shaders(?). Maybe that's forkable?

**Comment by IRicTheCoder** [comment]
Thank you for the feedback, if it is due to Oculus might not be something we can fix ourselves, but we will look into it.

**Comment by NoodlesWithRice** [comment]
Merci <3

**Comment by IRicTheCoder** [comment]
This cannot be fixed by us, you have two choices, either disable Oculus if not playing with shaders, or disable the fancy models from Draconic Evolution. Closing the issue as sorted even though it wasn't solved.
