### ISSUE TITLE
add Essential mod

### ISSUE THREAD

**Issue by Fain225** [ChosenArchitect/Project-Architect-2#184]
**Is your feature request related to a problem? Please describe.**
->challenges loading multiplayer worlds of other players

**Describe the solution you'd like**
->add Essential mod by SparkUniverse_ to Project Architect 2 modpack

**Describe alternatives you've considered**
->

**Mod Sugestions**
->Essential mod by SparkUniverse_

**Additional context**
->allows friends to join singleplayer worlds and automatically converts them to multiplayer

**Comment by ChosenArchitect** [comment]
This mod will not be added but you can always add it yourself when you want to play with friends.
