### ISSUE TITLE
Broken EMC farm

### ISSUE THREAD

**Issue by DieAnotherDayTD** [ChosenArchitect/Project-Architect-2#186]
**Describe the bug**
->Bamboo logs can be turned into bamboo rafts to make profit

**To Reproduce**
1. Find a bamboo log and learn it and fill a drawer with it
2. Create a crafter setup that turns bamboo logs into planks then planks into rafts
3. Feed the raft to an energy condenser
4. PROFIT

**Expected behavior**
->I expected to have an equal exchange of EMC maybe a bit more EMC because of the labor work but difference is massive

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)

**Modpack version**
->3.3
**Java Version**
->
**Modpack Launcher Used**
->
**Ram Allocated**
->12GB

**Additional context**
->

**Comment by ChosenArchitect** [comment]
Fixed next update! Thanks for the report!
