### ISSUE TITLE
Suggestion: Disable weird JAOPCA outputs

### ISSUE THREAD

**Issue by moon-st0ne** [ChosenArchitect/Project-Architect-2#190]
**Is your feature request related to a problem? Please describe.**
->These should not be allowed to exist. Additionally, some JAOPCA blocks correspond to resources from mods not in this pack.
![image](https://github.com/user-attachments/assets/2d3044e4-f376-41d7-a140-98a46a443b64)
![image](https://github.com/user-attachments/assets/cb8c38a7-f1d5-4647-ad0a-e7868c3c9b5e)
![image](https://github.com/user-attachments/assets/8ab1c600-e34f-4506-b2bf-fd29aaf74323)

**Describe the solution you'd like**
->Disable JAOPCA blocks which either do not make any sense ("block of brick", "block of fluix", "block of glowstone", etc.) or which do not correspond to ores which are in the pack (alfsteel, pendorite, etc.)

**Describe alternatives you've considered**
->I've considered deleting JAOPCA from my mods folder (can you tell that I do not like this mod?) but that might break some things, so I decided to submit a ticket.

**Mod Sugestions**
->

**Additional context**
->Thanks for including Thaumon!

**Comment by IRicTheCoder** [comment]
As of 4.0, these blocks have been sorted, as well as some got renamed as they were right, but had the wrong name. Closing this as sorted, thanks!
