### ISSUE TITLE
RFtools dimension not working with ProjectE or diamond blocks

### ISSUE THREAD

**Issue by KStream-m8** [ChosenArchitect/Project-Architect-2#191]
**Describe the bug**
-> The block absorber does not take any matter block (such as black matter, red matter etc.) and gives 100% progress without identifying the block

**To Reproduce**
1. Block Absorber
2. Red Matter Block

**Expected behavior**
-> The Block Absorber should be able to absorb the block as it does for any other block

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)
![2024-08-30_12 02 04](https://github.com/user-attachments/assets/28e05bc7-f44b-41e2-afd7-a0b221cbca90)

**Modpack version**
->Project Architect 2, version 3.6
**Java Version**
-> I really don't know
**Modpack Launcher Used**
-> CurseForge
**Ram Allocated**
-> 12 GB

**Additional context**
-> In addition the dimension workbench is not working blocks are not configured for this modpack.

**Comment by ChosenArchitect** [comment]
I think those are the compressed blocks and they are disabled and so are ProjectE blocks but normal diamond blocks should work fine

**Comment by KStream-m8** [comment]
The issue is that the diamond blocks are all based on the compressed version so there is no normal diamond blocks. The rest are not working for the workbench so I am not sure what to do to progress with RFtool dimensions

**Comment by IRicTheCoder** [comment]
You need to research the Knowledge Things that drop from enderman, then add them to a Knowledge Holder that sits next of the Workbench to unlock the dimlets. When you have the rare blocks one you will see diamonds.

**Comment by KStream-m8** [comment]
Ok, thanks for that advice! I managed to get it after two rare scripts were put in the knowledge holder
