### ISSUE TITLE
hotbar stack displaying above 64, in inventory it shows a normal value

### ISSUE THREAD

**Issue by Vichyra** [ChosenArchitect/Project-Architect-2#192]
**Describe the bug**
->the hotbar shows an inventory stack a lot bigger than it is in reality, even above the limit of 64. it provides issues when placing blocks from that inventory slot

**To Reproduce**
1. trade in a @easyvillager trader with a trade more than a 64 emerald trade with emerals in targeted hotbar slot
2. place any stackable item in that inventory hotbar slot
3. 
4. 

**Expected behavior**
->stacking not going above 64

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)
![2024-08-30_11 58 11](https://github.com/user-attachments/assets/9f774931-cb1e-4153-a22b-3c3f0e882e51)
![2024-08-30_11 58 16](https://github.com/user-attachments/assets/759ff584-a8ec-439f-88a4-86ac76c1e748)

**Modpack version**
->3.6 (also happened in 3.5)
**Java Version**
->
**Modpack Launcher Used**
->Curseforge
**Ram Allocated**
->12800 MB

**Additional context**
->

**Comment by IRicTheCoder** [comment]
Did you test anything else or try to attempt to remove that "extra limit"? This seems like one of those Edge Case scenarios as I have not seen this yet happen besides a single report on Discord. Have you added any mods to your pack?

**Comment by Vichyra** [comment]
I have reloaded the pack, updated the pack twice since i ran into the issue. Anything works in those 2 inventory slots as long as they are not stackable. If i place stackable blocks from that spot it at some point runs into the issue where it displays a number while in reality it is 0 left. 
The other hotbar slots to not seem to have any issue, just those 2.
I havent done anything in terms of adding or removing mods as i have 0 knowledge on that kinda things. 
Probably the discord report was also me, i was direct to the github to report it.

I basically ran out of my knowledge as of how to fix it or to check if it is a bug, hence why i reached out here.

**Comment by IRicTheCoder** [comment]
Well you could try this:

1. Store everything in your character into a chest or similar;
2. Remove everything from any enderchest you might have, put it into a normal chest;
3. Go to your save and delete your player data (`saves\[NAME]\playerdata`);
4. Try again.

If in singleplayer you should only have 4 files all with the same ID in their name, delete both the `[ID].dat` one, the `dat_old` one and the `_cyclic` one. **BUT DO BACK THEM UP BEFORE DOING THIS**.

**Comment by Vichyra** [comment]
> Well you could try this:
> 
> 1. Store everything in your character into a chest or similar;
> 2. Remove everything from any enderchest you might have, put it into a normal chest;
> 3. Go to your save and delete your player data (`saves\[NAME]\playerdata`);
> 4. Try again.
> 
> If in singleplayer you should only have 4 files all with the same ID in their name, delete both the `[ID].dat` one, the `dat_old` one and the `_cyclic` one. **BUT DO BACK THEM UP BEFORE DOING THIS**.

This does seem to be the magic trick. Thank you so much! 
Ill fiddle around with the game some more tomorrow to see if the issue pops up again.

**Comment by Vichyra** [comment]
> > Well you could try this:
> > 
> > 1. Store everything in your character into a chest or similar;
> > 2. Remove everything from any enderchest you might have, put it into a normal chest;
> > 3. Go to your save and delete your player data (`saves\[NAME]\playerdata`);
> > 4. Try again.
> > 
> > If in singleplayer you should only have 4 files all with the same ID in their name, delete both the `[ID].dat` one, the `dat_old` one and the `_cyclic` one. **BUT DO BACK THEM UP BEFORE DOING THIS**.
> 
> This does seem to be the magic trick. Thank you so much! Ill fiddle around with the game some more tomorrow to see if the issue pops up again.

Scrap that, it already happend again. only thing i did was grab the stuff i had on me from the chest and now the fenceposts are being wonky

![2024-08-31_00 51 32](https://github.com/user-attachments/assets/18c0c33a-5624-4a6b-875c-84f9c089558b)

**Comment by IRicTheCoder** [comment]
There might be some item with you that is causing issues, maybe it is a bit corrupted, you would have to experiment with it to figure it out, I have no idea why this would be happening 🤔

**Comment by Vichyra** [comment]
> There might be some item with you that is causing issues, maybe it is a bit corrupted, you would have to experiment with it to figure it out, I have no idea why this would be happening 🤔

Its the wireless universal terminal from AE2. once i added that item to my inventory it started happening. put it back in the chest and the stack size went back to normal. Made a new exact same one (same 2 wireless terminals into it) and it does not replicate the issue. Adding back the corruped item to my inventory, the stack sizes in those 2 hotbars go wonky

**Comment by IRicTheCoder** [comment]
Does it have an export/import card in it? Or do you have Restock on in the bugged one?

**Comment by Vichyra** [comment]
> Does it have an export/import card in it? Or do you have Restock on in the bugged one?

The bugged one had a singularity and a quantum bride card in it. I just moved those 2 over to the new terminal and both are now not showing the issue. 
just tried swapping them around in inventory slots and the old one yeeted itself out of the world (litterally just dissapeared). tho that also just deleted the singularity and the bride card as those were in the bugged one as i was testing the scenario where the place of the terminal on the hotbar would matter. Maybe the problem just fixed itself there?

**Comment by IRicTheCoder** [comment]
Seems to be a very specific edge case, hard to tell what is realistically the issue, if you run into it again please provide feedback here. For now I will close this as solved. You can reopen it if the bug comes back!
