### ISSUE TITLE
Creative flight

### ISSUE THREAD

**Issue by jerry1333** [ChosenArchitect/Project-Architect-2#193]
**Describe the bug**
In quest book there is a quest "Swiftwolf's Rending Gale" in ProjectE chapter. Description and everything in that quest suggests that after creating ring you'll get creative flight - but this ring is some piece of garbage - cant flight with it :/ 
->

**To Reproduce**
1. Create "Swiftwolf's Rending Gale"
2. Try to fly from really high cliff
3. ...
4. DIE

**Expected behavior**
NOT DIE
->

**Screenshots**
![obraz](https://github.com/user-attachments/assets/104a8131-ac49-427f-a0a9-3a47da0e5fd2)

**Modpack version**
-> 3.5
**Java Version**
-> Anything that's FTB App installed
**Modpack Launcher Used**
-> FTB App
**Ram Allocated**
-> 6GB

**Additional context**
...
->

**Comment by IRicTheCoder** [comment]
You need to have an EMC battery to keep it working. Like a Klein Star which you can charge in the left side of your Transmutation Table.

**Comment by jerry1333** [comment]
Ohh boy, it works but who would though that it's so complicated... geez...

I going to install few more mods to this pack.

Thanks for quick help!
