### ISSUE TITLE
Create Steam Engine missing from JEI

### ISSUE THREAD

**Issue by miklam** [ChosenArchitect/Project-Architect-2#194]
**Describe the bug**
->The Create 'Steam Engine' isn't showing up in JEI when searching for it. It is still available to craft, but the recipe is missing in the JEI UI.

**To Reproduce**
1. 
2. 
3. 
4. 

**Expected behavior**
-> The item should show up in JEI

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)

**Modpack version**
-> 3.6
**Java Version**
-> 17.0.12
**Modpack Launcher Used**
-> Prism Launcher
**Ram Allocated**
-> 10240 MiB

**Additional context**
->

**Comment by ChosenArchitect** [comment]
It is showing for me... 
![image](https://github.com/user-attachments/assets/feb1f40b-a8e6-4047-ba4f-526434df0938)
![image](https://github.com/user-attachments/assets/ff49ad5b-dcdb-4aa5-8847-4be011ebdd0a)

**Comment by IRicTheCoder** [comment]
It is a bug with JEI, haven't figured out why. Some items sometimes disappear, but relogging normally brings them back.

**Comment by miklam** [comment]
Yeah, I tried relogging and the steam engine is there again. Apologies for not testing more properly!

**Comment by IRicTheCoder** [comment]
These issues should no longer happen in version 4.0+ with the new update from JEI and added "force show" logic we made.
