### ISSUE TITLE
Create Crafts & Additions Alternator hidden in JEI

### ISSUE THREAD

**Issue by moon-st0ne** [ChosenArchitect/Project-Architect-2#195]
**Describe the bug**
->The Alternator from Create Crafts & Additions, which is required for the "Create Power?" quest in the Power tab, is hidden in JEI and the creative search menu. The recipe is only accessible through this quest.

**To Reproduce**
1. Launch Project Architect 2 version 3.6
2. Search for "Alternator" in JEI and/or the creative search menu
3. Find no Alternator
4. ???

**Expected behavior**
->Alternator should not be a hidden item

**Screenshots**
![image](https://github.com/user-attachments/assets/7c493162-b564-44f7-a067-5887b54e5c95)

**Modpack version**
->3.6
**Java Version**
->17
**Modpack Launcher Used**
->Prism
**Ram Allocated**
->8192MB

**Comment by moon-st0ne** [comment]
Ok, it seems this issue isn't limited to just CC&A. Here, you can see Create's gearbox is missing from JEI.
![image](https://github.com/user-attachments/assets/bbcb260e-043b-45ba-ad4f-6211085b02cf)

**Comment by IRicTheCoder** [comment]
This is a bug with JEI, been looking into it, but seems to be very random. Relogging tends to fix the issue, or restarting the server if playing in one.

**Comment by IRicTheCoder** [comment]
These issues should no longer happen in version 4.0+ with the new update from JEI and added "force show" logic we made.
