### ISSUE TITLE
Mis spell :)

### ISSUE THREAD

**Issue by XenonsTech** [ChosenArchitect/Project-Architect-2#198]
**Describe the bug**
-> worm instead of wrym in magic storage quest

**To Reproduce**
1. open your ftb quests
2. 
3. 
4. 

**Expected behavior**
-> easily fix it

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)

**Modpack version**
-> 3.6
**Java Version**
-> 1.20.1
**Modpack Launcher Used**
-> Prism
**Ram Allocated**
-> 10

**Additional context**
-> just remember chosen

**Comment by ChosenArchitect** [comment]
fixed next update!
