### ISSUE TITLE
Personal Shrinking Device 'Toggle Shrink' keybind does not toggle shrinking.

### ISSUE THREAD

**Issue by wieto** [ChosenArchitect/Project-Architect-2#199]
**Describe the bug**
-> The keybind for the personal shrinking device does not toggle shrinking.

**To Reproduce**
1.  Bind any key to 'Toggle Shrink' in the keybinds menu.
2. Press the key in-game. 

**Expected behavior**
-> The key should toggle the shrinking of the player.

**Modpack version**
-> 3.6
**Java Version**
-> 17.0.12
**Modpack Launcher Used**
-> Prism Launcher
**Ram Allocated**
-> 6144 MiB

**Additional context**
->

**Comment by IRicTheCoder** [comment]
Haven't been able to test this, but do you have the device in your inventory? Did you open it once to configure it?

**Comment by wieto** [comment]
> Haven't been able to test this, but do you have the device in your inventory? Did you open it once to configure it?

Yes to both. This bug has been confirmed by one other person from the discord. 

Edit: It's worth mentioning that shift-right clicking, with the device in-hand, does work as expected. It's just that the keybind seems to be broken for some reason.

**Comment by IRicTheCoder** [comment]
This is in fact an issue with the mod, for what I gather it has been reported, and it has been worked on or is being worked on.

I will close this has we cannot do anything about it, thank you for the report!
