### ISSUE TITLE
[BUG] - Crafting inside Sophisticated Backpack with Crafting Upgrade Crashes game

### ISSUE THREAD

**Issue by DizzyDJW** [ChosenArchitect/Project-Architect-2#2]
**Describe the bug**
Crafting using the Crafting Upgrade inside the Sophisticated Backpack crashes the game.

**To Reproduce**
1. Craft Sophisitcated Backpack (Mine was Diamond)
2. Craft Crafting Upgrade
3. Try to craft any item using the upgrade
4. See issue

**Expected behavior**
Not that

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)

**Modpack version**
2.0
**Java Version**
Java 17
**Modpack Launcher Used**
Prism
**Ram Allocated**
8GB

**LOG File**
https://mclo.gs/Rjnnw6P

**Additional context**
"Reported exception thrown!
net.minecraft.ReportedException: Container click"

**Comment by ChosenArchitect** [comment]
Did you by chance get a crashlog? if Sould I would love a pastebin of that

**Comment by shiftthedev** [comment]
Did you added any mods?

**Comment by James103** [comment]
I just got the attached crash report while crafting Wind Generators from Mekanism, by using JEI to fill in the recipe into the Sophisticated Backpacks crafting table-in-an-upgrade and shift-clicking the output.
[crash-2024-07-27_20.06.53-client.txt](https://github.com/user-attachments/files/16401889/crash-2024-07-27_20.06.53-client.txt)
