### ISSUE TITLE
crafting RS storage parts in sophisticated storage barrel with crafting upgrade crashes client

### ISSUE THREAD

**Issue by tsuuii** [ChosenArchitect/Project-Architect-2#20]
crafting Refined Storage storage parts in sophisticated storage barrel with crafting upgrade crashes client
doesn't crash with every craft, was makeing 256k storage part and it crashed my client with
1k, 4k and 16k parts as i crafted them. 2 crashes happend shift clicking (multiple crafts) and 1 crash
single clicking and holding previos crafts. 

**Modpack version**
2.23

**Ram Allocated**
6

**Comment by shiftthedev** [comment]
can you share a crash-report? you can use https://mclo.gs

**Comment by tsuuii** [comment]
[mclo.gs/tucQV0v](url)

**Comment by IRicTheCoder** [comment]
With some updates of the respective mods, this issue seems to be fixed as of version 4.0. Closing it as solved, feel free to reopen the issue if the problem persists.
