### ISSUE TITLE
wtf was that

### ISSUE THREAD

**Issue by tekutora** [ChosenArchitect/Project-Architect-2#200]
i was doing some mechanisms and started hearing some fucking scary sounds i shat myself what was that 
is that because of killing pigs????
i wanna delete this mod cuz i am mentally fucking weak and i hate anything that scares me

**Comment by tekutora** [comment]
what the name of this mod say me pls

**Comment by IRicTheCoder** [comment]
Where were you, what were you doing when the sound started? You can open your inventory, press the speaker icon with a red line on top, and see the sounds that are there, you can listen to them, and mute what you don't want.

Without more information its impossible to tell you what the sound/mod was.

**Comment by tekutora** [comment]
i was in my basement doing mechanisms and then i started hearing voices sculk sounds footsteps and other not explainble sounds

**Comment by tekutora** [comment]
putting dificulty peacful stopted the sounds, but i didnt see any mobs on minimap

**Comment by IRicTheCoder** [comment]
Are you close to an Ancient City? You could have triggered a Shrieker which is Vanilla.

**Comment by tekutora** [comment]
no i dont, thats the problem

**Comment by tekutora** [comment]
its not only about skulk

**Comment by tekutora** [comment]
footsteps like player scary loud sounds

**Comment by tekutora** [comment]
im experienced minecraft player and i know that its wasnt vanilla

**Comment by tekutora** [comment]
im trying to find this sound in sound muffler in inventory but i cant

**Comment by IRicTheCoder** [comment]
First of all, please stop sending 30 messages in a row. I am trying to help you, so please put everything in a single message. Can you post screenshots of where it happened? Can you explain more than "mechanisms" what you were doing?

This is the first time, that I am aware, something like this has been reported, so it is not simple to sort out what is the cause, and/or what really happened.

**Comment by tekutora** [comment]
sorry, im not a native english speaker im trynig my best

**Comment by tekutora** [comment]
![image](https://github.com/user-attachments/assets/61091977-9d65-4edb-97c5-357f982c4a77)
i was there and there was a wither in glass cage doing common wither sounds and nothing more and then those sounds happens

**Comment by tekutora** [comment]
wither was in stasis chamber for gas so hes afk

**Comment by tekutora** [comment]
and those sounds was louder when i was looking in the wall

**Comment by tekutora** [comment]
and music disc 13 started playing with those sounds, and i know there is a mobs with backpacks doing music, but i never heard a mob doing this kinda sounds, and there was no mobs on minimaps and i have megatorches against hostile mobs spawn

**Comment by tekutora** [comment]
![image](https://github.com/user-attachments/assets/baedd475-b820-4e7c-a2dc-3d035c9aeb8e)
i found it

**Comment by tekutora** [comment]
this is the sounds, but again theres no mobs how can that happen

**Comment by tekutora** [comment]
sorry for spamming in still in panic

**Comment by IRicTheCoder** [comment]
I was going to suggest looking at the disks, since you talked about the backpacks. Not all mobs are blocked by Mega Torches, passive mobs can spawn with the backpack too. Maybe that was the case.

So you found the sound and have muted it right?

**Comment by tekutora** [comment]
yes

**Comment by tekutora** [comment]
im really sorry for all that

**Comment by tekutora** [comment]
im going to send you a video right now i understood what was that

**Comment by IRicTheCoder** [comment]
No need, I already tested it on my world and understood what the issue was, glad you found it. Have fun playing!

**Comment by tekutora** [comment]
i really want u to watch this https://youtu.be/-ZRDbIsX1F4

**Comment by tekutora** [comment]
thank you for support
