### ISSUE TITLE
Incorrect quest item name.

### ISSUE THREAD

**Issue by Kapppa** [ChosenArchitect/Project-Architect-2#202]
**Describe the bug**
-> Pig quest has the stuffed pigil as Pig in pin text.

**To Reproduce**
1. Open Quest book
2. 
3. 
4. 

**Expected behavior**
-> Should be stuffed hoglin

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)
![image](https://github.com/user-attachments/assets/7ca27f46-622b-4930-8c09-63ad7d03c108)

**Modpack version**
-> 3.6
**Java Version**
-> Java 17
**Modpack Launcher Used**
-> Prism
**Ram Allocated**
-> 16GB

**Additional context**
->

**Comment by IRicTheCoder** [comment]
This is finally fixes in version 4.5, closing the issue
