### ISSUE TITLE
Modular routers cant be broken in survival

### ISSUE THREAD

**Issue by thisKid619** [ChosenArchitect/Project-Architect-2#204]
**Describe the bug**
-> after placing a modular router it cant be removed with a vanilla or modded pick axe

**To Reproduce**
1.  place modular router
2. try to break router
3. 
4. 

**Expected behavior**
-> modular router breaks when mined

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)

**Modpack version**
-> 3.5
**Java Version**
-> 1.20.1
**Modpack Launcher Used**
-> curseforge
**Ram Allocated**
->9000

**Additional context**
-> the routers can be broken in creative

**Comment by IRicTheCoder** [comment]
Update to 3.6 that has been fixed on that version, it was broken in 3.4/3.5, if you want to break it in those versions use a tiny TNT or turn cheats on. If on a server you need to be OP.

**Comment by thisKid619** [comment]
when i update to 3.6 i get an immediate crash related to quark

**Comment by IRicTheCoder** [comment]
Can you share the crash-report? Without that it is hard to know what is going on
