### ISSUE TITLE
Dimlet Workbench contains disabled block dimlets

### ISSUE THREAD

**Issue by Gerdathlete** [ChosenArchitect/Project-Architect-2#206]
See: https://github.com/McJtyMods/RFToolsDimensions/issues/502

The RFTools Dimensions configs cause blocks that cannot be used in dimlets to show up in the dimlet workbench. The issue can be fixed by removing the listings from the .json files.

The config files in question are in config/rftoolsdimensions.

Modpack Version: 3.6

**Comment by IRicTheCoder** [comment]
We are aware, that has been tweaks and should be fixed in an upcoming version, thank you for the report! I did a dive into the code and ended up realizing that such was the case. It just doesn't make sense to me that it is like that.

**Comment by IRicTheCoder** [comment]
In version 4.0 this should have been sorted and disabled dimlets should not appear anymore. Closing this as solved.
