### ISSUE TITLE
Updated Modpack Error

### ISSUE THREAD

**Issue by Enji-HD** [ChosenArchitect/Project-Architect-2#209]
Coming from playing 3.3 I updated to the most recent 3.6 and after that loading into my world it first initiates "reading world" into the infinite dirt block screen.

**To Reproduce**
1. Right lclick mod icon
2. Change version 3.6
3. update to new modpack
4. load minecraft
5. load world
6. Dirt void.

**Expected behavior**
-> Load into the world.

**Modpack version**
-> 3.6
**Java Version**
-> Java 8 update 421 (64-bit)
**Modpack Launcher Used**
-> Curse Forge
**Ram Allocated**
-> 7GB

**Comment by IRicTheCoder** [comment]
If you haven't changed any configs, you can go to your world folder `saves\WORLDNAME\serverconfig` and delete all files inside, and see if that helps.

**Comment by Enji-HD** [comment]
I figure it out. Lol. I forgot I had other mods within the modpack so i just had to add the other mods i added to the updated modpack. Thank you for the fast reply!

**Comment by IRicTheCoder** [comment]
If it is solved, I will close the issue, thanks!
