### ISSUE TITLE
Functional Storage's Framed Drawers have EMC values

### ISSUE THREAD

**Issue by Cynan** [ChosenArchitect/Project-Architect-2#21]
Whilst all normal drawers for Functional Storage don't have EMC.  The framed drawers have an EMC of 64.

Framed Drawer (1x1)
Framed Drawer (1x2)
Framed Drawer (2x2)

Both untextured and textured variants have EMC

I doubt this is on purpose and it could catch someone out if they have a vacuum hopper sending items to an EMC feeder or when clearing an inventory when a textured drawer alongside its contents could be traded in for 64 EMC.

Has been around but just confirmed this is still present in 2.4

**Comment by ChosenArchitect** [comment]
Will fix next update!
