### ISSUE TITLE
Refined Obsidian recipe

### ISSUE THREAD

**Issue by Nutz117** [ChosenArchitect/Project-Architect-2#211]
Version 3.6

Mekanism refined obsidian cannot be crafted without refined obsidian or an item made of refined obsidian. The osmium compressor uses refined obsidian dust to make refined obsidian ingot and refined obsidian dust is only made by crushing or pulverizing refined ingot. Obsidan dust seems to have been removed from the game. It does not appear in JEI. Obsidian dust should be used in the metallurgic infuser with diamond to create refined obsidian dust.

**Comment by IRicTheCoder** [comment]
The Recipe is:

- `Diamond Dust`
- `Powdered Obsidian` (from Create)
Result: `Refined Obsidian Dust`

Is the recipe not actually appearing in JEI?

**Comment by Nutz117** [comment]
May have missed a tab. JEI does show the correct recipe in the metallurgic infuser. Thank You

**Comment by IRicTheCoder** [comment]
No problem, have fun. Will make the issue as resolved.
