### ISSUE TITLE
A letter from a quest is missing

### ISSUE THREAD

**Issue by mazencj** [ChosenArchitect/Project-Architect-2#212]
**Describe the bug**
-> **In the Screenshot below** 

**To Reproduce**
1. 
2. 
3. 
4. 

**Expected behavior**
->

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)

![2024-09-07_19 58 56](https://github.com/user-attachments/assets/e4150e85-ee3a-4265-bf27-46877b1aa0ea)

**Modpack version**
-> 3.6
**Java Version**
->
**Modpack Launcher Used**
->
**Ram Allocated**
->

**Additional context**
->

**Comment by ChosenArchitect** [comment]
fixed next udpate
