### ISSUE TITLE
ae2 items disappearing  

### ISSUE THREAD

**Issue by LuhLynnRose** [ChosenArchitect/Project-Architect-2#213]
**Describe the bug**
-> When I auto-craft or place items in the system they vanish I can fix it for a minute by powering off the whole system then it works, and then it happens again.

**To Reproduce**
1. try to auto craft
2. put items in the system
3. 
4. 

**Expected behavior**
->to not lose my items.

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)

**Modpack version**
->
**Java Version**
->
**Modpack Launcher Used**
->
**Ram Allocated**
->

**Additional context**
->

**Comment by IRicTheCoder** [comment]
Do you have a transmutation interface connected to the system? Is there any storage buses? Is your controller in a loaded chunk?

**Comment by IRicTheCoder** [comment]
There has not been any feedback on this for 2 weeks, assuming it was solved and closing the issue.
