### ISSUE TITLE
Mod add 

### ISSUE THREAD

**Issue by whitenet** [ChosenArchitect/Project-Architect-2#214]
**Mod Sugestions**
Create: Enchantable Machinery - https://www.curseforge.com/minecraft/mc-mods/create-enchantable-machinery
Create Enchantment Industry - https://www.curseforge.com/minecraft/mc-mods/create-enchantment-industry

its be nice to have this addons on modpack make create even more better

**Comment by IRicTheCoder** [comment]
Not sure if you looked through the modpack actually, but the `Create Enchantment Industry` is in the pack. As for the other one, I will put it on the suggestion list for consideration.

**Comment by IRicTheCoder** [comment]
`Create: Enchantable Machinery` has added to the pack making both mods here in it. Closing this as added.
