### ISSUE TITLE
Reinforced Alloy Recipe missing from V3.6 

### ISSUE THREAD

**Issue by MrBaldpatch** [ChosenArchitect/Project-Architect-2#216]
There is no recipe for Reinforced alloy in V3.6. 

recipe was there in v3.4 I only changed the version today.

makes Mekanism impossible to get to higher tier machines .

**Comment by IRicTheCoder** [comment]
The recipe should still work. JEI is having issues with displaying certain recipes and/or items. Seems to be solved in the latest version of JEI, you can try to update only that mod and try again. We will update it when the pack gets updated again.

**Comment by ChosenArchitect** [comment]
Shows up in next update version so should be fixed
