### ISSUE TITLE
Diamond gear recipe is missing

### ISSUE THREAD

**Issue by LuciusV** [ChosenArchitect/Project-Architect-2#217]
**Describe the bug**
->
Multiservo Press cannot make diamond gears
**To Reproduce**
1.  see JEI

**Expected behavior**
->
recipe should be present

**Comment by IRicTheCoder** [comment]
That might have been an issue when some other recipes were adjusted, will look into adding that recipe back into the game, for now you should be able to craft it using the crafting table recipe.

**Comment by ChosenArchitect** [comment]
fixed next update
