### ISSUE TITLE
QOL  add pipe connector mod

### ISSUE THREAD

**Issue by MrBaldpatch** [ChosenArchitect/Project-Architect-2#218]
QoL mod

https://www.curseforge.com/minecraft/mc-mods/pipe-connector

Add the above mod to make laying majority of cables and pipes quick and painless. Its a simple mod that wont break the game. Just shift Right click on a start and end point, shift scroll to set the depth and the right click the air with the cable/pipe i your offhand and the pipe connector in main. it will run the pipes for you.

**Comment by IRicTheCoder** [comment]
I have added that mod to the list of suggestions to look into, it has been suggested before, seems just QoL so it might get added, we will see. Thanks for the feedback!

**Comment by IRicTheCoder** [comment]
As of now, this mod won't be added, the pack is mainly finished and we saw no need to add this mod. Thanks for the suggestion, closing this as not planned
