### ISSUE TITLE
Building Gadgets and create wrench don't work in 3.6

### ISSUE THREAD

**Issue by QahnaarinOrigin** [ChosenArchitect/Project-Architect-2#219]
**Describe the bug**

->ALL the BG2 items, fully charged, do not function at all. Cannot select block with BG, can't destroy blocks with destroyer, can't copy/paste (says 0 blocks selected) and I didn't bother with the others. Figured they did not work as the first 3 absolutely don't work at all. Everything else works as normal (menu/settings, charge, etc.), they just do not function as intended.

I cannot use the create wrench to pick up any create blocks (the basic function of the wrench). It does not work to turn/adjust create blocks either. The only thing I can do with the wrench is pull blocks from the copycat blocks. 

I started a new world and the issues still persist.

**To Reproduce**
1. Just using the items as intended does not function as expected, no steps.
2. 
3. 
4. 

**Expected behavior**

->Building gadgets supposed to select blocks with shift+right click, copy selected area, etc as their functions are intended.

->Create Wrench does not pick up and place into inventory any Create items when shift+right click.

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)

->Don't know how to use this site (or my PC) to find screenshots... I'm not exactly a forum user or in-depth PC user. I only know how to use google search (horribly) and play Minecraft. I don't even know how to use ComputerCraft, xNet, Factory Manager or anything along those lines in mods either. I've taken a LOT of accidental screens and I don't know how to find them to delete the unnecessary useless images. And by "horribly," I can't even find how to do the screenshot thing. Every result shows 3-6 year old guides that don't line up with the current forum (included 2024 in the search). 

**Modpack version**
->3.6
**Java Version**
->1.8.0_421-b09
**Modpack Launcher Used**
->CurseForge
**Ram Allocated**
->12gb

**Additional context**
->

**Comment by IRicTheCoder** [comment]
I have used the items mentioned without issues in V3.6, so I am not sure what could be happening, did you change any configurations or added any mods to the pack? I do understand you are not a PC user, and are not used to use it besides playing Minecraft, but could changes to your pack have been made?

**Comment by QahnaarinOrigin** [comment]
The only config I've learned to modify is ultimine. I can change saturation and amount of blocks mined. I don't understand the rest of the lines in that file and don't touch them.

I have the game as it's standalone pack, unmodified. Including ultimine. I typically like to play around as intended and then modify ultimine later down the line in other packs. Since everything is EMCable, I don't have the need to modify that file.

Other than that, i have tried starting a new world (I mapped a border to all the 5k points and realized it built up 2gb of data and causing lots of lag), cheated in the items required to make them work and still had the same problem. The only thing I haven't done is reinstall the pack in case there was a hiccup in data.

I suppose I can also try to take a pic with my phone and make an attempt to post them with the tap to add function below this text box (just thought of that right now lol).

![20240911_110400](https://github.com/user-attachments/assets/c152920f-972d-47f2-88e6-a1532eabdeea)

![20240911_110336](https://github.com/user-attachments/assets/cbb905ec-7038-4ba0-9a07-f017b3e01633)

![20240911_110326](https://github.com/user-attachments/assets/e061aa69-9a7d-46cd-9c10-4b65d126ded1)

![20240911_110306](https://github.com/user-attachments/assets/e1e5ceff-5923-4979-9d32-166e2b0e1b4c)

![20240911_110244](https://github.com/user-attachments/assets/305aa289-a740-4dc1-afb1-326aab2f6982)

![20240911_110155](https://github.com/user-attachments/assets/3443e7eb-d5db-49bc-9eeb-8e3f5b4256a7)

![20240911_110119](https://github.com/user-attachments/assets/e2116150-2082-406f-a31b-d67e188872ef)

![20240911_110058](https://github.com/user-attachments/assets/5761c03d-71b2-43d1-8266-d9c475e36aab)

![20240911_105938](https://github.com/user-attachments/assets/8c3798b3-3a87-4d4a-8221-7a1e313addb2)

You can see in one image with the copy/paste I'm trying to right click and no effect - this time it doesn't even say "copied 0 blocks" like it did last time I tried to use it. I wanted to copy the boat and station in one of the random tribal-style villages and pull the airship villages to be slightly above about 50-75 blocks. This would've been the "repair station" with others hovering, queued for due repairs.

![20240911_111401](https://github.com/user-attachments/assets/b702408a-5c78-4009-b8f6-1bc07d0c103c)

I'm not sure if there's a conflict in keybinds eg: if I use sort inventory on middle click, I can't pick block. Yes, weird. It worked in atm9tts, but not here either. I just re-key sort inventory. I also have this issue in vault hunters, so it's not exclusive to just this pack.

However, I can't figure out what may cause the keybind conflict, if it is that. Or maybe it's a missing mod atm9 has that prevents those conflicts? 

Also, not sure if it's based on shaders? I had to turn them off. My PC is a potato and couldn't run with shaders on, even with just ore glow on. Every movement had a 2 second hitch before it responded to my control - horrendous.

**Comment by IRicTheCoder** [comment]
Shaders are heavy by nature, and can't run well on some PCs. As for the rest I am unsure of what is happening, as I haven't used the copy/paste cut/paste tools that much, but for the exchanging you need to sneak/shift + right-click the block you want to set as the block to exchange the others with.

**Comment by QahnaarinOrigin** [comment]
Yes, same with building gadget. Both were set to air and wouldn't pick a
selected block.

However, I did figure out it was a bad install by reinstalling the pack.
Reinstall automatically set the version to 3.6 so I didn't have to. I think
that's probably where the problem existed for me, having to update to the
new version from the first install.

Went straight to creative and tested all 5 gadgets. Had a little too much
fun with the destruction gadget. Wish there was a way to filter which
blocks don't get deleted, but it works. I know it's a direwolf mod and he
would have to be the one to talk to about it. I'm sure others have already.

Anyways, for now, that's the fix to this issue. Lost my world, but it's
worth the fix. Not like I can't find them again 😂

Thanks for taking the time to try and help figure out the original problem.
Appreciate it 🌟

**Comment by IRicTheCoder** [comment]
Since the issue as been essentially resolved, I will close it. Feel free to post a new one if you run into any more issues with the pack. Have fun!

**Comment by QahnaarinOrigin** [comment]
Didn't know how to close it. Thanks for that assist ☺️
