### ISSUE TITLE
Server file keep crashing without opening the server

### ISSUE THREAD

**Issue by DorukBey7777** [ChosenArchitect/Project-Architect-2#220]
Hi, I have an issue with the server file.

I cannot create the server it keeps crashing without opening the server and I quite don't know how to fix it.

I am going to attach the files below. I have no idea whether the issue is on my end or the server file, so I am posting it here.
If someone can help I would appreciate it.

[2024-09-11-1.log.gz](https://github.com/user-attachments/files/16961495/2024-09-11-1.log.gz)
[debug.log](https://github.com/user-attachments/files/16961497/debug.log)
[debug-1.log.gz](https://github.com/user-attachments/files/16961498/debug-1.log.gz)

**Comment by IRicTheCoder** [comment]
The server files seem to be modified or corrupted, please download the latest ones from 4.3 and make a fresh install and try again, then copy any world you had to that fresh install

If that does not work, please post back again.

**Comment by IRicTheCoder** [comment]
Did not get any feedback on this, and based on the logs the installation seemed to be bugged. Assuming that this got fixed either by an update or performing a fresh install. Closing the issue as solved, assuming so from lack of feedback. If the issue persists feel free to re-open the issue.
