### ISSUE TITLE
game crushes while loading the world

### ISSUE THREAD

**Issue by countershad-zz-ow** [ChosenArchitect/Project-Architect-2#221]
[crash-2024-09-11_10.20.09-server.txt](https://github.com/user-attachments/files/16960386/crash-2024-09-11_10.20.09-server.txt)
**Describe the bug**
->when i start the game the load percentage skip almost directly to 100% then the game crushes

**To Reproduce**
1. launch a saved file
2. 
3. 
4. 

**Expected behavior**
->

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)

**Modpack version**
->3.6
**Java Version**
->
**Modpack Launcher Used**
->forge 47.3.7
**Ram Allocated**
->

**Additional context**
->

**Comment by ChosenArchitect** [comment]
```
-- Block entity being ticked --
Details:
	Name: minecraft:hopper // net.minecraft.world.level.block.entity.HopperBlockEntity
	Block: Block{minecraft:hopper}[enabled=true,facing=north]
	Block location: World: (622,56,-349), Section: (at 14,8,3 in 38,3,-22; chunk contains blocks 608,-64,-352 to 623,319,-337), Region: (1,-1; contains chunks 32,-32 to 63,-1, blocks 512,-64,-512 to 1023,319,-1)
	Block: Block{minecraft:hopper}[enabled=true,facing=north]
	Block location: World: (622,56,-349), Section: (at 14,8,3 in 38,3,-22; chunk contains blocks 608,-64,-352 to 623,319,-337), Region: (1,-1; contains chunks 32,-32 to 63,-1, blocks 512,-64,-512 to 1023,319,-1)
```
This seems to be a vanilla hopper being ticked...
There is a quick fix for this but not sure why a Vanilla hopper would be causing this
**How to fix Ticking Entities and enable the error fixing Forge setting for 1.13 and newer, please follow these steps:**

- Navigate to your instance folder and click your world folder. In this example, my world is called my-forge-world.

- Within your world folder, click the folder called serverconfig.

- Find the file forge-server.toml and click Edit.

- Scroll down until you find the settings removeErroringEntities and removeErroringTileEntities which we've highlighted below.

Change both of the settings from false to true as shown below.

Then simply save the file and relaunch your modpack. When your pack starts, the new settings will take effect. When you next connect to your save and load the chunk with the ticking block entity, Forge will attempt to automatically remove the block which is causing issues.

Once the problem has been fixed, we recommend changing the settings back to false to prevent any issues with your world.

**Comment by IRicTheCoder** [comment]
After a week this had no feedback, assuming it was fixed and closing the issue as solved, if it is not reopen the issue. Thank You!
