### ISSUE TITLE
Game crashes when using draconic pickaxe

### ISSUE THREAD

**Issue by lomgth** [ChosenArchitect/Project-Architect-2#222]
**Describe the bug**
-> When using a draconic pickaxe with an AOE module (I was using a chaotic with the 11x11) and the excavating enchantment and mine too fast the game crashes. 

**To Reproduce**
1. Put AOE module on draconic pickaxe
2. Enchant with excavating
3. Mine as fast as possible
4. 

**Expected behavior**
-> I expected the mining radius to be 12x12 with the enchantment but it is 11x11 with a 3x3 from the enchantment. 

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)

**Modpack version**
-> 3.6
**Java Version**
-> version 8 update 421 (build 1.8.0_421-b09)
**Modpack Launcher Used**
->curseforge
**Ram Allocated**
-> 20320MB

**Additional context**
-> I added a few crash reports. Three from today all from what I believe to be the bug I'm running into. 
[crash-2024-09-11_09.59.51-server.txt](https://github.com/user-attachments/files/16966717/crash-2024-09-11_09.59.51-server.txt)
[crash-2024-09-11_12.19.25-server.txt](https://github.com/user-attachments/files/16966716/crash-2024-09-11_12.19.25-server.txt)
[crash-2024-09-11_12.29.17-server.txt](https://github.com/user-attachments/files/16966713/crash-2024-09-11_12.29.17-server.txt)

**Comment by IRicTheCoder** [comment]
Did you add any mods to the pack? Changed any configs? Also what blocks specifically have you tried to break? Always the same or different ones?

**Comment by lomgth** [comment]
No new mods or config changes. I first ran into the bug in a diamond block dim and then tried it in a test world on the redstone superflat. I can try more blocks if you'd like.

**Comment by IRicTheCoder** [comment]
The logs you have are weird as they don't point to a point specifically, more like to a broken logging instruction which doesn't seem to make sense, I would try and replicate it on my end and see if I can cause the crash

**Comment by IRicTheCoder** [comment]
I have tested this and had no issue, I will test again to ensure that I am not messing the test up. In any case please update to 4.4 and see if this still happens.

**Comment by IRicTheCoder** [comment]
I did figure out how to make the crash, and even more making it happen always. This has been fixed in 4.5 by giving back to the user a book with the excavating book if present, and removing it from the draconic tools (stating that Draconic Tools can't use that enchantment).

Closing the issue as it is fixed in the current version, in case it comes back feel free to reopen the issue.
