### ISSUE TITLE
Crash almost immediately after launch

### ISSUE THREAD

**Issue by HuneyBunn3120** [ChosenArchitect/Project-Architect-2#225]
Hello,
When I try and open the mod through Curse Forge, I get a crash message with Exit Code: 1 error almost immediately after launch. I don't know what I'm doing wrong. 

Thank you in advance,
Huney :)

**Comment by ChosenArchitect** [comment]
If you are running AMD, ensure you have all your drivers updated as this is one common cause of this issue for modpacks!

**Comment by HuneyBunn3120** [comment]
> If you are running AMD, ensure you have all your drivers updated as this is one common cause of this issue for modpacks!

All of my drivers are up to date, I am running RTX 3050 Ti. I've read about the drivers needing to be up to date. However, I'm still having the same issue. :( If you have any other ideas that would be great but thank you anyways! Love your content btw

**Comment by IRicTheCoder** [comment]
Is there any log file, pid file in the pack's folder or a crash report?

**Comment by HuneyBunn3120** [comment]
Yes, I see log files. I don't see a crash report.

**Comment by IRicTheCoder** [comment]
Send me the logs you can find that are the latest ones, I will take a look

**Comment by HuneyBunn3120** [comment]
Alright, here you go!
[latest.log](https://github.com/user-attachments/files/17168148/latest.log)

**Comment by IRicTheCoder** [comment]
On the main folder of the pack is there a .log file or something that has `pid` in its name? Cause that should pin point the issue better. Also have you tried reinstalling the pack?

**Comment by HuneyBunn3120** [comment]
Yeah, I've reinstalled it maybe 4-5 times now. You're going to have to be patient with me here, most modding I've done before Minecraft is the sims 4, this is a whole other ballpark lol. Give me a couple minutes to try and find what you are talking about.

Edit: Here is a screen shot of the mod folder. Just un and reinstalled, and tried running.
![Project Architect 2 9_28_2024 1_42_51 PM](https://github.com/user-attachments/assets/7ea88882-78af-4850-a190-6293eb2d938b)

**Comment by IRicTheCoder** [comment]
This seems to be problem more of curse forge, what is your Java version do you know? Are you using the Standalone CurseForge or the Overwolf version?

**Comment by HuneyBunn3120** [comment]
I use standalone CurseForge. I am not exactly sure what you mean by java version but on the launcher, it says v.3.1.13-2.0.16

Edit: Sorry, this has become such a hassle! I really appreciate your help though.

**Comment by IRicTheCoder** [comment]
Are you launching straight from CurseForge into game, or CurseForge opens the Minecraft Launcher?

**Comment by HuneyBunn3120** [comment]
CurseForge opens the Minecraft Launcher

**Comment by IRicTheCoder** [comment]
Then follow this to see if it will fix it:

![image](https://github.com/user-attachments/assets/46217a3d-44b4-4884-8af7-97a42d2b2030)
![image](https://github.com/user-attachments/assets/1cd98d22-96b0-412e-a68f-03ce502a7698)

Then get back to us on this, if it did or not

**Comment by HuneyBunn3120** [comment]
That did the trick! Thank you, guys!

**Comment by IRicTheCoder** [comment]
Glad it fixed it, have fun and I hope you enjoy the pack! Closing the issue as solved
