### ISSUE TITLE
Blackstone Furnace from Nether's Delight and Quark have the same recipe

### ISSUE THREAD

**Issue by mhord** [ChosenArchitect/Project-Architect-2#226]
Because of this, the induction smelter recipe can't be accessed, as the game makes a Nether's Delight furnace instead of a Quark furnace.

To reproduce, try making a Quark Blackstone Furnace.

Version 3.6.

**Comment by IRicTheCoder** [comment]
There should be an icon with 2 arrows in a circle, if you press that you can change the outcome of the recipe. Unless you are making the recipe in a crafting table the mod does not support, and so the icon wouldn't appear.

This is from a mod that allows you to pick the outcome of a recipe when certain recipes collide as it is hard to fix all recipes.
