### ISSUE TITLE
Ok, own up.. who ate the infued alloy recipe

### ISSUE THREAD

**Issue by Beckydog** [ChosenArchitect/Project-Architect-2#228]
**Describe the bug**
-> Infused alloy recipe was in pack, now? isn't. Possible gremlins.

**To Reproduce**
1. Go to autocraft Item requiring infused alloy
2. Wonder why it's taking so long
3. Go check machine.
4. It's sitting there dumbly.

**Expected behavior**
->Insert iron and redstone.,
Receive bacon. or Infused alloy. Much prefering alloy. no bacon.

**Modpack version**
->4.0
**Java Version**
->
**Modpack Launcher Used**
->Curseforge travesty
**Ram Allocated**
->8 ish gig

**Additional context**
-> Seriously,. no bacon. please. that autocraft setup is delicate enough as it is :P

**Comment by XenonsTech** [comment]
The Redstone won't input correctly if you try to handle both the extra and the input on the same side. Instead, you should use an export bus or a similar mechanism to import to a different side and then set that side to "Extra".

**Comment by IRicTheCoder** [comment]
Like mentioned above you can only input the redstone dust and such using the Extra slot not the normal input one. That should fix your issue, if not please let us know.

**Comment by IRicTheCoder** [comment]
There has been no new feedback on this to know if it has been fixed or not. A solution was provided, and with no feedback will assume it got fixed. 

For note, JEI is also in Beta in 1.20.1 and onwards so sometimes recipes don't appear on JEI, which wasn't the case here per say but just leaving the information here.

Closing the issue, reopen if the issue still seems to presist. Thanks!
