### ISSUE TITLE
Crash when adding filter to LaserIO Tag filter

### ISSUE THREAD

**Issue by iTuroQQ** [ChosenArchitect/Project-Architect-2#229]
**Describe the bug**
Might be a LaserIO bug, will be reporting the problem there too. I have a mobfarm and to filter the items I'm using LaserIO to sort them into EMCable / Tools and Armor. If I add forge:armor to the Tag Filter by LaserIO it immediatly crashes to desktop.
**To Reproduce**
1. Place LaserNode
2. add Item Card
3. add Tag Filter
4.1 type forge:armor in the Add Tag line.
4.2 OR place a armor piece in the top right filter slot to choose from its attributes.
5. Crash

**Expected behavior**
->The filter to be added

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)

**Modpack version**
->Project Architect 2 - 4.0 as of 16th September
**Java Version**
->"Recommended"
**Modpack Launcher Used**
->FTB App
**Ram Allocated**
->16GB 

**Additional context**
->
Auto-Generated Crash report
[crash-2024-09-16_18.22.47-client.txt](https://github.com/user-attachments/files/17016827/crash-2024-09-16_18.22.47-client.txt)

**Comment by IRicTheCoder** [comment]
Its an issue with the Trimmable Tools, this is fixed in 4.2+ so I suggest you update to 4.3 to get also the latest changes and fixes, thank you! Closing this as it is fixed in the latest version.
