### ISSUE TITLE
Villager still trade Shimmer enchant book

### ISSUE THREAD

**Issue by JGaming-7945** [ChosenArchitect/Project-Architect-2#23]
**Describe the bug**
->Villagers still trade the disable book of shimmer

**To Reproduce**
N/A

**Expected behavior**
->N/A

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)
![image](https://github.com/user-attachments/assets/b934c74a-1ced-4b8e-9a68-d01115dee34a)

**Modpack version**
->2.4
**Java Version**
->17
**Modpack Launcher Used**
->CursedForge
**Ram Allocated**
->10gb

**Additional context**
->

**Comment by ChosenArchitect** [comment]
Still not sure what needs to be changed to remove this... it seems like a enchant that just adds the glint to things

**Comment by James103** [comment]
If you purchase the trade shown above then run `/data get entity @s SelectedItem` or `/kubejs hand` while holding the book, or alternatively run `/data get entity` on the villager selling the Shimmer book, what do you get?
