### ISSUE TITLE
new industrial forgoing addon recipes not autocrafting

### ISSUE THREAD

**Issue by StargodGoku** [ChosenArchitect/Project-Architect-2#231]
**Describe the bug**
->i am trying to autocraft new more Industrial forgoing addons tier 3 and 4 upgrades. they are not registering lower tier upgrades that are required as learned in system. (for example tier 2 speed upgrade is needed to make tier 3 speed upgrade)

**To Reproduce**
1. learned all patterns required for addon speed tier 3 and tier 4 in AE2 autocrafting setup
2. attempt to autocraft addon speed 4 it fails saying its missing tier 3 recipe
3. attempt to autocraft addoon speed tier 3 it fails saying it doesnt have tier 2 recipe
4.crafted a addon speed tier 2 and put it into the system to see if autocraft would accept but it still failed
5. crafted the addons manually after double checking all recipes

**Expected behavior**
->i expected to be able to teach my AE2 systam all the crafts and all the patterns in appropiate providers and being able to craft them on deman with autocrafting

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)

**Modpack version**
->4.0
**Java Version**
->1.20.1
**Modpack Launcher Used**
->curseforge
**Ram Allocated**
->8 gigs

**Additional context**
->

**Comment by Demsli** [comment]
When hitting + in JEI it adds a phantom item, which is not craftable. The solution: clear the Pattern Terminal of the phantom upgrade and add it back again from JEI Search. Dragging it from JEI Search adds the upgrade that exists, which is shown with a plus sign in the pattern terminal (if you have autocrafts for the Tier 2 upgrades). But agree, this is a bug with the recipe. But before the fix you can use my method and it will work

**Comment by IRicTheCoder** [comment]
That is not a bug with the recipes it is the fact that AE2 does not work right with NBTs when it is supposed to Ignore them based on the recipe, so it is an AE2 bug. The solution above does fix it, as I also figured this out in testing.

**Comment by StargodGoku** [comment]
this fix the issue thank you loads

**Comment by Demsli** [comment]
> That is not a bug with the recipes it is the fact that AE2 does not work right with NBTs when it is supposed to Ignore them based on the recipe, so it is an AE2 bug. The solution above does fix it, as I also figured this out in testing.

Same issue in Refined Storage. Maybe it's JEI problem? For example click on "Addon Efficiency Tier 3". There you'll see the Tier 2 addon required for the craft. When clicking on Tier 2 Addon inside the recipe for tier 3 - nothing happens. It doesnt show the recipe for Tier 2
