### ISSUE TITLE
Refined Storage needs n philosopher's stones to auto-craft n items with one

### ISSUE THREAD

**Issue by F1r3w477** [ChosenArchitect/Project-Architect-2#233]
**Describe the bug**
-> In Refined Storage auto crafting, the system requires one Philosopher's Stone for each use, even though the same stone can be reused. For example, if you try to craft 100 alchemical coal, it demands 100 Philosopher's Stones, instead of just one.

**To Reproduce**
1. Set up auto crafting for something that requires the philosophers stone (e.g. Alchemical Coal) 
2. Request a quantity higher than 1

**Expected behavior**
-> Since the item is re-usable, I'd expect it to only require the 1, since there is no durability

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)
![image](https://github.com/user-attachments/assets/0bff0ba1-353e-4fda-a1ee-b3b9b72946e5)

**Modpack version**
-> 4.0
**Java Version**
-> 21 
**Modpack Launcher Used**
-> Curseforge
**Ram Allocated**
-> 
![image](https://github.com/user-attachments/assets/f70aabd8-f5f5-4d37-bc18-988b7b8d5719)

**Additional context**
->

**Comment by F1r3w477** [comment]
![image](https://github.com/user-attachments/assets/02a4b0d6-ed93-4b02-beb6-e37ba03ccb18)
An example of how absurd it can get.

**Comment by Demsli** [comment]
Autocrafting in Refined Storage does not support reusable items. It is recommended to use an external crafter for such items, with the RFTools "Crafter" being the most often used. - straight out of RS discord channel:)

**Comment by F1r3w477** [comment]
Sounds good, thanks. Will close this.
