### ISSUE TITLE
Updating multiplayer server to 4.1 causes the terminal to spam [Server thread/ERROR] [KubeJS Server/] errors

### ISSUE THREAD

**Issue by LevyWilson** [ChosenArchitect/Project-Architect-2#235]
**Describe the bug**
Server starts fine, then the terminal is inundated with a huge spam of these [Server thread/ERROR] [KubeJS Server/] errors
->

**To Reproduce**
1. Updated from 4.0 to 4.1

**Expected behavior**
->

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)

**Modpack version**
-> 4.1
**Java Version**
-> Java 17 OpenJDK
**Modpack Launcher Used**
-> Crafty on Linux
**Ram Allocated**
-> 4-8

**Additional context**
-> Server is run behind a Velocity proxy and has 5 extra mods installed with it. Bungeeforge, Proxy Compatible Forge, mc2Discord, Observable, and Performant. Server ran fine up until 4.1 update. Now even reverting the mods and configs back to 4.0, the world won't load. Have to completely revert the instance to a backup.

[debug.log](https://github.com/user-attachments/files/17039812/debug.log)

[latest.log](https://github.com/user-attachments/files/17039807/latest.log)

**Comment by IRicTheCoder** [comment]
We are aware of this error and currently working on a fix for it, sorry for the inconvenience.

**Comment by DiggityMan420** [comment]
logs 
[newest.log](https://github.com/user-attachments/files/17045109/newest.log)
[server.log](https://github.com/user-attachments/files/17045110/server.log)
 same huge list of errors hope these logs help some

**Comment by IRicTheCoder** [comment]
> logs [newest.log](https://github.com/user-attachments/files/17045109/newest.log) [server.log](https://github.com/user-attachments/files/17045110/server.log) same huge list of errors hope these logs help some

As mentioned above, we are aware of this, and a fix has been made, the hotfix will be deployed as soon as possible.

If you want to fix it before that, extract this [hotfix.zip](https://github.com/user-attachments/files/17045489/hotfix.zip) in the server/client folder and say yes to replacing the files.

That will take care of the issue.

**Comment by Paddy91088** [comment]
Same Problem here , Server Errors begin to start when I try to log in. First try it causes Server crash. Second try i can join, but endless Error loop. 


[18.09.24 latest.txt](https://github.com/user-attachments/files/17045562/18.09.24.latest.txt)
[crash-2024-09-18_15.59.09-server.txt](https://github.com/user-attachments/files/17045564/crash-2024-09-18_15.59.09-server.txt)

**Comment by Paddy91088** [comment]
Fix Works ! Error Loop has stopped ! Nice ! :)

**Comment by LevyWilson** [comment]
Can confirm, 4.2 fixed my issue. ☺

**Comment by IRicTheCoder** [comment]
Since this is fixed, I will be closing the issue, feel free to reopen if needed
