### ISSUE TITLE
Damage-immunity items don't prevent lethal damage

### ISSUE THREAD

**Issue by Cibernet83** [ChosenArchitect/Project-Architect-2#236]
**Describe the bug**
->Some enchantments and Items (most notably those added by Cyclic) that grant immunity to a specific type of damage do not appear to protect the player against lethal damage

**To Reproduce**
1. Equip Cyclic's Silkweave Slippers
2. Jump from a high enough distance to be considered lethal. Without armor or health upgrades, 24 blocks should do.
3. Wait until your player hits the ground, and notice that the Slippers did not prevent you from dying.

**Expected behavior**
->The player shouldn't die when taking damage from a source they're immune against, such as fall damage when wearing Silkweave Slippers

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)
![ProjectArchitect22024-09-1816-37-55-ezgif com-video-to-gif-converter](https://github.com/user-attachments/assets/874600dd-d4ba-4e36-a103-eca150669d8c)

**Modpack version**
->4.0
**Java Version**
->Java 17
**Modpack Launcher Used**
->Modrinth, imported from CurseForge
**Ram Allocated**
->6016MB

**Additional context**
->This doesn't happen when Cyclic is installed on its own, nor does it seem to affect Reliquary's Angelic Feather, perhaps it could be due to it canceling `LivingAttackEvent` rather than `LivingDamageEvent` like the Cyclic curios do. There might be a mod in the pack messing with player damage, forcing the player to die under certain conditions, which might also explain why the death message gets swapped out by a generic one as seen in the gif above.

**Comment by IRicTheCoder** [comment]
Please update to 4.2 and try again, I have an idea of what causes this, and it should not really happen anymore

**Comment by Cibernet83** [comment]
It works, thank you!
If you don't mind me asking, do you know what the issue was?

**Comment by IRicTheCoder** [comment]
> It works, thank you! If you don't mind me asking, do you know what the issue was?

A script I made, I left a condition out and so it was validating everything, even the player. Now it should not be an issue anymore.
