### ISSUE TITLE
Game crashes when selecting Tier 1 "Amplify" glyph for crafting

### ISSUE THREAD

**Issue by tekulvw** [ChosenArchitect/Project-Architect-2#238]
**Describe the bug**
In v4.0, if I left click on the amplify tier 1 glyph to select it for crafting, my client crashes. I've got a Mage's Spell book.

**To Reproduce**
1. Get Mage's Spell book
2. Get Scribe's table
3. Left click on T1 Amplify
4. 

**Expected behavior**
Game shouldn't crash.

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)

**Modpack version**
-> 4.0
**Java Version**
-> 17.0.8
**Modpack Launcher Used**
->ATLauncher
**Ram Allocated**
->8192

**Additional context**
->

**Comment by ChosenArchitect** [comment]
Did you try doing this on the 4.2 version?

**Comment by tekulvw** [comment]
No longer present on 4.2!
