### ISSUE TITLE
Why stacks of 16

### ISSUE THREAD

**Issue by JGaming-7945** [ChosenArchitect/Project-Architect-2#24]
**Is your feature request related to a problem? Please describe.**
->I get mad at some of the stack sizes with vanilla item like signs, pearls and soup.

**Describe the solution you'd like**
->I would like for you to and the mod "Why Stacks of 16" 

**Describe alternatives you've considered**
->N/A

**Mod Sugestions**
->Why Stacks of 16

**Additional context**
->N/A

**Comment by ChosenArchitect** [comment]
Added it :D
