### ISSUE TITLE
Lost all my inventory items

### ISSUE THREAD

**Issue by PelirrojX** [ChosenArchitect/Project-Architect-2#242]
**Describe the bug**
->I clicked the button on the right side of the inventory screen (the arrow pointing down with the horizontal lines) and all my inventory items dissapeared

**To Reproduce**
1. Open inventory
2. click arrow
3. ...
4. profit! your items are gone!

**Expected behavior**
->Don't know. First time clicking the arrow thingy.

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)

**Modpack version**
->4.2
**Java Version**
->don't know
**Modpack Launcher Used**
->Curseforge
**Ram Allocated**
->8ish GB

**Additional context**
->This may *not* be a bug but for the life of me I cannot get my items back and I'm very sad :-(

**Comment by IRicTheCoder** [comment]
Did you have the LaserIO interface opened? This happens only on that interface, and unfortunately we haven't found a fix for it. It is a bug between Inventory Tweaks which adds the button to sort your inventory, and LaserIO.

Any LaserIO GUI causes that.

**Comment by PelirrojX** [comment]
Well... that's exactly what happened then. I was actually tweaking the laser color from LaserIO config. So I guess old time pouch is gooone.

Thank you for your help :-)

**Comment by IRicTheCoder** [comment]
Unfortunately that is not something we can fix, we also haven't found out what in both mods interaction causes such a thing, will keep this open as a bug so we know to look into it again

**Comment by IRicTheCoder** [comment]
After a few attempts at fixing this, we concluded that it is not fixable on our end, this has been reported before to LaserIO's github, so we will have to wait for a fix. Closing the issue as can't fix.

**Comment by ChosenArchitect** [comment]
You can always load a backup and it happens every 30 minutes. This is one way to get all your items back! Backups should be in the simple backups folder.
