### ISSUE TITLE
Is the thermal induction smelter invar recipe meant to be replaced?

### ISSUE THREAD

**Issue by Ryno1278** [ChosenArchitect/Project-Architect-2#25]
**Is your feature request related to a problem? Please describe.**
->I noticed there was no recipe for invar in the induction smelter I was frustrated by this so I went in the modpack folder to add my own recipe for invar in the` kubejs/data/thermal\recipes\machines\smelter` folder, then I saw there was already a recipe called `"smelter_alloy_invar.json"` . When I clicked on it I saw it wasn't a recipe for invar but rather `"kubejs:archimorph"` so I didn't know if it was intentional to replace/remove the invar recipe by naming the file to `"smelter_alloy_invar.json"` if so I don't know why but nonetheless great modpack!

**Describe the solution you'd like**
->Add back the invar recipe.

**Describe alternatives you've considered**
->none

**Mod Sugestions**
->none

**Additional context**
->

**Comment by ChosenArchitect** [comment]
This is a mistake... Forgot to rename the json but will fix!
