### ISSUE TITLE
Do not heal an Iron Golem

### ISSUE THREAD

**Issue by mitchngwen** [ChosenArchitect/Project-Architect-2#251]
Healing an Iron Golem crashes the server and destroys a datapack or some sort of configuration, because it crashes after starting the server again. Not going to upload logs I already deleted the server and started over. I just though you would like to know.

**Comment by ChosenArchitect** [comment]
Not having logs and not knowing what version you are on isn't very helpful for potentially testing and fixing this issue, but we can test in the latest version and see if there is an issue caused by healing Iron Golems.

**Comment by mitchngwen** [comment]
This is not at all an issue. This was my fault, I ran out of HDD space. Sorry
My son just happened to heal an Iron Golem when this happened and we though that was the issue. It was not until I deleted the whole server and started over that I figured out that I was out of HDD space. Great modpack BTW! Thank you.
