### ISSUE TITLE
Atomic Disassembler and Malachite Ore bug

### ISSUE THREAD

**Issue by Supergod99** [ChosenArchitect/Project-Architect-2#253]
**Describe the bug**
-> Using Atomic Disassembler on Malachite Ore from Enlightened mod does not yield any drops. Using any other pickaxe, even a  simple osmium pickaxe, will yield the correct drops

**To Reproduce**
1. Obtain Atomic Disassembler
2. Find Malachite Ore in End Dimension
3. Mine it
4. Obtain 0 drops

**Expected behavior**
-> You should obtain Malachite 

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)

**Modpack version**
-> 4.5
**Java Version**
-> Java 17
**Modpack Launcher Used**
-> Curseforge
**Ram Allocated**
-> 8gb

**Additional context**
->

**Comment by IRicTheCoder** [comment]
That has been fixed in the next update, it is a known issue, there was a fix but did not work fully, now it does. When the update comes out it will be fixed

**Comment by Supergod99** [comment]
Still not working as of 4.5

**Comment by IRicTheCoder** [comment]
You are correct, this is however not an issue of the fix or anything else, its with the actual Disassembler which I did not notice. It does not have the tags for what it can "break" so it does not get detected by the fix. Thank you for reporting back, this helps finding these outliers and fix them.

**Comment by IRicTheCoder** [comment]
You can extract this zip into `kubejs/server_scripts/pa2_extras` and replace the one there, it should allow for the disassembler to work now.

[tags_mapper.zip](https://github.com/user-attachments/files/17214335/tags_mapper.zip)

These outliers that I could find should be also fixed in the next update, thank you for the feedback

**Comment by Supergod99** [comment]
No problem, appreciate your work on the pack!

**Comment by IRicTheCoder** [comment]
If you can please confirm the script above fixes it for you, so we know that in a "real case scenario" it does work, I would appreciate that :)

**Comment by Supergod99** [comment]
Fixed sorry for late reply

**Comment by IRicTheCoder** [comment]
Thank you, closing the issue as solved then!
