### ISSUE TITLE
Add tutorial on how to find the stronghold portal into the quest book.

### ISSUE THREAD

**Issue by andrewccard** [ChosenArchitect/Project-Architect-2#26]
**Is your feature request related to a problem? Please describe.**
The most common question ive seen in the discord is "where is the portal, ive been in here for hours and havent found it"

**Describe the solution you'd like**
A short description, (or just a video link showing how to find it) in the quest for going to the end.

**Comment by ChosenArchitect** [comment]
I added a riddle in the quest rewards and added a new quest!
