### ISSUE TITLE
mod suggestion to solve the problem of having too many enchantments

### ISSUE THREAD

**Issue by RConTRS** [ChosenArchitect/Project-Architect-2#260]
**Is your feature request related to a problem? Please describe.**
->

**Describe the solution you'd like**
->

**Describe alternatives you've considered**
->

**Mod Suggestions**
->enchanting infuser

**Additional context**
->this is a well crafted pack! just the logo is enough to prove that. but as other packs there are so many enchantments and it's very difficult to get the enchantments you want especially in end game, so my suggestion is to have the enchanting infuser mod, a must have mod im fond of since it released, other packs seems to include it as well so why not? but i also respect your opinions, im not always right however.

**Comment by IRicTheCoder** [comment]
You have the Library of Alexandria (and others, from apotheosis) that allows you to do essentially that, after loading enchant books into it you can then add an item and select whatever enchant you want to place on your item.

Further more, you have an altar in The Bumblezone (which I don't remember the name right now), that allows you to select the enchantment and level you specifically want, and get it in exchange of honey.

Those would essentially provide the same functionality as the Enchanting Infuser. The pack is currently fully development only bugs and such are being fixed, I don't think this would add enough of Quality of Life to justify adding it into the pack at this point in time.

**Comment by RConTRS** [comment]
right, apotheosis has pretty much what i needed. closing the issue
