### ISSUE TITLE
Cannot complete Contain the Chaos

### ISSUE THREAD

**Issue by gem45of99** [ChosenArchitect/Project-Architect-2#268]
**Describe the bug**
-> The "Contain the Chaos" quest does not take the item when the containment jar containing the Chaos Guardian is submitted. I tried through the quest and piping it to a Task Screen.

**To Reproduce**
1. Capture the Chaos Guardian in a Containment Jar
2. 
- Option 1: Open "Contain the Chaos" quest in quest book. Click the containment jar. Click Submit.
- Option 2: Put down a Task Screen. Select the Contain the Chaos" quest for the task screen. Put containment jar in chest. Using a pipe try to pipe from the chest to the Task Screen.
3. Observe that the jar is not submitted and the  quest does not complete. 

**Expected behavior**
-> The containment jar is submitted and the quest completes.

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)

**Modpack version**
-> 4,6 and 4.7
**Java Version**
->
**Modpack Launcher Used**
-> FTB App
**Ram Allocated**
-> 10GB

**Additional context**
->

**Comment by gem45of99** [comment]
I just tried completing the Dimensional Slayer quest, and it is not detecting the containment jars for the blobs in my inventory also.

**Comment by sdf356** [comment]
I also can't get this to submit.

**Comment by ChosenArchitect** [comment]
This might be from our nbt quest change. I might need to turn this back off and just leave it be.

**Comment by ChosenArchitect** [comment]
Should be fixed in next update
