### ISSUE TITLE
sophisticated storage in transmutation table, no emc

### ISSUE THREAD

**Issue by LoveElisaKiss** [ChosenArchitect/Project-Architect-2#27]
You can put a sophisticated storage oak chest into the transmutation table, it has no EMC value and i cant get it back out

1. get a oak chest (sophisticated storage
2. shift+left click it into a transmutation table
3. try to get it out (left click)
4. it doesn't work

**Expected behavior**
->either the table wouldnt accept it or i could get it back out.

**Screenshots**
![image](https://github.com/user-attachments/assets/084c28ca-0265-49b5-90c8-54931a7c71c2)

**Modpack version**
->2.4
**Java Version**
->version 8 update 361
**Modpack Launcher Used**
->curseforge
**Ram Allocated**
->8448MB

**Additional context**
->I am playing with someone else using essential

**Comment by ChosenArchitect** [comment]
you can unlearn it with another chest but I will see if I can get this to happen on my end

**Comment by ChosenArchitect** [comment]
This might have be an effect from prior learning before emc was removed and you can fix this be unlearning the chest with another chest!
