### ISSUE TITLE
Can't craft "sticky balls" from Thermal extra

### ISSUE THREAD

**Issue by R1ckyP4pa** [ChosenArchitect/Project-Architect-2#278]
->I cant craft the sticky balls from the fractionating still, i also didnt have the recipe with JEI, once i click or press R it does nothing
please help

**Modpack version**
->Latest, 4.8
**Java Version**
->1.8
**Modpack Launcher Used**
->Curseforge
**Ram Allocated**
->7200

**Comment by ChosenArchitect** [comment]
Did you update any mods? If you did update the thermal extras mod it will break the recipes as they made a huge change to the mod and is the reason I didn't update the mod.

**Comment by R1ckyP4pa** [comment]
yeah i do, i need to reinstall the mpack?
