### ISSUE TITLE
Schematic and schematicannon recipe not showing up

### ISSUE THREAD

**Issue by Justmoonboy** [ChosenArchitect/Project-Architect-2#28]
I dont know if this is intentional or not but the schematicannon and the schematic do not show up in JEI but they still work

Just look for the schematicannon or schematic in JEI and it wont show up

I expected them to show up

**Modpack version**
-> version 2.5
**Modpack Launcher Used**
-> Curseforge
**Ram Allocated**
->12768MB

**Comment by ChosenArchitect** [comment]
![image](https://github.com/user-attachments/assets/e6946bee-ebec-42bb-ad20-4e988ae56e4f)
![image](https://github.com/user-attachments/assets/59b0218f-d29c-4181-805b-bc42ebda9f19)
Both are showing up in JEI for me in my dev build?
