### ISSUE TITLE
Blocked Tabs for Side Config in Mekanism Machines

### ISSUE THREAD

**Issue by TrueEthymith** [ChosenArchitect/Project-Architect-2#282]
**Describe the bug**
->The menu to switch the type of object I/O being configurated doesn't show in screen in the side config for Mekanism machines.

**To Reproduce**
1.  Play on v2.8 of Project Architect 2
2.  Place a machine down from Mekanism such as an Enrichment Chamber 
3.  Click the "Side Config" button to the top-right of the GUI for the machine.
4.  Tabs go past the left-side of the screen and cannot be interacted with.

**Expected behavior**
-> I expected there to be tabs that have labels such as gasses, liquids, infusing types, energy, etc. to the left of the side config to be able to select from for the side config.

**Screenshots**
W/ JEI Overlay:
![WithJEIOverlay](https://github.com/user-attachments/assets/a56d92e2-6f16-4a83-aad7-9b11654267c2)
W/O JEI Overlay:
![WithoutJEIOverlay](https://github.com/user-attachments/assets/41eb8ba1-b069-4915-a89a-12e3fd1d6faf)
Downgrade to v2.5 of the modpack:
![DowngradedVersion](https://github.com/user-attachments/assets/a3a3986a-fd3d-4cf7-af6a-68f54928e9c3)

**Modpack version**
-> 2.8
**Java Version**
-> 17.0.8 64bit
**Modpack Launcher Used**
-> Curseforge
**Ram Allocated**
-> 4 GiBs (4096 MBs)

**Additional context**
-> I am using a single-screen setup with a resolution of 2560 x 1440 (due to window size, more like 2560 x 1396). The GUI for item config should be moved farther to the right as shown in the v2.5 screenshot.

**Comment by ChosenArchitect** [comment]
You can move them buy click them and dragging them much like a window in Windows
