### ISSUE TITLE
Transmutation Interface + AE2 Can't Use Stars

### ISSUE THREAD

**Issue by ieatpaper43** [ChosenArchitect/Project-Architect-2#288]
**Describe the bug**
-> When autocrafting with AE2 and a transmutation interface connected to your network, you cannot use the Stars (from ProjectE/xpansion) as ingredients. It instead says it's missing the ingredients, even when you clearly have them in your storage.

**To Reproduce**
1. Obtain enough EMC for a Star craft, i.g. the Klein Star Omega
2. Connect a Transmutation Interface to your AE2 network
3. Encode the crafting recipe into a pattern provider in your network
4. Attempt to craft the star

**Expected behavior**
-> It should be able to use stars as ingredients.

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)

Screenshot showing I clearly have enough Klein Star Spheres to craft a Klein Star Omega:
![2024-12-09_17 13 10](https://github.com/user-attachments/assets/ffb78f67-5d9f-4dfd-aeee-ec33fdecd8b6)

Screenshot showing the autocrafting screen saying I'm missing those Klein Star Spheres:
![2024-12-09_17 13 15](https://github.com/user-attachments/assets/dc704051-f5e8-4e58-be8f-049066ecacc6)

**Modpack version**
-> 4.8
**Java Version**
-> 17
**Modpack Launcher Used**
-> Prism Launcher
**Ram Allocated**
-> 20000 MiB

**Additional context**
-> The Klein Star Omega is just an example, it seems to happen with all other stars (notably the Colossal Star Omega which is how I found it, trying to autocraft Final Stars), and only seems to happen if the ingredients are not in any other kind of storage.

**Comment by ieatpaper43** [comment]
Some more context I just found, a similar thing happens to the Alchemical Books. When an Alchemical Book is involved in a craft, it will say it is also missing. I would imagine it's related somehow.

**Comment by ChosenArchitect** [comment]
So this is in relation to JEI not having the correct nbt when shifted in. To get around this you need to make the pattern using the items you just crafted and not the ones from JEI shift clicking.

**Comment by ieatpaper43** [comment]
Could you tell me exactly what you mean? I've tried many different ways of putting it in the grid what encoding the pattern, like dragging from JEI, going to the recipe and hitting "+" in JEI, and dragging from my inventory, none of which have worked. I have experienced this with items that have NBT data, and I usually fix it by dragging it from the JEI instead of from my inventory -- but the stars don't have any NBT tags (as seen by F3+H), and again, dragging from JEI doesn't work.

**Comment by ChosenArchitect** [comment]
Ah it's the Klein stars... Did you make sure substitutions enabled is turned on?

**Comment by ieatpaper43** [comment]
That seems to have worked, thank you!
