### ISSUE TITLE
Team EMC

### ISSUE THREAD

**Issue by trashed-rat** [ChosenArchitect/Project-Architect-2#29]
**Is your feature request related to a problem? Please describe.**
->While playing with my friend we have to share items so we both have the items in our transmutation table.

**Describe the solution you'd like**
->I would like to be able to share EMC and the items learned with my teammates.

**Describe alternatives you've considered**
->N/A

**Mod Sugestions**
->Team ProjectE

**Additional context**
->This mod will remove any existing EMC progress.

**Comment by ChosenArchitect** [comment]
This would remove EMC from existing worlds
