### ISSUE TITLE
[BUG] - Typing "E" in Transmutation Table Search Bar closes UI

### ISSUE THREAD

**Issue by DizzyDJW** [ChosenArchitect/Project-Architect-2#3]
**Describe the bug**
Anytime the letter "e" is typed into the Transmutation Table's Search Bar, the ui closes.

**To Reproduce**
1. Open Transmutation Search Bar
2. Type the letter "e"
3. See Issue

**Expected behavior**
Not that

**Modpack version**
2.0
**Java Version**
17
**Modpack Launcher Used**
Prism
**Ram Allocated**
8GB

**Additional context**
N/A

**Comment by Itzbionicz** [comment]
Same thing happened with me when typing G for logs. Luckily, changing a keybind fixed it.

**Comment by DizzyDJW** [comment]
> Same thing happened with me when typing G for logs. Luckily, changing a keybind fixed it.

Sadly there is no fix for this as simple as changing a keybind, as "E" is only used to open inventory and literally nothing else.

**Comment by ChosenArchitect** [comment]
This isn't a bug. You just need to remind your hotkeys. For example remove whatever key is causing the gui to close

**Comment by DizzyDJW** [comment]
> This isn't a bug. You just need to remind your hotkeys. For example remove whatever key is causing the gui to close

OK, I'm not THAT dumb. That's the first thing I checked and wouldn't you know it, there is NO other use for the "E" key at ALL. In fact I removed the "E" key in key binds altogether and it still closed the ui when typing into into the search bar.

**Comment by DizzyDJW** [comment]
Also, for my friend it is the "G" key, even unbound, the "G" key closes the UI when he types into the transmutation tables search bar

**Comment by GamingEinstein** [comment]
For me, this only happens with Curios bound to something. And it doesn't matter what combination of keys is used, if that key is pressed at all, even if you have the text field selected in the Transmutation Table, it will close it.

This is most likely related to [this](https://github.com/TheIllusiveC4/Curios/issues/393) bug reported to Curios. The bug reporter found that they were doing an improper return statement in their text field of their modded container, so it's probably something on ProjectE's side and will need to be reported to them instead.

At least for me, unbounding Curios' Open GUI key fixes this issue. Hope this helps other people looking for a solution
