### ISSUE TITLE
Crimson Fungus glitched texture (texturepacks)

### ISSUE THREAD

**Issue by XenonsTech** [ChosenArchitect/Project-Architect-2#30]
**Describe the bug**
->Glitched texture of the Nethers "Crimson Fungus"

**To Reproduce**
1. Open game
2. Go to Nether
3. Look at Crimson Fungus

**Expected behavior**
->Remove or edit the texture pack that caused the issues

**Screenshots**
![2024-07-29_22 45 56](https://github.com/user-attachments/assets/279d5cf6-c13c-4aff-a268-0f8bcf7c50a2)
![2024-07-29_22 51 23](https://github.com/user-attachments/assets/2abe94dd-2a2b-4ceb-8b9e-38b664adf99b)
![2024-07-29_22 51 26](https://github.com/user-attachments/assets/bf8b84c6-bfda-4dd4-9a5f-7440028a05e0)

**Modpack version**
->2.5 (aka current)
**Java Version**
->Forge 1.20.1
**Modpack Launcher Used**
->Prism 8.4
**Ram Allocated**
->8064MB (Around 8GB)

**Additional context**
-> No its just the texture for crimson fungus is glitched

**Comment by ChosenArchitect** [comment]
Should be fixed in the next update!

**Comment by XenonsTech** [comment]
> Should be fixed in the next update!

thanks mate
