### ISSUE TITLE
Middle mouse button doesn't work in ae2

### ISSUE THREAD

**Issue by MrGreen09** [ChosenArchitect/Project-Architect-2#31]
**Describe the bug**
->When I press the middle button to change item quantity in an AE2 pattern, the menu doesn’t open. It also won’t auto craft items I already have in stock.

**To Reproduce**
1.Make an ae2 pattern
2.try to edit item quantity

**Expected behavior**
->Menu for changing item quantity open

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)

**Modpack version**
->2.5
**Java Version**
->1.20.1
**Modpack Launcher Used**
->Curseforge
**Ram Allocated**
->9000MB
**Additional context**
->

**Comment by shiftthedev** [comment]
have you tried scrolling instead of middle-clicking?

**Comment by ChosenArchitect** [comment]
ill see what I can do! This might be an issue with the sort mod needing to be added to the don't sort list if anything check your key binds for middle mouse and remove those

**Comment by ChosenArchitect** [comment]
fixed in next update!
