### ISSUE TITLE
Sharestone EMC value worth more than core crafting components

### ISSUE THREAD

**Issue by AKGbtw** [ChosenArchitect/Project-Architect-2#34]
**Describe the bug**
-> The EMC value of the sharestone is worth more emc than the 7 component it takes in the crafting grid.

**To Reproduce**
1. 
2. 
3. 
4. 

**Expected behavior**
-> the 7 crafting components should add up to the same value of the sharestone's EMC value.

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)

**Modpack version**
->
**Java Version**
->
**Modpack Launcher Used**
->
**Ram Allocated**
->

**Additional context**
->

**Comment by ChosenArchitect** [comment]
fixed in the next update! Thanks for the report :D
