### ISSUE TITLE
EMC Automation

### ISSUE THREAD

**Issue by Dgjhadimi** [ChosenArchitect/Project-Architect-2#35]
**Describe the bug**
->EMC automation mod items set as missing item name “kubejs:archimeat”

**To Reproduce**
1. 
2. 
3. 
4. 

**Expected behavior**
->I expected to be able to do the quests

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)

**Modpack version**
->2.6
**Java Version**
->1.20.1
**Modpack Launcher Used**
->curseforge
![image](https://github.com/user-attachments/assets/5a4103df-1128-4b63-8dfd-4ef58fa836b6)
![image](https://github.com/user-attachments/assets/3f7b2e0d-ddb9-4b44-a575-0d3c4f8a2f51)

**Ram Allocated**
->

**Additional context**
->

**Comment by shiftthedev** [comment]
it seems that your instance didn't update correctly

**Comment by Dgjhadimi** [comment]
> it seems that your instance didn't update correctly

How would I fix that

**Comment by shiftthedev** [comment]
try re-download the pack

**Comment by Dgjhadimi** [comment]
How would I fix itSent from my iPhoneOn Jul 30, 2024, at 17:05, ShiftTheDev ***@***.***> wrote:﻿
it seems that your instance didn't update correctly

**Comment by ChosenArchitect** [comment]
This should be fixed with a redownload as something was removed or didn't download the KubeJS folder as that is needed for the modpack

**Comment by Dgjhadimi** [comment]
> This should be fixed with a redownload as something was removed or didn't download the KubeJS folder as that is needed for the modpack

I’ll test this out and hope this works because I’m loving this modpack
