### ISSUE TITLE
maybe a bug  Source blocks used in framed Items

### ISSUE THREAD

**Issue by DiggityMan420** [ChosenArchitect/Project-Architect-2#36]
**Describe the bug**
-> trying top use a source Block (made with 4  source gem)  work in a any gramed block item

**To Reproduce**
1. take 4 source gems craft to cube
2.try and place source cube in a framed item

**Expected behavior**
-> framed item takes on items intended to be replaced with

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)

**Modpack version**
-> 2.6
**Java Version**
->17.0.8 64bit
**Modpack Launcher Used**
->curseforge

**Ram Allocated**
-> 10gb this pack seem to run high

**Additional context**
-> see images also if  its not a bug can this be a suggestion  instead
![Screenshot_39](https://github.com/user-attachments/assets/01ff731d-de43-49a6-94eb-ed119675d955)

**Comment by shiftthedev** [comment]
seems to be an issue with FramedBlocks.
for now you can use Copycat Block

**Comment by ChosenArchitect** [comment]
Its a transparent block and some blocks just don't work in the Framed Blocks

**Comment by DiggityMan420** [comment]
thanks
