### ISSUE TITLE
Framed Drawers (1x1, 1x2 and 2x2) still have EMC-values

### ISSUE THREAD

**Issue by Bodadis** [ChosenArchitect/Project-Architect-2#37]
**Describe the bug**
-> All 3 Framed Drawers (1x1, 1x2 and 2x2) still have EMC-values even though the changelog said it was removed.

**Expected behavior**
-> Framed Drawers not having EMC-value.

**Screenshots**
![2024-07-31_01 41 50](https://github.com/user-attachments/assets/66883b30-bea1-4c75-9b2a-a18e6baee93d)

**Modpack version**
-> 2.6
**Java Version**
-> Java 17.0.8 64bit
**Modpack Launcher Used**
-> CurseForge
**Ram Allocated**
-> 10016

**Comment by ChosenArchitect** [comment]
really fixed this time lol next update!
