### ISSUE TITLE
A couple ideas

### ISSUE THREAD

**Issue by Bodadis** [ChosenArchitect/Project-Architect-2#38]
**Is your feature request related to a problem? Please describe.**
-> 1. Frustrating to craft Dielectric Paste for the Powah!-mod.
-> 2. Frustrating to search for Fallen stars in The End
-> 3. Frustrating to have a lot of Inscribers for each Print for AE2 in the early game

SOLUTION:
-> 1. Adding an extra recipe using Volcanite Amulet. (see screenshot but I missed adding the Redstone for each operation)
-> 2. Adding a recipe for the Fallen Star, perhaps using IF-laser drills or combining Nether Stars with Obsidian, Dark Matter and glass.
-> 3. Make a custom recipe for an Universal Press for Engineering, Calculation, Logic and Silicon prints.

**Describe alternatives you've considered**
-> 1. AE2 with infinite lava (using Create Hose pulley) and fluid crafting can do this easily. But this is more of an early solution.
-> 2. Well, with infinite flight you can just roam around the End quite easily so it is not a problem but it's nice to have it automated or craftable.
-> 3. Extremely easy to fix once you have autocrafting and enough resources to make subnets with Pattern Providers and Storage busses.

**Mod Suggestions**
-> KubeJS

**Additional context**
-> 1. ![Recipe for Di paste](https://github.com/user-attachments/assets/994367a7-a1b2-4fa0-a12d-6cc5ba339f59)

**Comment by Bodadis** [comment]
Forgot to mention about the Heat for Powah Thermal Generators, maybe add a higher tier than Blazing Block? :)

**Comment by ChosenArchitect** [comment]
The Universal Press was a kubejs script from ATM and there is nothing hard about doing it the normal way.
The Powah automation... am I a joke to you MEME here
![image](https://github.com/user-attachments/assets/d6cde51a-1ae9-45bb-bfc8-58d191b98f95)
and Fallen stars I want to keep the way it is as people can use the Builder or Meks Dig miner to do it as well!

**Comment by Bodadis** [comment]
I must have completely missed that recipe for Dieletric Paste, not gonna bring it up again!

I understand, and yeah it's not hard, just more convenient.

Thanks!

**Comment by Bodadis** [comment]
Any thoughts of adding Connected Glass?

**Comment by IRicTheCoder** [comment]
Due to changes to the pack, fallen stars now have a recipe. Besides that some of the things mentioned here are already available. As for the connected glass, glass has connected textures, and so a specific mod for that doesn't seem realistically needed. Closing this as added/solved.
