### ISSUE TITLE
Lantern and EMC

### ISSUE THREAD

**Issue by malac0da13** [ChosenArchitect/Project-Architect-2#4]
**Describe the bug**
->Latern says it has EMC when it is placed in world but when mined it says it has none and can not be added to transmutation table.

**To Reproduce**
1. place lantern in world see it has EMC
2. Mine it and try and put it in transmutation table
3. 
4. 

**Expected behavior**
->

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)

**Modpack version**
->
**Java Version**
->
**Modpack Launcher Used**
->
**Ram Allocated**
->

**Additional context**
->

**Comment by ChosenArchitect** [comment]
This is a visual bug with Jade and projecte I tested and tested but could not find a reason why it does this It also does it for nether portal frames
