### ISSUE TITLE
Sophisticated Barrel XRay

### ISSUE THREAD

**Issue by flaxicon** [ChosenArchitect/Project-Architect-2#43]
**Describe the bug**
->You can craft a sophisticated barrel that lets you see through the world.

**To Reproduce**
1.  Craft a sophisticated barrel
2.  take crafted barrel and craft again with redstone torch(probably works with other items) to the right of it
3.  repeat step 2 until barrel looks like 3 redstone torches
4. Place block

**Expected behavior**
->a barrel that doesn't pierce the veil of reality

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)
![image](https://github.com/user-attachments/assets/1174aa73-29bf-4e21-af93-b2d186561bfb)

**Modpack version**
->2-2.6
**Java Version**
->1.20.1
**Modpack Launcher Used**
->Curseforge
**Ram Allocated**
->4gb

**Additional context**
->

**Comment by ChosenArchitect** [comment]
nothing I can do about this but also kinda lame lol There are a lot of ways even in vanilla Minecraft to do this and all it lets you do it see caves kinda
