### ISSUE TITLE
Disable Smooth Quartz Block EMC

### ISSUE THREAD

**Issue by dannypas00** [ChosenArchitect/Project-Architect-2#44]
**Describe the bug**
-> Smooth Quartz Blocks are easily obtainable by the stack, and each block is worth 1024 EMC

**To Reproduce**
1. Go to quartz flats biome in nether
2. Vein mine as many Smooth Quartz Blocks as you feel like
3. Turn it all into EMC for millions of EMC/minute

**Expected behavior**
-> Blocks generated in the world so commonly should not have this high of an EMC value

**Screenshots**
![image](https://github.com/user-attachments/assets/81d8e042-166c-49e9-819d-069630abd9eb)  
![image](https://github.com/user-attachments/assets/c795cd92-11ae-415f-8eaf-b50b80e67483)

**Modpack version**
-> 2.6
**Java Version**
-> 17.0.9.8
**Modpack Launcher Used**
-> Prism
**Ram Allocated**
-> 12GB

**Additional context**
->Smooth Quartz Blocks currently don't have an uncrafting recipe, so I suggest simply disabling their EMC value to solve the issue.

**Comment by ChosenArchitect** [comment]
Fixed
