### ISSUE TITLE
Many 'Advanced' sophisticated backpack are missing 'native' recipe

### ISSUE THREAD

**Issue by radwadas** [ChosenArchitect/Project-Architect-2#45]
**Describe the bug**
Many of the advanced upgrades from sophisticated backpacks don't have a recipe that uses the standard upgrade. The only recipe available is by using equivalent advanced upgrade from the sophisticated storage mod.
I doubt these recipes were disabled intentionally.

**To Reproduce**
1. Try to craft advanced pickup upgrade for a backpack

**Expected behavior**
-> a recipe that uses backpack pickup upgrade is available

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)

**Modpack version**
->2.6
**Java Version**
->
**Modpack Launcher Used**
->curseforge
**Ram Allocated**
->16gb

**Additional context**
->

**Comment by ChosenArchitect** [comment]
I see both in JEI
![image](https://github.com/user-attachments/assets/6e57541f-0ce4-4d2f-bbf9-db20efd8d9fb)
Whats the issue? I do know the storage and backpacks have compact with upgrade to work with both and have conversions

**Comment by radwadas** [comment]
![image](https://github.com/user-attachments/assets/32cdb1c1-ae2f-45ae-83a9-eaea17010efd)
![image](https://github.com/user-attachments/assets/5c8b2cfe-bd0d-480a-8061-1d0bcf7cc242)
Hmm, by the looks of if, I can't craft either advanced upgrades. Something must have not loaded properly.

**Comment by ChosenArchitect** [comment]
Try updating to the 2.8 version
