### ISSUE TITLE
World stuck creating/loading

### ISSUE THREAD

**Issue by Reaper8621** [ChosenArchitect/Project-Architect-2#47]
I recently installed Project Architect 2, and have been trying to create a world. However, whenever I try to create/load a world, I get to the loading box, but then it gets stuck at 0%, and the instance stops responding

I don't know how to replicate the issue other than trying to load a world on my system

Upon at first trying to create the world, I expected the world to properly load

![image_2024-07-31_113157593](https://github.com/user-attachments/assets/1cf84dd8-5f5d-4fb8-9a2f-828a940a3f30)
![Screenshot 2024-07-31 112351](https://github.com/user-attachments/assets/d8a729b6-ce21-4dbb-b05c-4193a60fac32)

**Modpack version**
->Project Architect 2-2.7.zip

**Modpack Launcher Used**
->Forge

**Ram Allocated**
->8000MB allocated

Note: I tried a fix for a similar issue, which was to enable the error fixing Forge setting, but that didn't work

**Comment by Burikq** [comment]
same issue bro 💯 :)rofl
crash-report: https://pastebin.com/ddgz3q5i

**Comment by ChosenArchitect** [comment]
Should be fixed in the 2.8 as this was a flub with mods updating

**Comment by Darkaim63** [comment]
Will 2.8 be out sometime today?

**Comment by Reaper8621** [comment]
> Should be fixed in the 2.8 as this was a flub with mods updating

Tysm!
