### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by Enyflow** [ChosenArchitect/Project-Architect-2#48]
**Describe the bug**
->Game crashes, set 8/9/10 gb of ram allocated, no changes. This is the first modpack I have this issue, Played fine with modpacks more than 450 mods.
I join the world, play like max 10 minutes then crash.
This is crash report:
https://mclo.gs/WE7CmN4

**Modpack version**
->  2.4

**Java Version**
-> Picked up _JAVA_OPTIONS: -Xmx2048M
java version "1.8.0_231"
Java(TM) SE Runtime Environment (build 1.8.0_231-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.231-b11, mixed mode)

**Modpack Launcher Used**
-> CurseForge

**Ram Allocated**
-> 9gb

**Additional context**
-> I started playing 2 days ago, today started this issue.

**Comment by 5ully** [comment]
The crash log is common when you have too many other programs running so the system is unable to allocate enough RAM to your program. Its pretty much Java asking the system for RAM and the system saying: "No, Sorry,  I don't have anything to give".

**Comment by Enyflow** [comment]
Yes, the only program I have open is Edge with 1 pdf page

**Comment by ChosenArchitect** [comment]
Update modpack version to 2.8+
