### ISSUE TITLE
Add a backup mod

### ISSUE THREAD

**Issue by BooBooFastCat1** [ChosenArchitect/Project-Architect-2#49]
**Is your feature request related to a problem? Please describe.**
->i am having issues when i leave a sugar cane emc farm for a coulple of hours where it freezes and all i can do is close the program 

**Describe the solution you'd like**
-> i would like a backup mod that does backups automatically

**Describe alternatives you've considered**
-> i am not sure as i am unsure what the actual problem is

**Mod Sugestions**
->FTB Backups 2

**Additional context**
->

**Comment by MelanX** [comment]
Another suggestion: Simple Backups

**Comment by ChosenArchitect** [comment]
I need to add a backup mod... will do next update!
