### ISSUE TITLE
Remove client-only mods from server pack

### ISSUE THREAD

**Issue by TheInfamousAlk** [ChosenArchitect/Project-Architect-2#5]
The server files for Project Architect 2 2.1 (Project Architect 2 2.1 Server Files.zip) contain one or more client-side mods that need to be removed, including at least embeddium. 

`Forge: net.minecraftforge:47.3.0[18:15:49] [main/ERROR] [minecraft/Main]: Failed to start the minecraft server
net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
	Embeddium (embeddium) has failed to load correctly
������7java.lang.RuntimeException: Attempted to load class net/minecraft/client/gui/screens/Screen for invalid dist DEDICATED_SERVER
]`

There may be more, as it failed on this one and may not have gotten to any other client-only mods included in the server files. 

Thank you!

**Comment by ChosenArchitect** [comment]
This was a mistake because for some reason embed didn't show up as client on the curseforge app
