### ISSUE TITLE
server pack crash....FIXED!

### ISSUE THREAD

**Issue by Frostylooms** [ChosenArchitect/Project-Architect-2#50]
**Describe the bug**
-> i downloaded the server pack, i extracted files, click run.bat, it installs forge automatically, i sign change eula to true, run.bat again and every time it gets to world generation it crashes.  i always host servers and play on them with a friends. so not too new to this. 
 
i went ahead and had chatgpt 4

Code line 1 in screen shot

java.lang.IllegalStateException: Feature order cycle found, involved sources: [Reference{ResourceKey[minecraft:worldgen/biome / minecraft:wooded_badlands]=net.minecraft.world.level.biome.Biome@4e9c9ba7}, Reference{ResourceKey[minecraft:worldgen/biome / integrateddynamics:meneglin]=net.minecraft.world.level.biome.Biome@6bc80f8b}]

Code line 2 in screenshot 

Blueprint (blueprint), Version: 7.1.0
Issue tracker URL: https://github.com/team-abnormals/blueprint/issues
at TRANSFORMER/blueprint@7.1.0/com.teamabnormals.blueprint.common.world.modification.ModdedBiomeSlicesManager.lambda$onServerAboutToStart$3(ModdedBiomeSlicesManager.java:78)

![Screenshot 2024-07-31 143327](https://github.com/user-attachments/assets/35baf12d-0c98-4568-81df-cdcd4515cabd)

[crash-2024-07-31_13.45.43-server.txt](https://github.com/user-attachments/files/16447406/crash-2024-07-31_13.45.43-server.txt)

**Comment by shiftthedev** [comment]
what's the modpack version?

**Comment by Frostylooms** [comment]
> what's the modpack version?

the server pack files are labeled 2.7

**Comment by shiftthedev** [comment]
update to 2.8 should fix it

**Comment by Frostylooms** [comment]
> update to 2.8 should fix it

it has!! i just tested it. thank you to you or whoever may have done it! we can play!
