### ISSUE TITLE
Quark animals do not spawn.

### ISSUE THREAD

**Issue by ClaymooreEOC** [ChosenArchitect/Project-Architect-2#51]
**Describe the bug**
-> Lack of Quark crabs mean the Skillet quest in the Adventure Bound section cannot be completed.

**To Reproduce**
1. Log in
2. Look at beach
3. See no crab
4. 

**Expected behavior**
-> Look at beach. See crab. Kill crab. Cook. Win game.

**Comment by ChosenArchitect** [comment]
I have seen the crabs. The do spawn in breaches and you can also mob swab them if need be.

**Comment by ChosenArchitect** [comment]
So I did some testing and it seems the do spawn but might take some time in a BEACH biome and you will have to look for a Vanilla-type one! After doing some testing I did see this one in the beach I was in while testing some other things.
![image](https://github.com/user-attachments/assets/8302e15a-3755-4b87-a7c7-4353e86fa3d5)

**Comment by brubadue** [comment]
I've been waiting for over an hour at a vanilla beach and I have yet to see anything but coconut crabs...

**Comment by ClaymooreEOC** [comment]
> I've been waiting for over an hour at a vanilla beach and I have yet to see anything but coconut crabs...

I finally got it by flying around to even more beaches.
They have their own minimap icon so once they actually show up they are easy to find.

**Comment by brubadue** [comment]
I logged in this morning and found two of them within 5 seconds in a willow forest.
