### ISSUE TITLE
Not include JEI's client config

### ISSUE THREAD

**Issue by Zero9o1o** [ChosenArchitect/Project-Architect-2#53]
**Is your feature request related to a problem? Please describe:**
It is frustrating when modpacks include client config that are suppose to be modifiable by end user (the players), like the jei-client.ini in the config\jei folder. By shipping said configs it will overwrite any of their modifications when applying an update. 

**Describe the solution you'd like:**
Solution would be to not include said config file

**Comment by ChosenArchitect** [comment]
Ill try and remember to not add that when updating! Thanks for the issue

**Comment by IRicTheCoder** [comment]
This has been done in the newer versions of the pack so it should no longer be an issue, closing this as added.
