### ISSUE TITLE
Smelted Uraninite - Emc Dupe

### ISSUE THREAD

**Issue by MalaChaiLatte** [ChosenArchitect/Project-Architect-2#54]
**Describe the bug**
->
Smelted Uraninite has an EMC value, allowing EMC duping via the energizing orb

**Screenshots**

![Screenshot 2024-08-01 at 4 08 29 PM](https://github.com/user-attachments/assets/85c1c242-5022-4c4e-b883-77713ac2b803)

![Screenshot 2024-08-01 at 4 08 40 PM](https://github.com/user-attachments/assets/6d1acc2a-f46f-4fac-b304-dc97701903e6)

**Modpack version**
-> 2.8

**Comment by Bodadis** [comment]
If you have a RM Furnace you could probably quite easily make a infinite loop of EMC, since the RM Furnace have % to double the outcome. It looks like it's around 7500 EMC/s with this setup, but I haven't calculated the net gain though.

**Comment by ChosenArchitect** [comment]
Will fix next update! Uraninite shouldn't have emc
