### ISSUE TITLE
"Compress It!" and "Compressium" mods

### ISSUE THREAD

**Issue by monyarm** [ChosenArchitect/Project-Architect-2#55]
**Is your feature request related to a problem? Please describe.**
-> It would make the compression upgrades for the backpack even better.

**Describe the solution you'd like**
-> The mods "Compress It!" and "Compressium" each add compressed versions of various items and blocks respectively. It would be great if they could not only be supported, but also have EMC added if their components also have EMC.

**Mod Sugestions**
-> "Compress It!" and "Compressium"

**Additional context**
-> The mod "Compress It" appears to only be available on Modrinth, but it's license means you should be able to add it to your modpack anyways. I think.

**Comment by IRicTheCoder** [comment]
As of version 4.0, we have added new compression blocks, as for the mods mentioned, compress it is from Modrinth which makes it hard to add to CurseForge and keep it updated. For the Compressium mod, it didn't seem that needed, with some of the additions made by us.

Closing this as handled/solved.
