### ISSUE TITLE
Lantern missing EMC

### ISSUE THREAD

**Issue by monyarm** [ChosenArchitect/Project-Architect-2#56]
**Describe the bug**
-> Lanterns have EMC in the world, but not as items in the inventory

**To Reproduce**
1. Find a lantern
2. Break it
3. It has no EMC

**Expected behavior**
-> It either has EMC in both, or has no EMC in both.

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)

**Modpack version**
-> 2.8
**Java Version**
-> 1.17
**Modpack Launcher Used**
-> PrismLauncher
**Ram Allocated**
-> 16GB

**Additional context**
-> Linux

**Comment by shiftthedev** [comment]
its a Jade issue. nothing we can do.
