### ISSUE TITLE
/set home

### ISSUE THREAD

**Issue by Wolfepupkitten** [ChosenArchitect/Project-Architect-2#57]
**Describe the bug**
If you use /set home it works perfectly. But when I wanted to set a second home I used "/set home sky" it said home created but when I tried to tp there later it said I only had the one home. 

**To Reproduce**
Set a home then set a second home with a unique name. 

**Expected behavior**
I thought it said we could have multiple homes (I now have waystones but I still like the home feature). 

**Modpack version**
->2.8 I think? 

**Java Version**
-> umm I just download it (was a PS5 player before) so newest?

**Modpack Launcher Used**
-> courseforge 

**Ram Allocated**
->....umm un sure 

**Additional context**
This is my first modded game so I'm very new to understanding how it all works so may be a user error.

**Comment by shiftthedev** [comment]
the correct command is /sethome [name] and /home [name] (ex.: /sethome a, /sethome b)
but in the current modpack version you're only able to have 1 home.
