### ISSUE TITLE
Backpack UtilitiX Issue

### ISSUE THREAD

**Issue by Dusssk** [ChosenArchitect/Project-Architect-2#59]
**Duplication Glitch**
-> This is a duplication glitch using the backpack from the mod named UtilitiX

**To Reproduce**
1.  Aquire a backpack from the UtilitiX mod.
2. Fill them up with any item you want to duplicate.
3. Left click the button on the right side of the GUI.

**Expected behavior**
-> There will be one of two results.
1. The GUI will close whereas your inventory and hotbar will be sorted. All the items inside the backpack will be duplicated and promptly placed in to your inventory.
2.  The GUI will stay open but this time your backpack wil be duplicated in your inventory. The items inside the backpack stays intact and all the items will have been duplicated. 

**Screenshots**
![bug](https://github.com/user-attachments/assets/ba7e47e7-3e4e-4cb4-a71b-4f022a50d5c4)

**Modpack version**
-> 2.8
**Java Version**
-> Java 21
**Modpack Launcher Used**
-> Curse Forge
**Ram Allocated**
-> 8800 MB

**Additional Context**
-> This works in both singleplayer and LAN. Proper server untested.

**Comment by MelanX** [comment]
If there's a way to blacklist the menu for the sorting mod, do this for now. I'm the author of UtilitiX and need to figure out how to fix this properly.

**Comment by ChosenArchitect** [comment]
I can remove this packpack for now from crafting next update

**Comment by ChosenArchitect** [comment]
I will remove the back next update for now just don't use the back and be a GAMER :D
