### ISSUE TITLE
Book And Bookshelf EMC Issue

### ISSUE THREAD

**Issue by Itzbionicz** [ChosenArchitect/Project-Architect-2#6]
**Describe the bug**
-> Bookshelves have an EMC Level of 8 while 3 book have an EMC level of 15, so by breaking the bookshelf, you are going from 8 EMC to 15 EMC, meaning there is an EMC dupe.

**To Reproduce**
1. Get a bookshelf and put it in your Transmutation Table
2. Take out a bookshelf from the Transmutation Table
3. Place the bookshelf down and break it
4. Put your books in the Transmutation table and you have 7 extra EMC

**Expected behavior**
-> I would expect the books to be 3 EMC and then the bookshelves be increase by 1 to 9 EMC, since planks don't have an EMC value. 

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)
![image](https://github.com/user-attachments/assets/75c70be6-5a4c-4281-a543-f09ba0504d9d)
![image](https://github.com/user-attachments/assets/536db221-fe90-403c-8bf7-c349c2c5a19b)

**Modpack version**
-> Version 2.1
**Java Version**
-> 1.20.1
**Modpack Launcher Used**
-> ATLauncher
**Ram Allocated**
-> 8,000 MB

**Additional context**
-> No addition Information but Thank you! Have a good day/night!

**Comment by ChosenArchitect** [comment]
fixed in next update!
