### ISSUE TITLE
EMC for Trials Chambers Smithing Templates

### ISSUE THREAD

**Issue by monkeybug34** [ChosenArchitect/Project-Architect-2#60]
**Is your feature request related to a problem? Please describe.**
-> smithing templates are a valuable item for EMC, however the two smithing templates from the TRIALS CHAMBERS mod does not have any EMC values.

**Describe the solution you'd like**
-> add EMC values to these two templates.

**Describe alternatives you've considered**
-> 

**Mod Sugestions**
-> n/a

**Additional context**
-> I haven't actually gotten my hands on any, so I don't know how valuable/how much EMC they should be worth.

**Comment by ChosenArchitect** [comment]
Fixed next update!
