### ISSUE TITLE
add EMC to Alchemical Bags

### ISSUE THREAD

**Issue by monkeybug34** [ChosenArchitect/Project-Architect-2#61]
**Is your feature request related to a problem? Please describe.**
-> Alchemical bags act the same way as the vanilla ender chest. if you were to have 2 different 'white alchemical bag', they share the same content. this is also per-player. so if I gave you my alchemical bag that I put all my diamonds into, you would see an empty one when you open it up. (exactly like an ender chest)

**Describe the solution you'd like**
-> I think the alchemy bags should have their EMC value reinstated.

**Describe alternatives you've considered**
->

**Mod Sugestions**
-> n/a

**Additional context**
-> double checked in single player.

**Comment by ChosenArchitect** [comment]
Ill do some testing and see if I have them removed for some reason... might be what they are crafted with

**Comment by ChosenArchitect** [comment]
Fixed next update!
