### ISSUE TITLE
RFT Dimension Absorbers not working properly

### ISSUE THREAD

**Issue by KuronoKira** [ChosenArchitect/Project-Architect-2#62]
**Describe the bug**
-> The absorbers are unable to absorb various blocks and liquids

**To Reproduce**
1a. Place a bucket of brine on the floor
2a. Place a liquid absorber above the brine

1b. Place a flax bale on the floor
2b. Place a block absorber above the bale

**Expected behavior**
-> The absorber should absorb what's placed below it and fill up the progress bar

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)

**Modpack version**
-> 2.8
**Java Version**
-> 1.20.1
**Modpack Launcher Used**
-> ATLauncher
**Ram Allocated**
-> 8GB

**Additional context**
-> The blocks and fluids are listed in the dimlet workbench, so I'd expect them to be supported by the absorbers as well. Mekanism fluids are often listed as both block and fluid dimlet, but the placed fluid can't be absorbed by block absrobers nor liquid absorbers

**Comment by ChosenArchitect** [comment]
A lot of Mek fluids have been removed from RFTools Dim for balance reasons
