### ISSUE TITLE
RFToolsPower's Coal Generator render glitch

### ISSUE THREAD

**Issue by monkeybug34** [ChosenArchitect/Project-Architect-2#63]
**Describe the bug**
-> the front face of the Coal Generator from RFToolsPower renders bright red when it either contains power or is generating power. not sure which.

**To Reproduce**
1. place coal generator
2. feed it charcoal
3. 
4. 

**Expected behavior**
-> front face of the coal generator should become bright red

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)
![2024-08-02_16 58 39](https://github.com/user-attachments/assets/c8e3e6a7-cc35-4322-a2ec-0c4476469905)

**Modpack version**
->2.8

**Java Version**
-> Minecraft bundled Java version

**Modpack Launcher Used**
-> Curseforge

**Ram Allocated**
-> 8192MB (8GB)

**Additional context**
->

**Comment by IRicTheCoder** [comment]
Was unable to replicate this as of version 4.0, will assume the issue has been solved since some render related mods have been updated a few times since the version this was reported in.

Closing as solved, feel free to reopen if the issue continues.
