### ISSUE TITLE
Server Files

### ISSUE THREAD

**Issue by ProQsGamer** [ChosenArchitect/Project-Architect-2#64]
**Describe the bug**
-> The server files don't come with the forge installer so when I compress the server files into Crafty on my server computer like any other modpack and unzip and then run it gives me a error saying running wrong version of forge.

**To Reproduce**
1. Install server files
2. Compress files (7Zip)
3. Unzip files into Crafty Controller (CasaOS)
4. Start Server

**Expected behavior**
->Error with needs newer version of forge.

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)

**Modpack version**
->2.8
**Java Version**
->
**Modpack Launcher Used**
->
**Ram Allocated**
->8GB

**Additional context**
->I have tried giving the correct installer into the file and trying it that way but same thing happens. I've also tried starting the server on my own computer then putting the files to run on my local machine but same problem. Wondering if it has to do with the server files that are given. This has happened before in the early versions of ATM9 on there first release with the server files for the pack.
[PA2 crash.log](https://github.com/user-attachments/files/16477936/PA2.crash.log)
![Screenshot 2024-08-02 201945](https://github.com/user-attachments/assets/1bd2a3bd-b174-46cd-b835-66474e1a7f1f)
![Screenshot 2024-08-02 201850](https://github.com/user-attachments/assets/9e39271a-e10d-4f67-87c7-5ece2be5efd1)

**Comment by ChosenArchitect** [comment]
you need to run the custom .bat or .sh that ships with the modpack and it will auto download the forget installer

**Comment by ProQsGamer** [comment]
![Screenshot 2024-08-04 010344](https://github.com/user-attachments/assets/57babae5-5bdf-41f4-b2d3-75af7b89e942)
> you need to run the custom .bat or .sh that ships with the modpack and it will auto download the forget installer

Thank you, i had to do what you said but also had to change the server executable location from 47.2.0 to 47.3.0. for some reason it was defaulting to the older version for your pack but I got it working. Thank you!
