### ISSUE TITLE
Add a backup mod

### ISSUE THREAD

**Issue by devcraft444** [ChosenArchitect/Project-Architect-2#65]
**Is your feature request related to a problem? Please describe.**
->

**Describe the solution you'd like**
->

**Describe alternatives you've considered**
->

**Mod Sugestions**
->

**Additional context**
->

**Comment by devcraft444** [comment]
I lost 10 hours gameplay due to power cut.

**Comment by shiftthedev** [comment]
#49 duplicated
will be added in the next update
