### ISSUE TITLE
Server gets stuck preparing start region

### ISSUE THREAD

**Issue by OnTheM4rc** [ChosenArchitect/Project-Architect-2#66]
**Describe the bug**
-> Since the update to 2.8 my world from 2.4 gets stuck on Preparing start region for dimension Minecraft:overworld

**To Reproduce**
1. Just running run.bat

**Expected behavior**
->Expected to load the server and not hang on server starting

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)
![image](https://github.com/user-attachments/assets/637594a9-1f91-4a37-87cb-5e4ce0af3069)

**Modpack version**
->2.8
**Java Version**
->java 8
**Modpack Launcher Used**
->Curse Forge
**Ram Allocated**
->12GB

**Comment by shiftthedev** [comment]
this is fixed

**Comment by shiftthedev** [comment]
@ChosenArchitect this can be closed
