### ISSUE TITLE
Nether portals timing the server out.

### ISSUE THREAD

**Issue by Emrts12** [ChosenArchitect/Project-Architect-2#68]
**Describe the bug**
->When a nether portal is walked through it times out the server.

**To Reproduce**
1. Make a nether portal.
2. Walk through it.
3. Server times everyone out.
4. Start to cry.

**Expected behavior**
->I expected the portal to work as intended.

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)

**Modpack version**
->1.20
**Java Version**
->1.20
**Modpack Launcher Used**
->Cursedforge
**Ram Allocated**
->8gb

**Additional context**
->This is for the "project Architect 2" mod

**Comment by shiftthedev** [comment]
without a crash-report or any type of log we can't help

**Comment by IRicTheCoder** [comment]
It has been a month without any update on this, assuming the problem either went away or got fixed, maybe with updating the pack. Closing it as solved.
