### ISSUE TITLE
 XP tap and Experience Crystal Drop Infinite XP

### ISSUE THREAD

**Issue by Itzbionicz** [ChosenArchitect/Project-Architect-2#69]
**Describe the bug**
-> XP tap and Experience Crystal Drop Infinite XP even if the experience crystal is empty

**To Reproduce**
1. Place a Experience Crystal Down
2. Place a XP tap next to the Experience Crystal
3. Open the XP Tap and get Infinite XP

**Expected behavior**
-> Not to give xp when empty

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)
![image](https://github.com/user-attachments/assets/4115716b-89df-4a92-a6b4-f754744facaa)
![image](https://github.com/user-attachments/assets/56d3dcd2-8377-4776-b8ea-a0a514f39d7d)
![image](https://github.com/user-attachments/assets/f6894f56-35d7-4408-97ed-37cb469ee3c8)
![image](https://github.com/user-attachments/assets/9605288e-9781-4680-9623-9d9e0e36caa7)

**Modpack version**
-> 2.6
**Java Version**
-> 1.21
**Modpack Launcher Used**
-> ATLauncher
**Ram Allocated**
-> 8000 MB

**Additional context**
-> As you can see in the screenshot containing the experience crystal's gui, to the right of it, you can see the tap is still giving XP, even though the crystal is empty. It says the Experience Crystal has 2.14MB of experience but in reality, it has none.

EDIT: Added a fourth screenshot showing that there are 2 essence bars. This is a experience crystal connected to my mob EMC farm.

**Comment by ChosenArchitect** [comment]
Fixed in latest update on the mod :D
