### ISSUE TITLE
Inventory sorting bug with Iron Furnaces

### ISSUE THREAD

**Issue by Krona1** [ChosenArchitect/Project-Architect-2#7]
**Describe the bug**
->When auto-sorting inside of a Diamond Furnace, sorting also moves items from the hotbar

**To Reproduce**
1. Open diamond furnace
2. middle click to auto-sort inventory 
3. 
4. 

**Expected behavior**
-> Leave hotbar items while auto-sorting

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)

**Modpack version**
->2.0
**Java Version**
->jdk-17
**Modpack Launcher Used**
->Curse Forge
**Ram Allocated**
->10Gb

**Additional context**
->

**Comment by ChosenArchitect** [comment]
Should be fixed in next update!
