### ISSUE TITLE
Chisel Chipped lab blocks not dropping

### ISSUE THREAD

**Issue by HalJordan** [ChosenArchitect/Project-Architect-2#70]
**Describe the bug**
->
When you break these blocks, regardless of tool, nothing is dropped
**To Reproduce**
1. Make block
2. Place block
3. grab any pickaxe/dark matter hammer/etc
4. break block
5. Search endlessly to see where it went.
6. Check self into psych ward when it can't be found

**Expected behavior**
->
The block ....

should drop...

**Modpack version**
-> 2.8(was present in 2.6 as well)
**Java Version**
-> Current suggested
**Modpack Launcher Used**
-> Prism
**Ram Allocated**
-> enough

**Additional context**
->
It looks like a bug marked #wontfix and the author suggests an appropriate version of neoforge.

**Comment by shiftthedev** [comment]
can you share the mod issue link?
so i can see what was done and try to fix it

also i need to know the exact block that is not droping

**Comment by HalJordan** [comment]
https://legacy.curseforge.com/minecraft/mc-mods/chisel-chipped-integration/issues/1

```quote
This problem is fixed with neoforge 1.20.4

Versions below 1.20.4 will most likely not be fixed
```

**Comment by HalJordan** [comment]
I've not used many, pretty much entirely changed my base design after seeing that with the rusty block and it's variants..

**Comment by shiftthedev** [comment]
for now they drop if mined with vanilla tools.

**Comment by shiftthedev** [comment]
will be fixed in next updated
