### ISSUE TITLE
Enlightend ores have no EMC

### ISSUE THREAD

**Issue by R-solar** [ChosenArchitect/Project-Architect-2#71]
**Is your feature request related to a problem? Please describe.**
-> Raw ores and malachite from  enlightened_end have no EMC value, making things like "Teleporter" shenanigans  and decorating block related to them grindy

**Describe the solution you'd like**
-> add a EMC value to them according to their vanilla related rarity

**Describe alternatives you've considered**
->

**Mod Sugestions**
->

**Additional context**
->

**Comment by ChosenArchitect** [comment]
fixed next update
