### ISSUE TITLE
[Suggestion] Add Night Config Fixes

### ISSUE THREAD

**Issue by Gronglegrowth** [ChosenArchitect/Project-Architect-2#72]
**Is your feature request related to a problem? Please describe.**
At times, Forge's config system can corrupt said configs, resulting in game crashes upon trying to later read them. Fixing it necessitates deleting and regenerating the config file, which may lead to customized settings getting reset.

**Describe the solution you'd like**
I would like Night Config Fixes added to the modpack. This will regenerate the configs itself when the config corruption occurs, and has the option to regenerate them from templates placed in the /defaultconfigs/ folder meaning that customized settings are preserved.

**Mod Sugestions**
[Night Config Fixes](https://www.curseforge.com/minecraft/mc-mods/night-config-fixes) by Fusz

**Comment by IRicTheCoder** [comment]
This as been added on update 3.6, should now help with fixing some issues. Thanks for the suggestion!
