### ISSUE TITLE
Mob Drops GUI Glitch  

### ISSUE THREAD

**Issue by futureflash01** [ChosenArchitect/Project-Architect-2#73]
**Describe the bug**
->When looking at the "Legendary Dimensional Essence" from RFTools Dimensions in JEI, if you look at the 'Mob Drops' tab, the 'Legendary Blob' mob is too big and covers up the whole interface. The Common and Rare items don't have this bug.

**To Reproduce**
1. Open JEI
2. Search "Legendary Dimensional Essence"
3. Click the searched item
4. Open the 'Mob Drops' tab

**Expected behavior**
->the Legendary Blob mob should be of correct size and fit in its interface. It makes the surrounding information unreadable

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)
![image](https://github.com/user-attachments/assets/68d5244a-068e-409a-8d63-1806f1779fab)

**Modpack version**
->2.8
**Java Version**
->1.20.1
**Modpack Launcher Used**
->CurseForge
**Ram Allocated**
->8192MB (8GB)

**Additional context**
->N/A

**Comment by ChosenArchitect** [comment]
Nothing I can do about that... This mob is just HUGE :P
