### ISSUE TITLE
Ars Creative Jar Doesn't have a drop Table 

### ISSUE THREAD

**Issue by ChosenArchitect** [ChosenArchitect/Project-Architect-2#74]
**Describe the bug**
->

**To Reproduce**
1. 
2. 
3. 
4. 

**Expected behavior**
->

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)

**Modpack version**
->
**Java Version**
->
**Modpack Launcher Used**
->
**Ram Allocated**
->

**Additional context**
->

**Comment by shiftthedev** [comment]
fixed in next update
