### ISSUE TITLE
I found another broken texture :)

### ISSUE THREAD

**Issue by XenonsTech** [ChosenArchitect/Project-Architect-2#75]
**Broken Texture**

-> The enderman head from the mod Supplementaries

1.  Get an enderman head from supplementaries
2.  look at the placed item texture
3.  look at the inventory texture

**Expected behavior**
-> Find the issue and hopefully able to fix it as supplementaries is a big mod with many features

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)
![2024-08-04_20 11 34](https://github.com/user-attachments/assets/08a48f46-7d78-41c4-96a5-f1df4ec657db)

**Modpack version**
-> Version 2.9
**Java Version**
-> 1.20.1
**Modpack Launcher Used**
-> Prism
**Ram Allocated**
-> 8 gb

**Additional context**
-> nope

**Comment by shiftthedev** [comment]
will be fixed in next update.
for now you can disable Better Enderman resource pack
