### ISSUE TITLE
Broken chest texture ( I think )

### ISSUE THREAD

**Issue by XenonsTech** [ChosenArchitect/Project-Architect-2#76]
**Describe the bug**
-> glitched texture at the top of the chest

**To Reproduce**
1. place a chest
2.  look at it

**Expected behavior**
-> Hopefully find a way to fix this

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)
![2024-08-04_20 49 26](https://github.com/user-attachments/assets/228721fd-bb2c-42b3-97e5-a0c2ceed6043)

**Modpack version**
-> 2.9
**Java Version**
-> 1.20.1
**Modpack Launcher Used**
-> Prism
**Ram Allocated**
-> 8 GB

**Additional context**
-> no sir

**Comment by shiftthedev** [comment]
unable to replicate
