### ISSUE TITLE
JEI Doesn't show how to get Blutonium

### ISSUE THREAD

**Issue by malac0da13** [ChosenArchitect/Project-Architect-2#77]
**Is your feature request related to a problem? Please describe.**
->When you fin recipe to get blutonium it just say use dust. To get dust you just crush blutonium. No mention of cyanite reprocessing.

**Describe the solution you'd like**
->Mention Cyanite Reprocessor 

**Describe alternatives you've considered**
->

**Mod Sugestions**
->

**Additional context**
->

**Comment by ChosenArchitect** [comment]
This is a known issue... The mod dev never added the JEI support for the reprocessor

**Comment by ChosenArchitect** [comment]
I will add a tool tip onto it next update!
