### ISSUE TITLE
EMC loss when going through the sequenced assembly to assemble the first Final Star

### ISSUE THREAD

**Issue by James103** [ChosenArchitect/Project-Architect-2#78]
**Describe the bug**
Final Stars have EMC, but the EMC value of the Final Star is the same as that of a Colossal Star Omega, when it should either
A) be larger to account for the other ingredients, or
B) be 0 to make the star non-transmutable to encourage automation.

**To Reproduce**
1. Create a Final Star Shard by fusing together a Fading Matter Block (4,186,662,076,416 EMC) and Transmutation Tablet (2,228,488 EMC).
2. Craft a White Matter Block (1,120,676,118,528 EMC).
3. Craft a White Fuel Block (309,237,645,312 EMC).
4. Get some Liquid Hyper-Experience (500 mB costs 50 Glow Ink Sac and 50 Lapis Lazuli, totalling 44,000 EMC)
5. Repeat all of the above steps five more times (6 total repetitions at 5,616,578,112,744 EMC each = 33,699,468,676,464 EMC)
6. Craft a Colossal Star Omega (422,212,465,065,984 EMC).
7. Put all of the above together through the sequenced assembly to get the Final Star.

Expected EMC value: around 422,212,465,065,984 (Colossal Star Omega) + 33,699,468,676,464 (other ingredients) = 455,911,933,742,448.
Actual EMC value: 422,212,465,065,984 (only the Colossal Star Omega)

**Expected behavior**
The EMC value of the Final Star should be larger than that of the Colossal Star Omega due to the additional ingredients. The full calculations are detailed above.

**Modpack version**
2.9 Hotfix
**Java Version**
17.0.3, using 64 (amd64) architecture, from Eclipse Adoptium
**Modpack Launcher Used**
Prism Launcher
**Ram Allocated**
6144 MB

**Comment by ChosenArchitect** [comment]
The final star isn't supposed to have EMC! This will be fixed in next update
