### ISSUE TITLE
Early Game EMC Dupe

### ISSUE THREAD

**Issue by CurtisT15** [ChosenArchitect/Project-Architect-2#8]
There is an early game EMC dupe that makes gathering EMC too easy at the start.  You can put magma blocks into a multiservo press with a unpacking die, and receive 4 magma creams. Magma blocks have a value of 128 EMC and magma creams have a value of 1234 EMC each.

A multiservo press and stirling dynamo can be made within about an hour of starting a new world, and this dupe can create 4000 EMC/s with no upgrades in the machines. Within about 4 hours and some patience, you can be fully decked out in dark/red matter gear with a Red Katar. 

A simple solution to this would be removing that recipe from the multiservo press, if possible. If not, then increasing the value of the blocks, or decreasing the value of creams.

**Comment by ChosenArchitect** [comment]
we are doing a slight fixed to this but it will still be a dupe but those are intended!
