### ISSUE TITLE
Crash when trying to see the uses of Ender Chest

### ISSUE THREAD

**Issue by alex-3881** [ChosenArchitect/Project-Architect-2#80]
**Describe the bug**
-> If you press U on an ender chest, the game crashes

**To Reproduce**
1. Open JEI and hover over the ender chest
2. Press U

**Expected behavior**
-> Recipes that use the ender chest appear (or nothing happens if there's none)

**Modpack version**
-> 2.9 hotfix
**Java Version**
-> 17.0.11
**Modpack Launcher Used**
-> GDLauncher
**Ram Allocated**
-> 8G

[crash-2024-08-05_11.13.52-client.txt](https://github.com/user-attachments/files/16494415/crash-2024-08-05_11.13.52-client.txt)

**Comment by shiftthedev** [comment]
create known issue. https://github.com/Creators-of-Create/Create/issues/6368
waiting this fix https://github.com/Creators-of-Create/Create/commit/00e919b6c7d13065e394561410dab8873091e5cf to be released.

**Comment by IRicTheCoder** [comment]
A temporary fix for this was applied to the modpack while Create doesn't release the fix, should be already available in version 3.4+. Closing the issue as resolved
