### ISSUE TITLE
Wrong crafting recipes for logs

### ISSUE THREAD

**Issue by Powermania321** [ChosenArchitect/Project-Architect-2#81]
**Describe the bug**
->Wrong crafting recipe for various logs. 2 slabs crafted together result in a log.

**To Reproduce**
1. 
2. 
3. 
4. 

**Expected behavior**
-> Crafting 2 slabs together was the expected recipe for their respective planks

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)
![2024-08-05_22 21 30](https://github.com/user-attachments/assets/cb1a7768-3055-47a4-86a6-b0ab42413e3a)

**Modpack version**
-> 3.0
**Java Version**
->21.0.1
**Modpack Launcher Used**
-> Curseforge
**Ram Allocated**
->10gb

**Additional context**
->

**Comment by ChosenArchitect** [comment]
Fixed next update!
