### ISSUE TITLE
Rendering Issue - Sugar Cane

### ISSUE THREAD

**Issue by DiggityMan420** [ChosenArchitect/Project-Architect-2#82]
**Describe the bug**
->just sugar cane as of now

**To Reproduce**
1. log in
2. look at sugarcane growing

**Expected behavior**
-> see images

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)
![Screenshot_49](https://github.com/user-attachments/assets/8379d829-44d5-43ae-a85c-431d5749daca)
![Screenshot_48](https://github.com/user-attachments/assets/2d42cc9d-592f-4ec4-ae0a-053c4977fe0e)
![Screenshot_47](https://github.com/user-attachments/assets/4ad02a93-c97c-4aea-88d5-a642557198be)

**Modpack version**
-> 3.0
**Java Version**
-> 21.0.4 64bit
**Modpack Launcher Used**
-> curseforge

**Ram Allocated**
-> 10gb

**Additional context**
-> i did delete the lines in the options file "resourcePacks" and "incompatibleResourcePacks"

**Comment by ChosenArchitect** [comment]
should be fixed next update!
