### ISSUE TITLE
Pig mis placed textures

### ISSUE THREAD

**Issue by XenonsTech** [ChosenArchitect/Project-Architect-2#83]
**Describe the bug**
-> The pig textures are mixed up the eyes are on the feet, the back is gone, ect,

**To Reproduce**
1.  Look at a pig in any world

**Expected behavior**
-> Fix the textures (via  resource packs)

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)
![2024-08-05_20 14 12](https://github.com/user-attachments/assets/cef1e5ad-a23b-4db4-b12d-6538ecf01ab8)

**Modpack version**
-> I think 2-3.0
**Java Version**
-> 1.20.1
**Modpack Launcher Used**
-> curseforge (I switched!)
**Ram Allocated**
-> 10 gb

**Additional context**
-> I tried to reset my mod pack remade it and swapped launchers it all didn't help

**Comment by ChosenArchitect** [comment]
Should be fixed next update!
