### ISSUE TITLE
Shift-Clicking Recipe into crafting grid broken

### ISSUE THREAD

**Issue by pilotcam** [ChosenArchitect/Project-Architect-2#84]
**Describe the bug**
When using JEI to look at a crafting recipe, the "+" button works to move items... but "Shift +" to insert multiple crafts does not work.  This was working in 2.8.  Broken in 3.0

**To Reproduce**
1.  Have items in inventory to craft something (e.g. 2 oak logs to craft 4 planks)
2.  Open inventory and find the oak planks recipe
3.  Shift-Click the "+" button.  Nothing Happens
4. Click the "+" button.  One log is moved to the crafting grid

**Expected behavior**
Shift "+" should have moved all the logs into the crafting grid

**Screenshots**
![2024-08-05_21 31 16](https://github.com/user-attachments/assets/1642bd53-e064-4e7c-a7bd-d73fef47e9a7)

**Modpack version**
3.0
**Java Version**
OpenJDK 17.0.8
**Modpack Launcher Used**
CurseForge
**Ram Allocated**
10GB

**Additional context**
Another user on discord talked about the Ctrl-Click being broken to have AE2 auto-craft missing items.  Maybe related.

**Comment by ChosenArchitect** [comment]
Should be fixed in next update!
