### ISSUE TITLE
Duplicating Source Gem with a Multiservo Press and an Unpacking Die

### ISSUE THREAD

**Issue by ZahRizi** [ChosenArchitect/Project-Architect-2#85]
**Describe the bug**
->You can use the multiservo press to turn a source gem block(which needs 4 source gem to craft) to 9 source gem with only 400 RF

**To Reproduce**
1. Make a multiservo press and the unpacking die
2. Take some source gem block
3. Uncraft the block
4. Gain an extra 5 gem in the process

**Expected behavior**
->You gain 4 source gem per block

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)
![2024-08-06_09 46 03](https://github.com/user-attachments/assets/6790ba3f-12cf-4c06-b5e8-2abc9bf3e69c)

**Modpack version**
->3.0
**Java Version**
->17.0.8
**Modpack Launcher Used**
->Curseforge
**Ram Allocated**
->8GB

**Additional context**
->

**Comment by ChosenArchitect** [comment]
fixed next update!
