### ISSUE TITLE
JEI BUG FOUND

### ISSUE THREAD

**Issue by GD3000MTG** [ChosenArchitect/Project-Architect-2#86]
**Describe the bug**
-> i cannot control + click on recopies to request crafting in ae2/rs

**To Reproduce**
1. control + click a recipe with ae2 to a recipe you have patterns for
2. 
3. 
4. 

**Expected behavior**
->

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)

**Modpack version**
-> 3.0
**Java Version**
-> OpenJDK 17.0.8
**Modpack Launcher Used**
-> curseforge as all players should
**Ram Allocated**
-> 12096 mb / 12gb

**Additional context**
->

**Comment by twsx** [comment]
Same issue.  
I _think_ it started with the update to 3.0, but can't be sure.

**Comment by twsx** [comment]
Can confirm both, that downgrading to 2.9hotfix fixes this issue, and that once again upgrading to 3.0 breaks it again.

JEI was updated with 3.0 so that ought to be it.

#84 is likely a related issue.

**Comment by ChosenArchitect** [comment]
should be fixed in next update
