### ISSUE TITLE
Fluid Absorber wont absorbe Liquid Ethylene

### ISSUE THREAD

**Issue by LordMorketh** [ChosenArchitect/Project-Architect-2#87]
**Describe the bug**
->The Dimlet workbench for RF Tools asks for a fluid absorber set for Liquid Ethylene (Mekanism) to create a fluid dimlet for Liquid Ethylene (Mekanism), but the Fluid Absorber will not absorb Liquid Ethylene when placed above a source block of that fluid.

**To Reproduce**
1. 
2. 
3. 
4. 

**Expected behavior**
->

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)

**Modpack version**
->
**Java Version**
->
**Modpack Launcher Used**
->
**Ram Allocated**
->

**Additional context**
->

**Comment by shiftthedev** [comment]
Mekanism liquids are disable in RF dimlets.
