### ISSUE TITLE
No EMC value assigned for Malachite

### ISSUE THREAD

**Issue by James103** [ChosenArchitect/Project-Architect-2#88]
**Describe the bug**
From the changelog for Project Architect 2, version 2.9:
> Added EMC Values to [...] Enlightened raw ores

However, no EMC value was assigned to Malachite, which is needed to make an Ender Chest due to recipe changes caused by the Enlightend mod.

**To Reproduce**
Check JEI (search `malachite`) and notice no EMC value is assigned to Malachite.

**Expected behavior**
Malachite should have an EMC value, in order to avoid players needing to explore and mine out the mineral in large quantities just to make some Ender Chests. (Players will still need to mine at least one of the mineral to be able to learn it and transmute more from their EMC.)

**Modpack version**
3.0
**Java Version**
17.0.3, using 64 (amd64) architecture, from Eclipse Adoptium.
**Modpack Launcher Used**
Prism Launcher
**Ram Allocated**
6144 MB

**Comment by ChosenArchitect** [comment]
I did add value to it but also fixed ender chest recipe
