### ISSUE TITLE
Server Crashes when trying to go to the Nether

### ISSUE THREAD

**Issue by jbullen1** [ChosenArchitect/Project-Architect-2#89]
**Describe the bug**
Every time I try to go to the Nether, the server crashes and restarts.  The server is hosted on BisectHosting.  I'm on version 3.0 with a clean install.

**To Reproduce**
1. Build Nether Portal
2. Enter Nether Portal
3. 
4. 

**Expected behavior**
I go to the Nether
->

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)

**Modpack version**
-> 3.0

**Java Version**
-> server is running Java17

**Modpack Launcher Used**
-> Curse Forge

**Ram Allocated**
->Client:  11gb
    Server:  8gb

**Additional context**
-> I added the server crash log to this ticket.
I tested and can go to the Nether in a single player world.

[crash-2024-08-05_22.34.08-server.txt](https://github.com/user-attachments/files/16510888/crash-2024-08-05_22.34.08-server.txt)

**Comment by shiftthedev** [comment]
disable watchdog by setting max-tick-time in server.properties to -1

**Comment by jbullen1** [comment]
That fixed it.  The client crashed the first time I tired to go to the nether after making the change and restarting the server.  But when I logged back in, I was in the nether.

Thanks for your help.
