### ISSUE TITLE
Cant load into world 

### ISSUE THREAD

**Issue by fourskinfairy** [ChosenArchitect/Project-Architect-2#9]
Every time I try opening the world that I have been playing it goes through loading terrain and then shows a blank screen with the dirt background. Then begins to not respond which forces me to force quit the program. I have had this issue with previous modpacks and dont know if it has something to do with either my CPU, RAM or something else. 

Project Architect 2-2.0 

GDLauncher Carbon 

8192MB allocated 

My specs:
32 GB Ram 
Processor: Intel i5-9600KF CPU @3.70GHz

**Comment by ChosenArchitect** [comment]
You can always give this a try
To enable the error fixing Forge setting for 1.13 and newer, please follow these steps:

Navigate to your instance folder and click your world folder. In this example, my world is called my-forge-world.

Within your world folder, click the folder called serverconfig.

Find the file forge-server.toml and click Edit.

Scroll down until you find the settings removeErroringEntities and removeErroringTileEntities which we've highlighted below.

Change both of the settings from false to true as shown below.

Then simply save the file and relaunch your modpack. When your pack starts, the new settings will take effect. When you next connect to your save and load the chunk with the ticking block entity, Forge will attempt to automatically remove the block which is causing issues.

Once the problem has been fixed, we recommend changing the settings back to false to prevent any issues with your world.

**Comment by IRicTheCoder** [comment]
This has been here for a while without any feedback. Night Config Fixes added in 3.6, or the provided potential solutions should help fix the issue. Closing this as resolved.
