### ISSUE TITLE
Travel Anchor slow breaking and not dropping

### ISSUE THREAD

**Issue by mikeyboy52** [ChosenArchitect/Project-Architect-2#90]
**Describe the bug**
-> when you have placed a travel anchor there is no way to break it and that it drops

**To Reproduce**
1. place a travel anchor
2. try and break a travel anchor with any tool

**Expected behavior**
-> when you break the travel anchor you should get it back, and you should be able to break it with a tool (i don't know which one)

**Modpack version**
-> 3.0
**Java Version**
-> 1.20.1
**Modpack Launcher Used**
-> curseforge
**Ram Allocated**
-> 10036 mb

**Additional context**
-> i don't know for sure if this is a bug or i am missing

**Comment by ChosenArchitect** [comment]
Will fix next update!
