### ISSUE TITLE
Travel Anchor does not drop when mined

### ISSUE THREAD

**Issue by Sw0rdSaint** [ChosenArchitect/Project-Architect-2#92]
**Describe the bug**
-> Travel Anchor does not drop when mined

**To Reproduce**
1. used obsidian paxel with silk touch and diamond pickarang with fortune to mine travel anchor
2. travel anchor does not drop , have magnet in curio and pick-up attachment in back-pack

**Expected behavior**
-> expected to get travel anchors back

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)

**Comment by mikeyboy52** [comment]
I also reported this bug and it should be fixed next update

**Comment by shiftthedev** [comment]
have you tried in 3.1?

**Comment by Sw0rdSaint** [comment]
I can confirm issue is now resolved in 3.1, kindly close ticket. thanks!
