### ISSUE TITLE
[Suggestion?] Add Multiservo Press Recipes for Create Deco and Create Utilities Sheets

### ISSUE THREAD

**Issue by bwuhh** [ChosenArchitect/Project-Architect-2#94]
Most plates/sheets are able to be made via both the Multiservo Press and the Mechanical Press:
![image](https://github.com/user-attachments/assets/5cc83f13-b43f-40d8-9d76-36746d98e17c)

Create Deco and Create Utilities' sheets are missing the same treatment:
![image](https://github.com/user-attachments/assets/dc04dbac-4da3-4cce-b20b-b46ca24cd627)

It would be convenient if a multiservo press recipe was added for them too.
I should add that these images were taken in ver 3.0 of the modpack. Although it could already have been changed in 3.1, patch notes do not say such.

**Comment by IRicTheCoder** [comment]
This suggestion was added in version 3.4, all sheets should now be available in Thermal Press. Closing issue as added.
