### ISSUE TITLE
Infinite "Saving World"

### ISSUE THREAD

**Issue by Aramid** [ChosenArchitect/Project-Architect-2#96]
**Describe the bug**
->Stuck in "Saving world" when leaving my game, if my base is loaded. (A specific chunk apparently)

**To Reproduce**
1. Have a base with 2 Reactor, a create elevator and a bunch of other automated things. Got a wither stasis chamber/crusher, and a rotten egg mob farm with crusher.
2. Leave the game with "Save & Quit"
3. Somehow get stuck. 

**Expected behavior**
->The game save the game in less that 5248579 hours and get back to menu.

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)

**Modpack version**
->2.9, 3.0, 3.1
**Java Version**
->No idea
**Modpack Launcher Used**
-> ATLauncher
**Ram Allocated**
-> 8giga, then 16.

**Additional context**
-> Went up to 20 minutes without saving. Can share save.
My java is marked as "Java Provided by Minecraft" by ATLauncher. Don't know if it is of any use.
Java Parameters (don't know if they are in the log) :
-XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
[latest.log.gz](https://github.com/user-attachments/files/16514515/latest.log.gz)

**Comment by Aramid** [comment]
Ok, I suppose i'm on my own on this one ? (Because it's still there with the last update)

**Comment by XenonsTech** [comment]
Im having the same issue haven't found a solution yet i'll let you know if
I do.
