### ISSUE TITLE
dup glitch

### ISSUE THREAD

**Issue by zak-12345** [ChosenArchitect/Project-Architect-2#97]
**Describe the bug**
->you can turn 3 gold ores into diamonds then turn that diamond into gold again

**To Reproduce**
1. get an enrichment chamber 
2. then connect it to a furnace
3. hook it up with a crafter with a pattern that turns gold into diamonds with the philosopher stone
4. make an energy condenser that takes diamonds then turns it into gold ore
5. then connect it to the enrichment chamber
if you fill the buffer and get an energy condenser mk 2 you can get 30 million in an hour
**Expected behavior**
->messes up progression

**Screenshots**
If applicable, add screenshots to help explain your problem. (Use F2 to take a screenshot in-game)

**Modpack version**
->latest
**Java Version**
->latest
**Modpack Launcher Used**
->official launcher
**Ram Allocated**
->8gb

**Additional context**
->i don't think it's fixable

**Comment by shiftthedev** [comment]
i see nothing wrong here

**Comment by ChosenArchitect** [comment]
This is a process that you can 100% do as you need to process the items :D See I tricked you into automation!
