### ISSUE TITLE
ChiselChippedIntegration - Way too easy EMC Dupe

### ISSUE THREAD

**Issue by Erwin2Punkt0** [ChosenArchitect/Project-Architect-2#98]
The Mod Chisel Chipped Integration adds a few Blocks, the Caution Framed block has a recipe costing less EMC to craft then the crafted Items are worth. So it offers a way too easy EMC dupe, just requiering to have some redstone.

Solution:
1. Decrease EMC value for this block
2. Make recipe slightly more expensive
3. Craft one instead of 24 Blocks at once

**Comment by ChosenArchitect** [comment]
fixed next update!
