### ISSUE TITLE
Stack refill only refills from hotbar, not inventory

### ISSUE THREAD

**Issue by James103** [ChosenArchitect/Project-Architect-2#99]
**Describe the bug**
The mod(s) responsible for automatically refilling stacks from the player's inventory only works for stacks of a similar item type in the player's _hotbar_, not the rest of their inventory.

See https://youtu.be/qYQb7ZOdRjY?t=213 for the bug in action.

This is very likely caused by a mod or an interaction between two or more mods.

**To Reproduce**
1. Place one item of stone in the player's main hand.
2. Place one item of stone elsewhere in the player's hotbar, in a separate stack.
3. Place stone elsewhere in the player's inventory, excluding the hotbar.
4. Start placing the stone blocks.
5. After the first stack runs out, the second stack in the hotbar is swapped in.
6. After the second stack runs out, no more stacks are left in the hotbar. It looks like a stack was swapped in from the rest of the player's inventory, however, it isn't and one has to move the stack manually.

**Expected behavior**
I would expect automatically refilling item stacks to work for items from anywhere in the player's hotbar and main inventory, instead of hotbar only.

**Modpack version**
3.1
**Java Version**
17.0.3, using 64 (amd64) architecture, from Eclipse Adoptium.
**Modpack Launcher Used**
Prism Launcher
**Ram Allocated**
6144 MB

**Comment by IRicTheCoder** [comment]
Unsure how this is happening, tested it myself a few hours ago and it was working correctly. Might be related to un-stackable items or something similar in some cases, but that wouldn't fit your case. Did you test this issue more? Any more feedback?

**Comment by IRicTheCoder** [comment]
Waited for 2 weeks for feedback on this, as of version 4.0 this does not seem to be an issue anymore. Closing this as solved, feel free to reopen if the issue continues.
